/**
 * Generated by scripts/generate-icons.js.
 * DO NOT EDIT!
 */

export { default as IconBusinessColor1 }
      from './business-color/BusinessColor1';
export { default as IconBusinessColor10 }
      from './business-color/BusinessColor10';
export { default as IconBusinessColor11 }
      from './business-color/BusinessColor11';
export { default as IconBusinessColor12 }
      from './business-color/BusinessColor12';
export { default as IconBusinessColor13 }
      from './business-color/BusinessColor13';
export { default as IconBusinessColor14 }
      from './business-color/BusinessColor14';
export { default as IconBusinessColor15 }
      from './business-color/BusinessColor15';
export { default as IconBusinessColor16 }
      from './business-color/BusinessColor16';
export { default as IconBusinessColor17 }
      from './business-color/BusinessColor17';
export { default as IconBusinessColor18 }
      from './business-color/BusinessColor18';
export { default as IconBusinessColor19 }
      from './business-color/BusinessColor19';
export { default as IconBusinessColor2 }
      from './business-color/BusinessColor2';
export { default as IconBusinessColor20 }
      from './business-color/BusinessColor20';
export { default as IconBusinessColor21 }
      from './business-color/BusinessColor21';
export { default as IconBusinessColor22 }
      from './business-color/BusinessColor22';
export { default as IconBusinessColor23 }
      from './business-color/BusinessColor23';
export { default as IconBusinessColor24 }
      from './business-color/BusinessColor24';
export { default as IconBusinessColor25 }
      from './business-color/BusinessColor25';
export { default as IconBusinessColor26 }
      from './business-color/BusinessColor26';
export { default as IconBusinessColor27 }
      from './business-color/BusinessColor27';
export { default as IconBusinessColor28 }
      from './business-color/BusinessColor28';
export { default as IconBusinessColor29 }
      from './business-color/BusinessColor29';
export { default as IconBusinessColor3 }
      from './business-color/BusinessColor3';
export { default as IconBusinessColor30 }
      from './business-color/BusinessColor30';
export { default as IconBusinessColor31 }
      from './business-color/BusinessColor31';
export { default as IconBusinessColor32 }
      from './business-color/BusinessColor32';
export { default as IconBusinessColor33 }
      from './business-color/BusinessColor33';
export { default as IconBusinessColor34 }
      from './business-color/BusinessColor34';
export { default as IconBusinessColor35 }
      from './business-color/BusinessColor35';
export { default as IconBusinessColor36 }
      from './business-color/BusinessColor36';
export { default as IconBusinessColor37 }
      from './business-color/BusinessColor37';
export { default as IconBusinessColor38 }
      from './business-color/BusinessColor38';
export { default as IconBusinessColor39 }
      from './business-color/BusinessColor39';
export { default as IconBusinessColor4 }
      from './business-color/BusinessColor4';
export { default as IconBusinessColor40 }
      from './business-color/BusinessColor40';
export { default as IconBusinessColor5 }
      from './business-color/BusinessColor5';
export { default as IconBusinessColor6 }
      from './business-color/BusinessColor6';
export { default as IconBusinessColor7 }
      from './business-color/BusinessColor7';
export { default as IconBusinessColor8 }
      from './business-color/BusinessColor8';
export { default as IconBusinessColor9 }
      from './business-color/BusinessColor9';
