/**
 * Generated by scripts/generate-icons.js.
 * DO NOT EDIT!
 */

export { default as IconFoodDishesColor1 }
      from './food-dishes-color/FoodDishesColor1';
export { default as IconFoodDishesColor10 }
      from './food-dishes-color/FoodDishesColor10';
export { default as IconFoodDishesColor11 }
      from './food-dishes-color/FoodDishesColor11';
export { default as IconFoodDishesColor12 }
      from './food-dishes-color/FoodDishesColor12';
export { default as IconFoodDishesColor13 }
      from './food-dishes-color/FoodDishesColor13';
export { default as IconFoodDishesColor14 }
      from './food-dishes-color/FoodDishesColor14';
export { default as IconFoodDishesColor15 }
      from './food-dishes-color/FoodDishesColor15';
export { default as IconFoodDishesColor2 }
      from './food-dishes-color/FoodDishesColor2';
export { default as IconFoodDishesColor3 }
      from './food-dishes-color/FoodDishesColor3';
export { default as IconFoodDishesColor4 }
      from './food-dishes-color/FoodDishesColor4';
export { default as IconFoodDishesColor5 }
      from './food-dishes-color/FoodDishesColor5';
export { default as IconFoodDishesColor6 }
      from './food-dishes-color/FoodDishesColor6';
export { default as IconFoodDishesColor7 }
      from './food-dishes-color/FoodDishesColor7';
export { default as IconFoodDishesColor8 }
      from './food-dishes-color/FoodDishesColor8';
export { default as IconFoodDishesColor9 }
      from './food-dishes-color/FoodDishesColor9';
