/**
 * Generated by scripts/generate-icons.js.
 * DO NOT EDIT!
 */

export { default as IconHomeColor1 }
      from './home-color/HomeColor1';
export { default as IconHomeColor10 }
      from './home-color/HomeColor10';
export { default as IconHomeColor11 }
      from './home-color/HomeColor11';
export { default as IconHomeColor12 }
      from './home-color/HomeColor12';
export { default as IconHomeColor13 }
      from './home-color/HomeColor13';
export { default as IconHomeColor14 }
      from './home-color/HomeColor14';
export { default as IconHomeColor15 }
      from './home-color/HomeColor15';
export { default as IconHomeColor16 }
      from './home-color/HomeColor16';
export { default as IconHomeColor2 }
      from './home-color/HomeColor2';
export { default as IconHomeColor3 }
      from './home-color/HomeColor3';
export { default as IconHomeColor4 }
      from './home-color/HomeColor4';
export { default as IconHomeColor5 }
      from './home-color/HomeColor5';
export { default as IconHomeColor6 }
      from './home-color/HomeColor6';
export { default as IconHomeColor7 }
      from './home-color/HomeColor7';
export { default as IconHomeColor8 }
      from './home-color/HomeColor8';
export { default as IconHomeColor9 }
      from './home-color/HomeColor9';
