/**
 * Generated by scripts/generate-icons.js.
 * DO NOT EDIT!
 */

export { default as IconKitchenColor1 }
      from './kitchen-color/KitchenColor1';
export { default as IconKitchenColor10 }
      from './kitchen-color/KitchenColor10';
export { default as IconKitchenColor11 }
      from './kitchen-color/KitchenColor11';
export { default as IconKitchenColor12 }
      from './kitchen-color/KitchenColor12';
export { default as IconKitchenColor13 }
      from './kitchen-color/KitchenColor13';
export { default as IconKitchenColor14 }
      from './kitchen-color/KitchenColor14';
export { default as IconKitchenColor15 }
      from './kitchen-color/KitchenColor15';
export { default as IconKitchenColor16 }
      from './kitchen-color/KitchenColor16';
export { default as IconKitchenColor2 }
      from './kitchen-color/KitchenColor2';
export { default as IconKitchenColor3 }
      from './kitchen-color/KitchenColor3';
export { default as IconKitchenColor4 }
      from './kitchen-color/KitchenColor4';
export { default as IconKitchenColor5 }
      from './kitchen-color/KitchenColor5';
export { default as IconKitchenColor6 }
      from './kitchen-color/KitchenColor6';
export { default as IconKitchenColor7 }
      from './kitchen-color/KitchenColor7';
export { default as IconKitchenColor8 }
      from './kitchen-color/KitchenColor8';
export { default as IconKitchenColor9 }
      from './kitchen-color/KitchenColor9';
