/**
 * Generated by scripts/generate-icons.js.
 * DO NOT EDIT!
 */

export { default as IconKnifeColor1 }
      from './knife-color/KnifeColor1';
export { default as IconKnifeColor10 }
      from './knife-color/KnifeColor10';
export { default as IconKnifeColor11 }
      from './knife-color/KnifeColor11';
export { default as IconKnifeColor12 }
      from './knife-color/KnifeColor12';
export { default as IconKnifeColor13 }
      from './knife-color/KnifeColor13';
export { default as IconKnifeColor14 }
      from './knife-color/KnifeColor14';
export { default as IconKnifeColor15 }
      from './knife-color/KnifeColor15';
export { default as IconKnifeColor16 }
      from './knife-color/KnifeColor16';
export { default as IconKnifeColor2 }
      from './knife-color/KnifeColor2';
export { default as IconKnifeColor3 }
      from './knife-color/KnifeColor3';
export { default as IconKnifeColor4 }
      from './knife-color/KnifeColor4';
export { default as IconKnifeColor5 }
      from './knife-color/KnifeColor5';
export { default as IconKnifeColor6 }
      from './knife-color/KnifeColor6';
export { default as IconKnifeColor7 }
      from './knife-color/KnifeColor7';
export { default as IconKnifeColor8 }
      from './knife-color/KnifeColor8';
export { default as IconKnifeColor9 }
      from './knife-color/KnifeColor9';
