/**
 * Generated by scripts/generate-icons.js.
 * DO NOT EDIT!
 */

export { default as IconLawColor1 }
      from './law-color/LawColor1';
export { default as IconLawColor10 }
      from './law-color/LawColor10';
export { default as IconLawColor11 }
      from './law-color/LawColor11';
export { default as IconLawColor12 }
      from './law-color/LawColor12';
export { default as IconLawColor13 }
      from './law-color/LawColor13';
export { default as IconLawColor14 }
      from './law-color/LawColor14';
export { default as IconLawColor15 }
      from './law-color/LawColor15';
export { default as IconLawColor16 }
      from './law-color/LawColor16';
export { default as IconLawColor2 }
      from './law-color/LawColor2';
export { default as IconLawColor3 }
      from './law-color/LawColor3';
export { default as IconLawColor4 }
      from './law-color/LawColor4';
export { default as IconLawColor5 }
      from './law-color/LawColor5';
export { default as IconLawColor6 }
      from './law-color/LawColor6';
export { default as IconLawColor7 }
      from './law-color/LawColor7';
export { default as IconLawColor8 }
      from './law-color/LawColor8';
export { default as IconLawColor9 }
      from './law-color/LawColor9';
