/**
 * Generated by scripts/generate-icons.js.
 * DO NOT EDIT!
 */

export { default as IconLeafColor1 }
      from './leaf-color/LeafColor1';
export { default as IconLeafColor10 }
      from './leaf-color/LeafColor10';
export { default as IconLeafColor11 }
      from './leaf-color/LeafColor11';
export { default as IconLeafColor12 }
      from './leaf-color/LeafColor12';
export { default as IconLeafColor13 }
      from './leaf-color/LeafColor13';
export { default as IconLeafColor14 }
      from './leaf-color/LeafColor14';
export { default as IconLeafColor15 }
      from './leaf-color/LeafColor15';
export { default as IconLeafColor16 }
      from './leaf-color/LeafColor16';
export { default as IconLeafColor2 }
      from './leaf-color/LeafColor2';
export { default as IconLeafColor3 }
      from './leaf-color/LeafColor3';
export { default as IconLeafColor4 }
      from './leaf-color/LeafColor4';
export { default as IconLeafColor5 }
      from './leaf-color/LeafColor5';
export { default as IconLeafColor6 }
      from './leaf-color/LeafColor6';
export { default as IconLeafColor7 }
      from './leaf-color/LeafColor7';
export { default as IconLeafColor8 }
      from './leaf-color/LeafColor8';
export { default as IconLeafColor9 }
      from './leaf-color/LeafColor9';
