/**
 * Generated by scripts/generate-icons.js.
 * DO NOT EDIT!
 */

export { default as IconLogisticsColor1 }
      from './logistics-color/LogisticsColor1';
export { default as IconLogisticsColor10 }
      from './logistics-color/LogisticsColor10';
export { default as IconLogisticsColor11 }
      from './logistics-color/LogisticsColor11';
export { default as IconLogisticsColor12 }
      from './logistics-color/LogisticsColor12';
export { default as IconLogisticsColor13 }
      from './logistics-color/LogisticsColor13';
export { default as IconLogisticsColor14 }
      from './logistics-color/LogisticsColor14';
export { default as IconLogisticsColor15 }
      from './logistics-color/LogisticsColor15';
export { default as IconLogisticsColor16 }
      from './logistics-color/LogisticsColor16';
export { default as IconLogisticsColor17 }
      from './logistics-color/LogisticsColor17';
export { default as IconLogisticsColor18 }
      from './logistics-color/LogisticsColor18';
export { default as IconLogisticsColor19 }
      from './logistics-color/LogisticsColor19';
export { default as IconLogisticsColor2 }
      from './logistics-color/LogisticsColor2';
export { default as IconLogisticsColor20 }
      from './logistics-color/LogisticsColor20';
export { default as IconLogisticsColor21 }
      from './logistics-color/LogisticsColor21';
export { default as IconLogisticsColor22 }
      from './logistics-color/LogisticsColor22';
export { default as IconLogisticsColor23 }
      from './logistics-color/LogisticsColor23';
export { default as IconLogisticsColor24 }
      from './logistics-color/LogisticsColor24';
export { default as IconLogisticsColor25 }
      from './logistics-color/LogisticsColor25';
export { default as IconLogisticsColor26 }
      from './logistics-color/LogisticsColor26';
export { default as IconLogisticsColor27 }
      from './logistics-color/LogisticsColor27';
export { default as IconLogisticsColor28 }
      from './logistics-color/LogisticsColor28';
export { default as IconLogisticsColor29 }
      from './logistics-color/LogisticsColor29';
export { default as IconLogisticsColor3 }
      from './logistics-color/LogisticsColor3';
export { default as IconLogisticsColor30 }
      from './logistics-color/LogisticsColor30';
export { default as IconLogisticsColor31 }
      from './logistics-color/LogisticsColor31';
export { default as IconLogisticsColor32 }
      from './logistics-color/LogisticsColor32';
export { default as IconLogisticsColor33 }
      from './logistics-color/LogisticsColor33';
export { default as IconLogisticsColor34 }
      from './logistics-color/LogisticsColor34';
export { default as IconLogisticsColor35 }
      from './logistics-color/LogisticsColor35';
export { default as IconLogisticsColor36 }
      from './logistics-color/LogisticsColor36';
export { default as IconLogisticsColor37 }
      from './logistics-color/LogisticsColor37';
export { default as IconLogisticsColor38 }
      from './logistics-color/LogisticsColor38';
export { default as IconLogisticsColor39 }
      from './logistics-color/LogisticsColor39';
export { default as IconLogisticsColor4 }
      from './logistics-color/LogisticsColor4';
export { default as IconLogisticsColor40 }
      from './logistics-color/LogisticsColor40';
export { default as IconLogisticsColor5 }
      from './logistics-color/LogisticsColor5';
export { default as IconLogisticsColor6 }
      from './logistics-color/LogisticsColor6';
export { default as IconLogisticsColor7 }
      from './logistics-color/LogisticsColor7';
export { default as IconLogisticsColor8 }
      from './logistics-color/LogisticsColor8';
export { default as IconLogisticsColor9 }
      from './logistics-color/LogisticsColor9';
