/**
 * Generated by scripts/generate-icons.js.
 * DO NOT EDIT!
 */

export { default as IconMusicColor1 }
      from './music-color/MusicColor1';
export { default as IconMusicColor10 }
      from './music-color/MusicColor10';
export { default as IconMusicColor11 }
      from './music-color/MusicColor11';
export { default as IconMusicColor12 }
      from './music-color/MusicColor12';
export { default as IconMusicColor13 }
      from './music-color/MusicColor13';
export { default as IconMusicColor14 }
      from './music-color/MusicColor14';
export { default as IconMusicColor15 }
      from './music-color/MusicColor15';
export { default as IconMusicColor16 }
      from './music-color/MusicColor16';
export { default as IconMusicColor2 }
      from './music-color/MusicColor2';
export { default as IconMusicColor3 }
      from './music-color/MusicColor3';
export { default as IconMusicColor4 }
      from './music-color/MusicColor4';
export { default as IconMusicColor5 }
      from './music-color/MusicColor5';
export { default as IconMusicColor6 }
      from './music-color/MusicColor6';
export { default as IconMusicColor7 }
      from './music-color/MusicColor7';
export { default as IconMusicColor8 }
      from './music-color/MusicColor8';
export { default as IconMusicColor9 }
      from './music-color/MusicColor9';
