/**
 * Generated by scripts/generate-icons.js.
 * DO NOT EDIT!
 */

export { default as IconShoppingColor1 }
      from './shopping-color/ShoppingColor1';
export { default as IconShoppingColor10 }
      from './shopping-color/ShoppingColor10';
export { default as IconShoppingColor11 }
      from './shopping-color/ShoppingColor11';
export { default as IconShoppingColor12 }
      from './shopping-color/ShoppingColor12';
export { default as IconShoppingColor13 }
      from './shopping-color/ShoppingColor13';
export { default as IconShoppingColor14 }
      from './shopping-color/ShoppingColor14';
export { default as IconShoppingColor15 }
      from './shopping-color/ShoppingColor15';
export { default as IconShoppingColor16 }
      from './shopping-color/ShoppingColor16';
export { default as IconShoppingColor2 }
      from './shopping-color/ShoppingColor2';
export { default as IconShoppingColor3 }
      from './shopping-color/ShoppingColor3';
export { default as IconShoppingColor4 }
      from './shopping-color/ShoppingColor4';
export { default as IconShoppingColor5 }
      from './shopping-color/ShoppingColor5';
export { default as IconShoppingColor6 }
      from './shopping-color/ShoppingColor6';
export { default as IconShoppingColor7 }
      from './shopping-color/ShoppingColor7';
export { default as IconShoppingColor8 }
      from './shopping-color/ShoppingColor8';
export { default as IconShoppingColor9 }
      from './shopping-color/ShoppingColor9';
