/**
 * Generated by scripts/generate-icons.js.
 * DO NOT EDIT!
 */

export { default as IconShoppingGrey1 }
      from './shopping-grey/ShoppingGrey1';
export { default as IconShoppingGrey10 }
      from './shopping-grey/ShoppingGrey10';
export { default as IconShoppingGrey11 }
      from './shopping-grey/ShoppingGrey11';
export { default as IconShoppingGrey12 }
      from './shopping-grey/ShoppingGrey12';
export { default as IconShoppingGrey13 }
      from './shopping-grey/ShoppingGrey13';
export { default as IconShoppingGrey14 }
      from './shopping-grey/ShoppingGrey14';
export { default as IconShoppingGrey15 }
      from './shopping-grey/ShoppingGrey15';
export { default as IconShoppingGrey16 }
      from './shopping-grey/ShoppingGrey16';
export { default as IconShoppingGrey2 }
      from './shopping-grey/ShoppingGrey2';
export { default as IconShoppingGrey3 }
      from './shopping-grey/ShoppingGrey3';
export { default as IconShoppingGrey4 }
      from './shopping-grey/ShoppingGrey4';
export { default as IconShoppingGrey5 }
      from './shopping-grey/ShoppingGrey5';
export { default as IconShoppingGrey6 }
      from './shopping-grey/ShoppingGrey6';
export { default as IconShoppingGrey7 }
      from './shopping-grey/ShoppingGrey7';
export { default as IconShoppingGrey8 }
      from './shopping-grey/ShoppingGrey8';
export { default as IconShoppingGrey9 }
      from './shopping-grey/ShoppingGrey9';
