/**
 * Generated by scripts/generate-icons.js.
 * DO NOT EDIT!
 */

export { default as IconSkullColor1 }
      from './skull-color/SkullColor1';
export { default as IconSkullColor10 }
      from './skull-color/SkullColor10';
export { default as IconSkullColor11 }
      from './skull-color/SkullColor11';
export { default as IconSkullColor12 }
      from './skull-color/SkullColor12';
export { default as IconSkullColor13 }
      from './skull-color/SkullColor13';
export { default as IconSkullColor14 }
      from './skull-color/SkullColor14';
export { default as IconSkullColor15 }
      from './skull-color/SkullColor15';
export { default as IconSkullColor16 }
      from './skull-color/SkullColor16';
export { default as IconSkullColor2 }
      from './skull-color/SkullColor2';
export { default as IconSkullColor3 }
      from './skull-color/SkullColor3';
export { default as IconSkullColor4 }
      from './skull-color/SkullColor4';
export { default as IconSkullColor5 }
      from './skull-color/SkullColor5';
export { default as IconSkullColor6 }
      from './skull-color/SkullColor6';
export { default as IconSkullColor7 }
      from './skull-color/SkullColor7';
export { default as IconSkullColor8 }
      from './skull-color/SkullColor8';
export { default as IconSkullColor9 }
      from './skull-color/SkullColor9';
