/**
 * Generated by scripts/generate-icons.js.
 * DO NOT EDIT!
 */

export { default as IconSpringColor1 }
      from './spring-color/SpringColor1';
export { default as IconSpringColor10 }
      from './spring-color/SpringColor10';
export { default as IconSpringColor11 }
      from './spring-color/SpringColor11';
export { default as IconSpringColor12 }
      from './spring-color/SpringColor12';
export { default as IconSpringColor13 }
      from './spring-color/SpringColor13';
export { default as IconSpringColor14 }
      from './spring-color/SpringColor14';
export { default as IconSpringColor15 }
      from './spring-color/SpringColor15';
export { default as IconSpringColor16 }
      from './spring-color/SpringColor16';
export { default as IconSpringColor2 }
      from './spring-color/SpringColor2';
export { default as IconSpringColor3 }
      from './spring-color/SpringColor3';
export { default as IconSpringColor4 }
      from './spring-color/SpringColor4';
export { default as IconSpringColor5 }
      from './spring-color/SpringColor5';
export { default as IconSpringColor6 }
      from './spring-color/SpringColor6';
export { default as IconSpringColor7 }
      from './spring-color/SpringColor7';
export { default as IconSpringColor8 }
      from './spring-color/SpringColor8';
export { default as IconSpringColor9 }
      from './spring-color/SpringColor9';
