/**
 * Generated by scripts/generate-icons.js.
 * DO NOT EDIT!
 */

export { default as IconSweet17Color1 }
      from './sweet-17-color/Sweet17Color1';
export { default as IconSweet17Color10 }
      from './sweet-17-color/Sweet17Color10';
export { default as IconSweet17Color11 }
      from './sweet-17-color/Sweet17Color11';
export { default as IconSweet17Color12 }
      from './sweet-17-color/Sweet17Color12';
export { default as IconSweet17Color13 }
      from './sweet-17-color/Sweet17Color13';
export { default as IconSweet17Color14 }
      from './sweet-17-color/Sweet17Color14';
export { default as IconSweet17Color15 }
      from './sweet-17-color/Sweet17Color15';
export { default as IconSweet17Color16 }
      from './sweet-17-color/Sweet17Color16';
export { default as IconSweet17Color17 }
      from './sweet-17-color/Sweet17Color17';
export { default as IconSweet17Color18 }
      from './sweet-17-color/Sweet17Color18';
export { default as IconSweet17Color19 }
      from './sweet-17-color/Sweet17Color19';
export { default as IconSweet17Color2 }
      from './sweet-17-color/Sweet17Color2';
export { default as IconSweet17Color20 }
      from './sweet-17-color/Sweet17Color20';
export { default as IconSweet17Color21 }
      from './sweet-17-color/Sweet17Color21';
export { default as IconSweet17Color22 }
      from './sweet-17-color/Sweet17Color22';
export { default as IconSweet17Color23 }
      from './sweet-17-color/Sweet17Color23';
export { default as IconSweet17Color24 }
      from './sweet-17-color/Sweet17Color24';
export { default as IconSweet17Color25 }
      from './sweet-17-color/Sweet17Color25';
export { default as IconSweet17Color3 }
      from './sweet-17-color/Sweet17Color3';
export { default as IconSweet17Color4 }
      from './sweet-17-color/Sweet17Color4';
export { default as IconSweet17Color5 }
      from './sweet-17-color/Sweet17Color5';
export { default as IconSweet17Color6 }
      from './sweet-17-color/Sweet17Color6';
export { default as IconSweet17Color7 }
      from './sweet-17-color/Sweet17Color7';
export { default as IconSweet17Color8 }
      from './sweet-17-color/Sweet17Color8';
export { default as IconSweet17Color9 }
      from './sweet-17-color/Sweet17Color9';
