/**
 * Generated by scripts/generate-icons.js.
 * DO NOT EDIT!
 */

export { default as IconTravelColor1 }
      from './travel-color/TravelColor1';
export { default as IconTravelColor10 }
      from './travel-color/TravelColor10';
export { default as IconTravelColor11 }
      from './travel-color/TravelColor11';
export { default as IconTravelColor12 }
      from './travel-color/TravelColor12';
export { default as IconTravelColor13 }
      from './travel-color/TravelColor13';
export { default as IconTravelColor14 }
      from './travel-color/TravelColor14';
export { default as IconTravelColor15 }
      from './travel-color/TravelColor15';
export { default as IconTravelColor16 }
      from './travel-color/TravelColor16';
export { default as IconTravelColor2 }
      from './travel-color/TravelColor2';
export { default as IconTravelColor3 }
      from './travel-color/TravelColor3';
export { default as IconTravelColor4 }
      from './travel-color/TravelColor4';
export { default as IconTravelColor5 }
      from './travel-color/TravelColor5';
export { default as IconTravelColor6 }
      from './travel-color/TravelColor6';
export { default as IconTravelColor7 }
      from './travel-color/TravelColor7';
export { default as IconTravelColor8 }
      from './travel-color/TravelColor8';
export { default as IconTravelColor9 }
      from './travel-color/TravelColor9';
