/**
 * Generated by scripts/generate-icons.js.
 * DO NOT EDIT!
 */

export { default as IconVirtualRealityColor1 }
      from './virtual-reality-color/VirtualRealityColor1';
export { default as IconVirtualRealityColor10 }
      from './virtual-reality-color/VirtualRealityColor10';
export { default as IconVirtualRealityColor11 }
      from './virtual-reality-color/VirtualRealityColor11';
export { default as IconVirtualRealityColor12 }
      from './virtual-reality-color/VirtualRealityColor12';
export { default as IconVirtualRealityColor13 }
      from './virtual-reality-color/VirtualRealityColor13';
export { default as IconVirtualRealityColor14 }
      from './virtual-reality-color/VirtualRealityColor14';
export { default as IconVirtualRealityColor15 }
      from './virtual-reality-color/VirtualRealityColor15';
export { default as IconVirtualRealityColor16 }
      from './virtual-reality-color/VirtualRealityColor16';
export { default as IconVirtualRealityColor2 }
      from './virtual-reality-color/VirtualRealityColor2';
export { default as IconVirtualRealityColor3 }
      from './virtual-reality-color/VirtualRealityColor3';
export { default as IconVirtualRealityColor4 }
      from './virtual-reality-color/VirtualRealityColor4';
export { default as IconVirtualRealityColor5 }
      from './virtual-reality-color/VirtualRealityColor5';
export { default as IconVirtualRealityColor6 }
      from './virtual-reality-color/VirtualRealityColor6';
export { default as IconVirtualRealityColor7 }
      from './virtual-reality-color/VirtualRealityColor7';
export { default as IconVirtualRealityColor8 }
      from './virtual-reality-color/VirtualRealityColor8';
export { default as IconVirtualRealityColor9 }
      from './virtual-reality-color/VirtualRealityColor9';
