/**
 * Generated by scripts/generate-icons.js.
 * DO NOT EDIT!
 */

import * as Icons from '../../4thofjuly-grey';

export const ICON_LIST = [
  { icon: Icons.Icon4ThofjulyGrey1, name: 'Icon4ThofjulyGrey1' },
  { icon: Icons.Icon4ThofjulyGrey10, name: 'Icon4ThofjulyGrey10' },
  { icon: Icons.Icon4ThofjulyGrey11, name: 'Icon4ThofjulyGrey11' },
  { icon: Icons.Icon4ThofjulyGrey12, name: 'Icon4ThofjulyGrey12' },
  { icon: Icons.Icon4ThofjulyGrey13, name: 'Icon4ThofjulyGrey13' },
  { icon: Icons.Icon4ThofjulyGrey14, name: 'Icon4ThofjulyGrey14' },
  { icon: Icons.Icon4ThofjulyGrey15, name: 'Icon4ThofjulyGrey15' },
  { icon: Icons.Icon4ThofjulyGrey16, name: 'Icon4ThofjulyGrey16' },
  { icon: Icons.Icon4ThofjulyGrey17, name: 'Icon4ThofjulyGrey17' },
  { icon: Icons.Icon4ThofjulyGrey18, name: 'Icon4ThofjulyGrey18' },
  { icon: Icons.Icon4ThofjulyGrey19, name: 'Icon4ThofjulyGrey19' },
  { icon: Icons.Icon4ThofjulyGrey2, name: 'Icon4ThofjulyGrey2' },
  { icon: Icons.Icon4ThofjulyGrey20, name: 'Icon4ThofjulyGrey20' },
  { icon: Icons.Icon4ThofjulyGrey21, name: 'Icon4ThofjulyGrey21' },
  { icon: Icons.Icon4ThofjulyGrey22, name: 'Icon4ThofjulyGrey22' },
  { icon: Icons.Icon4ThofjulyGrey23, name: 'Icon4ThofjulyGrey23' },
  { icon: Icons.Icon4ThofjulyGrey24, name: 'Icon4ThofjulyGrey24' },
  { icon: Icons.Icon4ThofjulyGrey25, name: 'Icon4ThofjulyGrey25' },
  { icon: Icons.Icon4ThofjulyGrey26, name: 'Icon4ThofjulyGrey26' },
  { icon: Icons.Icon4ThofjulyGrey27, name: 'Icon4ThofjulyGrey27' },
  { icon: Icons.Icon4ThofjulyGrey28, name: 'Icon4ThofjulyGrey28' },
  { icon: Icons.Icon4ThofjulyGrey29, name: 'Icon4ThofjulyGrey29' },
  { icon: Icons.Icon4ThofjulyGrey3, name: 'Icon4ThofjulyGrey3' },
  { icon: Icons.Icon4ThofjulyGrey30, name: 'Icon4ThofjulyGrey30' },
  { icon: Icons.Icon4ThofjulyGrey31, name: 'Icon4ThofjulyGrey31' },
  { icon: Icons.Icon4ThofjulyGrey32, name: 'Icon4ThofjulyGrey32' },
  { icon: Icons.Icon4ThofjulyGrey33, name: 'Icon4ThofjulyGrey33' },
  { icon: Icons.Icon4ThofjulyGrey34, name: 'Icon4ThofjulyGrey34' },
  { icon: Icons.Icon4ThofjulyGrey35, name: 'Icon4ThofjulyGrey35' },
  { icon: Icons.Icon4ThofjulyGrey36, name: 'Icon4ThofjulyGrey36' },
  { icon: Icons.Icon4ThofjulyGrey37, name: 'Icon4ThofjulyGrey37' },
  { icon: Icons.Icon4ThofjulyGrey38, name: 'Icon4ThofjulyGrey38' },
  { icon: Icons.Icon4ThofjulyGrey39, name: 'Icon4ThofjulyGrey39' },
  { icon: Icons.Icon4ThofjulyGrey4, name: 'Icon4ThofjulyGrey4' },
  { icon: Icons.Icon4ThofjulyGrey40, name: 'Icon4ThofjulyGrey40' },
  { icon: Icons.Icon4ThofjulyGrey5, name: 'Icon4ThofjulyGrey5' },
  { icon: Icons.Icon4ThofjulyGrey6, name: 'Icon4ThofjulyGrey6' },
  { icon: Icons.Icon4ThofjulyGrey7, name: 'Icon4ThofjulyGrey7' },
  { icon: Icons.Icon4ThofjulyGrey8, name: 'Icon4ThofjulyGrey8' },
  { icon: Icons.Icon4ThofjulyGrey9, name: 'Icon4ThofjulyGrey9' },
];