/**
 * Generated by scripts/generate-icons.js.
 * DO NOT EDIT!
 */

import * as Icons from '../../business-grey';

export const ICON_LIST = [
  { icon: Icons.IconBusinessGrey1, name: 'IconBusinessGrey1' },
  { icon: Icons.IconBusinessGrey10, name: 'IconBusinessGrey10' },
  { icon: Icons.IconBusinessGrey11, name: 'IconBusinessGrey11' },
  { icon: Icons.IconBusinessGrey12, name: 'IconBusinessGrey12' },
  { icon: Icons.IconBusinessGrey13, name: 'IconBusinessGrey13' },
  { icon: Icons.IconBusinessGrey14, name: 'IconBusinessGrey14' },
  { icon: Icons.IconBusinessGrey15, name: 'IconBusinessGrey15' },
  { icon: Icons.IconBusinessGrey16, name: 'IconBusinessGrey16' },
  { icon: Icons.IconBusinessGrey17, name: 'IconBusinessGrey17' },
  { icon: Icons.IconBusinessGrey18, name: 'IconBusinessGrey18' },
  { icon: Icons.IconBusinessGrey19, name: 'IconBusinessGrey19' },
  { icon: Icons.IconBusinessGrey2, name: 'IconBusinessGrey2' },
  { icon: Icons.IconBusinessGrey20, name: 'IconBusinessGrey20' },
  { icon: Icons.IconBusinessGrey3, name: 'IconBusinessGrey3' },
  { icon: Icons.IconBusinessGrey4, name: 'IconBusinessGrey4' },
  { icon: Icons.IconBusinessGrey5, name: 'IconBusinessGrey5' },
  { icon: Icons.IconBusinessGrey6, name: 'IconBusinessGrey6' },
  { icon: Icons.IconBusinessGrey7, name: 'IconBusinessGrey7' },
  { icon: Icons.IconBusinessGrey8, name: 'IconBusinessGrey8' },
  { icon: Icons.IconBusinessGrey9, name: 'IconBusinessGrey9' },
];