/**
 * Generated by scripts/generate-icons.js.
 * DO NOT EDIT!
 */

import * as Icons from '../../business-color';

export const ICON_LIST = [
  { icon: Icons.IconBusinessColor1, name: 'IconBusinessColor1' },
  { icon: Icons.IconBusinessColor10, name: 'IconBusinessColor10' },
  { icon: Icons.IconBusinessColor11, name: 'IconBusinessColor11' },
  { icon: Icons.IconBusinessColor12, name: 'IconBusinessColor12' },
  { icon: Icons.IconBusinessColor13, name: 'IconBusinessColor13' },
  { icon: Icons.IconBusinessColor14, name: 'IconBusinessColor14' },
  { icon: Icons.IconBusinessColor15, name: 'IconBusinessColor15' },
  { icon: Icons.IconBusinessColor16, name: 'IconBusinessColor16' },
  { icon: Icons.IconBusinessColor17, name: 'IconBusinessColor17' },
  { icon: Icons.IconBusinessColor18, name: 'IconBusinessColor18' },
  { icon: Icons.IconBusinessColor19, name: 'IconBusinessColor19' },
  { icon: Icons.IconBusinessColor2, name: 'IconBusinessColor2' },
  { icon: Icons.IconBusinessColor20, name: 'IconBusinessColor20' },
  { icon: Icons.IconBusinessColor21, name: 'IconBusinessColor21' },
  { icon: Icons.IconBusinessColor22, name: 'IconBusinessColor22' },
  { icon: Icons.IconBusinessColor23, name: 'IconBusinessColor23' },
  { icon: Icons.IconBusinessColor24, name: 'IconBusinessColor24' },
  { icon: Icons.IconBusinessColor25, name: 'IconBusinessColor25' },
  { icon: Icons.IconBusinessColor26, name: 'IconBusinessColor26' },
  { icon: Icons.IconBusinessColor27, name: 'IconBusinessColor27' },
  { icon: Icons.IconBusinessColor28, name: 'IconBusinessColor28' },
  { icon: Icons.IconBusinessColor29, name: 'IconBusinessColor29' },
  { icon: Icons.IconBusinessColor3, name: 'IconBusinessColor3' },
  { icon: Icons.IconBusinessColor30, name: 'IconBusinessColor30' },
  { icon: Icons.IconBusinessColor31, name: 'IconBusinessColor31' },
  { icon: Icons.IconBusinessColor32, name: 'IconBusinessColor32' },
  { icon: Icons.IconBusinessColor33, name: 'IconBusinessColor33' },
  { icon: Icons.IconBusinessColor34, name: 'IconBusinessColor34' },
  { icon: Icons.IconBusinessColor35, name: 'IconBusinessColor35' },
  { icon: Icons.IconBusinessColor36, name: 'IconBusinessColor36' },
  { icon: Icons.IconBusinessColor37, name: 'IconBusinessColor37' },
  { icon: Icons.IconBusinessColor38, name: 'IconBusinessColor38' },
  { icon: Icons.IconBusinessColor39, name: 'IconBusinessColor39' },
  { icon: Icons.IconBusinessColor4, name: 'IconBusinessColor4' },
  { icon: Icons.IconBusinessColor40, name: 'IconBusinessColor40' },
  { icon: Icons.IconBusinessColor5, name: 'IconBusinessColor5' },
  { icon: Icons.IconBusinessColor6, name: 'IconBusinessColor6' },
  { icon: Icons.IconBusinessColor7, name: 'IconBusinessColor7' },
  { icon: Icons.IconBusinessColor8, name: 'IconBusinessColor8' },
  { icon: Icons.IconBusinessColor9, name: 'IconBusinessColor9' },
];