/**
 * Generated by scripts/generate-icons.js.
 * DO NOT EDIT!
 */

import * as Icons from '../../food-dishes-color';

export const ICON_LIST = [
  { icon: Icons.IconFoodDishesColor1, name: 'IconFoodDishesColor1' },
  { icon: Icons.IconFoodDishesColor10, name: 'IconFoodDishesColor10' },
  { icon: Icons.IconFoodDishesColor11, name: 'IconFoodDishesColor11' },
  { icon: Icons.IconFoodDishesColor12, name: 'IconFoodDishesColor12' },
  { icon: Icons.IconFoodDishesColor13, name: 'IconFoodDishesColor13' },
  { icon: Icons.IconFoodDishesColor14, name: 'IconFoodDishesColor14' },
  { icon: Icons.IconFoodDishesColor15, name: 'IconFoodDishesColor15' },
  { icon: Icons.IconFoodDishesColor2, name: 'IconFoodDishesColor2' },
  { icon: Icons.IconFoodDishesColor3, name: 'IconFoodDishesColor3' },
  { icon: Icons.IconFoodDishesColor4, name: 'IconFoodDishesColor4' },
  { icon: Icons.IconFoodDishesColor5, name: 'IconFoodDishesColor5' },
  { icon: Icons.IconFoodDishesColor6, name: 'IconFoodDishesColor6' },
  { icon: Icons.IconFoodDishesColor7, name: 'IconFoodDishesColor7' },
  { icon: Icons.IconFoodDishesColor8, name: 'IconFoodDishesColor8' },
  { icon: Icons.IconFoodDishesColor9, name: 'IconFoodDishesColor9' },
];