/**
 * Generated by scripts/generate-icons.js.
 * DO NOT EDIT!
 */

import * as Icons from '../../green-energy-color';

export const ICON_LIST = [
  { icon: Icons.IconGreenEnergyColor1, name: 'IconGreenEnergyColor1' },
  { icon: Icons.IconGreenEnergyColor10, name: 'IconGreenEnergyColor10' },
  { icon: Icons.IconGreenEnergyColor11, name: 'IconGreenEnergyColor11' },
  { icon: Icons.IconGreenEnergyColor12, name: 'IconGreenEnergyColor12' },
  { icon: Icons.IconGreenEnergyColor13, name: 'IconGreenEnergyColor13' },
  { icon: Icons.IconGreenEnergyColor14, name: 'IconGreenEnergyColor14' },
  { icon: Icons.IconGreenEnergyColor15, name: 'IconGreenEnergyColor15' },
  { icon: Icons.IconGreenEnergyColor16, name: 'IconGreenEnergyColor16' },
  { icon: Icons.IconGreenEnergyColor17, name: 'IconGreenEnergyColor17' },
  { icon: Icons.IconGreenEnergyColor18, name: 'IconGreenEnergyColor18' },
  { icon: Icons.IconGreenEnergyColor19, name: 'IconGreenEnergyColor19' },
  { icon: Icons.IconGreenEnergyColor2, name: 'IconGreenEnergyColor2' },
  { icon: Icons.IconGreenEnergyColor20, name: 'IconGreenEnergyColor20' },
  { icon: Icons.IconGreenEnergyColor21, name: 'IconGreenEnergyColor21' },
  { icon: Icons.IconGreenEnergyColor22, name: 'IconGreenEnergyColor22' },
  { icon: Icons.IconGreenEnergyColor23, name: 'IconGreenEnergyColor23' },
  { icon: Icons.IconGreenEnergyColor24, name: 'IconGreenEnergyColor24' },
  { icon: Icons.IconGreenEnergyColor25, name: 'IconGreenEnergyColor25' },
  { icon: Icons.IconGreenEnergyColor26, name: 'IconGreenEnergyColor26' },
  { icon: Icons.IconGreenEnergyColor27, name: 'IconGreenEnergyColor27' },
  { icon: Icons.IconGreenEnergyColor28, name: 'IconGreenEnergyColor28' },
  { icon: Icons.IconGreenEnergyColor29, name: 'IconGreenEnergyColor29' },
  { icon: Icons.IconGreenEnergyColor3, name: 'IconGreenEnergyColor3' },
  { icon: Icons.IconGreenEnergyColor30, name: 'IconGreenEnergyColor30' },
  { icon: Icons.IconGreenEnergyColor31, name: 'IconGreenEnergyColor31' },
  { icon: Icons.IconGreenEnergyColor32, name: 'IconGreenEnergyColor32' },
  { icon: Icons.IconGreenEnergyColor4, name: 'IconGreenEnergyColor4' },
  { icon: Icons.IconGreenEnergyColor5, name: 'IconGreenEnergyColor5' },
  { icon: Icons.IconGreenEnergyColor6, name: 'IconGreenEnergyColor6' },
  { icon: Icons.IconGreenEnergyColor7, name: 'IconGreenEnergyColor7' },
  { icon: Icons.IconGreenEnergyColor8, name: 'IconGreenEnergyColor8' },
  { icon: Icons.IconGreenEnergyColor9, name: 'IconGreenEnergyColor9' },
];