/**
 * Generated by scripts/generate-icons.js.
 * DO NOT EDIT!
 */

import * as Icons from '../../helmet-grey';

export const ICON_LIST = [
  { icon: Icons.IconHelmetGrey1, name: 'IconHelmetGrey1' },
  { icon: Icons.IconHelmetGrey10, name: 'IconHelmetGrey10' },
  { icon: Icons.IconHelmetGrey11, name: 'IconHelmetGrey11' },
  { icon: Icons.IconHelmetGrey12, name: 'IconHelmetGrey12' },
  { icon: Icons.IconHelmetGrey13, name: 'IconHelmetGrey13' },
  { icon: Icons.IconHelmetGrey14, name: 'IconHelmetGrey14' },
  { icon: Icons.IconHelmetGrey15, name: 'IconHelmetGrey15' },
  { icon: Icons.IconHelmetGrey16, name: 'IconHelmetGrey16' },
  { icon: Icons.IconHelmetGrey17, name: 'IconHelmetGrey17' },
  { icon: Icons.IconHelmetGrey18, name: 'IconHelmetGrey18' },
  { icon: Icons.IconHelmetGrey19, name: 'IconHelmetGrey19' },
  { icon: Icons.IconHelmetGrey2, name: 'IconHelmetGrey2' },
  { icon: Icons.IconHelmetGrey20, name: 'IconHelmetGrey20' },
  { icon: Icons.IconHelmetGrey21, name: 'IconHelmetGrey21' },
  { icon: Icons.IconHelmetGrey22, name: 'IconHelmetGrey22' },
  { icon: Icons.IconHelmetGrey23, name: 'IconHelmetGrey23' },
  { icon: Icons.IconHelmetGrey24, name: 'IconHelmetGrey24' },
  { icon: Icons.IconHelmetGrey25, name: 'IconHelmetGrey25' },
  { icon: Icons.IconHelmetGrey26, name: 'IconHelmetGrey26' },
  { icon: Icons.IconHelmetGrey27, name: 'IconHelmetGrey27' },
  { icon: Icons.IconHelmetGrey28, name: 'IconHelmetGrey28' },
  { icon: Icons.IconHelmetGrey29, name: 'IconHelmetGrey29' },
  { icon: Icons.IconHelmetGrey3, name: 'IconHelmetGrey3' },
  { icon: Icons.IconHelmetGrey30, name: 'IconHelmetGrey30' },
  { icon: Icons.IconHelmetGrey31, name: 'IconHelmetGrey31' },
  { icon: Icons.IconHelmetGrey32, name: 'IconHelmetGrey32' },
  { icon: Icons.IconHelmetGrey4, name: 'IconHelmetGrey4' },
  { icon: Icons.IconHelmetGrey5, name: 'IconHelmetGrey5' },
  { icon: Icons.IconHelmetGrey6, name: 'IconHelmetGrey6' },
  { icon: Icons.IconHelmetGrey7, name: 'IconHelmetGrey7' },
  { icon: Icons.IconHelmetGrey8, name: 'IconHelmetGrey8' },
  { icon: Icons.IconHelmetGrey9, name: 'IconHelmetGrey9' },
];