/**
 * Generated by scripts/generate-icons.js.
 * DO NOT EDIT!
 */

import * as Icons from '../../home-grey';

export const ICON_LIST = [
  { icon: Icons.IconHomeGrey1, name: 'IconHomeGrey1' },
  { icon: Icons.IconHomeGrey10, name: 'IconHomeGrey10' },
  { icon: Icons.IconHomeGrey11, name: 'IconHomeGrey11' },
  { icon: Icons.IconHomeGrey12, name: 'IconHomeGrey12' },
  { icon: Icons.IconHomeGrey13, name: 'IconHomeGrey13' },
  { icon: Icons.IconHomeGrey14, name: 'IconHomeGrey14' },
  { icon: Icons.IconHomeGrey15, name: 'IconHomeGrey15' },
  { icon: Icons.IconHomeGrey16, name: 'IconHomeGrey16' },
  { icon: Icons.IconHomeGrey2, name: 'IconHomeGrey2' },
  { icon: Icons.IconHomeGrey3, name: 'IconHomeGrey3' },
  { icon: Icons.IconHomeGrey4, name: 'IconHomeGrey4' },
  { icon: Icons.IconHomeGrey5, name: 'IconHomeGrey5' },
  { icon: Icons.IconHomeGrey6, name: 'IconHomeGrey6' },
  { icon: Icons.IconHomeGrey7, name: 'IconHomeGrey7' },
  { icon: Icons.IconHomeGrey8, name: 'IconHomeGrey8' },
  { icon: Icons.IconHomeGrey9, name: 'IconHomeGrey9' },
];