/**
 * Generated by scripts/generate-icons.js.
 * DO NOT EDIT!
 */

import * as Icons from '../../home-color';

export const ICON_LIST = [
  { icon: Icons.IconHomeColor1, name: 'IconHomeColor1' },
  { icon: Icons.IconHomeColor10, name: 'IconHomeColor10' },
  { icon: Icons.IconHomeColor11, name: 'IconHomeColor11' },
  { icon: Icons.IconHomeColor12, name: 'IconHomeColor12' },
  { icon: Icons.IconHomeColor13, name: 'IconHomeColor13' },
  { icon: Icons.IconHomeColor14, name: 'IconHomeColor14' },
  { icon: Icons.IconHomeColor15, name: 'IconHomeColor15' },
  { icon: Icons.IconHomeColor16, name: 'IconHomeColor16' },
  { icon: Icons.IconHomeColor2, name: 'IconHomeColor2' },
  { icon: Icons.IconHomeColor3, name: 'IconHomeColor3' },
  { icon: Icons.IconHomeColor4, name: 'IconHomeColor4' },
  { icon: Icons.IconHomeColor5, name: 'IconHomeColor5' },
  { icon: Icons.IconHomeColor6, name: 'IconHomeColor6' },
  { icon: Icons.IconHomeColor7, name: 'IconHomeColor7' },
  { icon: Icons.IconHomeColor8, name: 'IconHomeColor8' },
  { icon: Icons.IconHomeColor9, name: 'IconHomeColor9' },
];