/**
 * Generated by scripts/generate-icons.js.
 * DO NOT EDIT!
 */

import * as Icons from '../../kitchen-color';

export const ICON_LIST = [
  { icon: Icons.IconKitchenColor1, name: 'IconKitchenColor1' },
  { icon: Icons.IconKitchenColor10, name: 'IconKitchenColor10' },
  { icon: Icons.IconKitchenColor11, name: 'IconKitchenColor11' },
  { icon: Icons.IconKitchenColor12, name: 'IconKitchenColor12' },
  { icon: Icons.IconKitchenColor13, name: 'IconKitchenColor13' },
  { icon: Icons.IconKitchenColor14, name: 'IconKitchenColor14' },
  { icon: Icons.IconKitchenColor15, name: 'IconKitchenColor15' },
  { icon: Icons.IconKitchenColor16, name: 'IconKitchenColor16' },
  { icon: Icons.IconKitchenColor2, name: 'IconKitchenColor2' },
  { icon: Icons.IconKitchenColor3, name: 'IconKitchenColor3' },
  { icon: Icons.IconKitchenColor4, name: 'IconKitchenColor4' },
  { icon: Icons.IconKitchenColor5, name: 'IconKitchenColor5' },
  { icon: Icons.IconKitchenColor6, name: 'IconKitchenColor6' },
  { icon: Icons.IconKitchenColor7, name: 'IconKitchenColor7' },
  { icon: Icons.IconKitchenColor8, name: 'IconKitchenColor8' },
  { icon: Icons.IconKitchenColor9, name: 'IconKitchenColor9' },
];