/**
 * Generated by scripts/generate-icons.js.
 * DO NOT EDIT!
 */

import * as Icons from '../../kitchen-grey';

export const ICON_LIST = [
  { icon: Icons.IconKitchenGrey1, name: 'IconKitchenGrey1' },
  { icon: Icons.IconKitchenGrey10, name: 'IconKitchenGrey10' },
  { icon: Icons.IconKitchenGrey11, name: 'IconKitchenGrey11' },
  { icon: Icons.IconKitchenGrey12, name: 'IconKitchenGrey12' },
  { icon: Icons.IconKitchenGrey13, name: 'IconKitchenGrey13' },
  { icon: Icons.IconKitchenGrey14, name: 'IconKitchenGrey14' },
  { icon: Icons.IconKitchenGrey15, name: 'IconKitchenGrey15' },
  { icon: Icons.IconKitchenGrey16, name: 'IconKitchenGrey16' },
  { icon: Icons.IconKitchenGrey2, name: 'IconKitchenGrey2' },
  { icon: Icons.IconKitchenGrey3, name: 'IconKitchenGrey3' },
  { icon: Icons.IconKitchenGrey4, name: 'IconKitchenGrey4' },
  { icon: Icons.IconKitchenGrey5, name: 'IconKitchenGrey5' },
  { icon: Icons.IconKitchenGrey6, name: 'IconKitchenGrey6' },
  { icon: Icons.IconKitchenGrey7, name: 'IconKitchenGrey7' },
  { icon: Icons.IconKitchenGrey8, name: 'IconKitchenGrey8' },
  { icon: Icons.IconKitchenGrey9, name: 'IconKitchenGrey9' },
];