/**
 * Generated by scripts/generate-icons.js.
 * DO NOT EDIT!
 */

import * as Icons from '../../knife-color';

export const ICON_LIST = [
  { icon: Icons.IconKnifeColor1, name: 'IconKnifeColor1' },
  { icon: Icons.IconKnifeColor10, name: 'IconKnifeColor10' },
  { icon: Icons.IconKnifeColor11, name: 'IconKnifeColor11' },
  { icon: Icons.IconKnifeColor12, name: 'IconKnifeColor12' },
  { icon: Icons.IconKnifeColor13, name: 'IconKnifeColor13' },
  { icon: Icons.IconKnifeColor14, name: 'IconKnifeColor14' },
  { icon: Icons.IconKnifeColor15, name: 'IconKnifeColor15' },
  { icon: Icons.IconKnifeColor16, name: 'IconKnifeColor16' },
  { icon: Icons.IconKnifeColor2, name: 'IconKnifeColor2' },
  { icon: Icons.IconKnifeColor3, name: 'IconKnifeColor3' },
  { icon: Icons.IconKnifeColor4, name: 'IconKnifeColor4' },
  { icon: Icons.IconKnifeColor5, name: 'IconKnifeColor5' },
  { icon: Icons.IconKnifeColor6, name: 'IconKnifeColor6' },
  { icon: Icons.IconKnifeColor7, name: 'IconKnifeColor7' },
  { icon: Icons.IconKnifeColor8, name: 'IconKnifeColor8' },
  { icon: Icons.IconKnifeColor9, name: 'IconKnifeColor9' },
];