/**
 * Generated by scripts/generate-icons.js.
 * DO NOT EDIT!
 */

import * as Icons from '../../knife-grey';

export const ICON_LIST = [
  { icon: Icons.IconKnifeGrey1, name: 'IconKnifeGrey1' },
  { icon: Icons.IconKnifeGrey10, name: 'IconKnifeGrey10' },
  { icon: Icons.IconKnifeGrey11, name: 'IconKnifeGrey11' },
  { icon: Icons.IconKnifeGrey12, name: 'IconKnifeGrey12' },
  { icon: Icons.IconKnifeGrey13, name: 'IconKnifeGrey13' },
  { icon: Icons.IconKnifeGrey14, name: 'IconKnifeGrey14' },
  { icon: Icons.IconKnifeGrey15, name: 'IconKnifeGrey15' },
  { icon: Icons.IconKnifeGrey16, name: 'IconKnifeGrey16' },
  { icon: Icons.IconKnifeGrey2, name: 'IconKnifeGrey2' },
  { icon: Icons.IconKnifeGrey3, name: 'IconKnifeGrey3' },
  { icon: Icons.IconKnifeGrey4, name: 'IconKnifeGrey4' },
  { icon: Icons.IconKnifeGrey5, name: 'IconKnifeGrey5' },
  { icon: Icons.IconKnifeGrey6, name: 'IconKnifeGrey6' },
  { icon: Icons.IconKnifeGrey7, name: 'IconKnifeGrey7' },
  { icon: Icons.IconKnifeGrey8, name: 'IconKnifeGrey8' },
  { icon: Icons.IconKnifeGrey9, name: 'IconKnifeGrey9' },
];