/**
 * Generated by scripts/generate-icons.js.
 * DO NOT EDIT!
 */

import * as Icons from '../../law-grey';

export const ICON_LIST = [
  { icon: Icons.IconLawGrey1, name: 'IconLawGrey1' },
  { icon: Icons.IconLawGrey10, name: 'IconLawGrey10' },
  { icon: Icons.IconLawGrey11, name: 'IconLawGrey11' },
  { icon: Icons.IconLawGrey12, name: 'IconLawGrey12' },
  { icon: Icons.IconLawGrey13, name: 'IconLawGrey13' },
  { icon: Icons.IconLawGrey14, name: 'IconLawGrey14' },
  { icon: Icons.IconLawGrey15, name: 'IconLawGrey15' },
  { icon: Icons.IconLawGrey16, name: 'IconLawGrey16' },
  { icon: Icons.IconLawGrey2, name: 'IconLawGrey2' },
  { icon: Icons.IconLawGrey3, name: 'IconLawGrey3' },
  { icon: Icons.IconLawGrey4, name: 'IconLawGrey4' },
  { icon: Icons.IconLawGrey5, name: 'IconLawGrey5' },
  { icon: Icons.IconLawGrey6, name: 'IconLawGrey6' },
  { icon: Icons.IconLawGrey7, name: 'IconLawGrey7' },
  { icon: Icons.IconLawGrey8, name: 'IconLawGrey8' },
  { icon: Icons.IconLawGrey9, name: 'IconLawGrey9' },
];