/**
 * Generated by scripts/generate-icons.js.
 * DO NOT EDIT!
 */

import * as Icons from '../../law-color';

export const ICON_LIST = [
  { icon: Icons.IconLawColor1, name: 'IconLawColor1' },
  { icon: Icons.IconLawColor10, name: 'IconLawColor10' },
  { icon: Icons.IconLawColor11, name: 'IconLawColor11' },
  { icon: Icons.IconLawColor12, name: 'IconLawColor12' },
  { icon: Icons.IconLawColor13, name: 'IconLawColor13' },
  { icon: Icons.IconLawColor14, name: 'IconLawColor14' },
  { icon: Icons.IconLawColor15, name: 'IconLawColor15' },
  { icon: Icons.IconLawColor16, name: 'IconLawColor16' },
  { icon: Icons.IconLawColor2, name: 'IconLawColor2' },
  { icon: Icons.IconLawColor3, name: 'IconLawColor3' },
  { icon: Icons.IconLawColor4, name: 'IconLawColor4' },
  { icon: Icons.IconLawColor5, name: 'IconLawColor5' },
  { icon: Icons.IconLawColor6, name: 'IconLawColor6' },
  { icon: Icons.IconLawColor7, name: 'IconLawColor7' },
  { icon: Icons.IconLawColor8, name: 'IconLawColor8' },
  { icon: Icons.IconLawColor9, name: 'IconLawColor9' },
];