/**
 * Generated by scripts/generate-icons.js.
 * DO NOT EDIT!
 */

import * as Icons from '../../leaf-color';

export const ICON_LIST = [
  { icon: Icons.IconLeafColor1, name: 'IconLeafColor1' },
  { icon: Icons.IconLeafColor10, name: 'IconLeafColor10' },
  { icon: Icons.IconLeafColor11, name: 'IconLeafColor11' },
  { icon: Icons.IconLeafColor12, name: 'IconLeafColor12' },
  { icon: Icons.IconLeafColor13, name: 'IconLeafColor13' },
  { icon: Icons.IconLeafColor14, name: 'IconLeafColor14' },
  { icon: Icons.IconLeafColor15, name: 'IconLeafColor15' },
  { icon: Icons.IconLeafColor16, name: 'IconLeafColor16' },
  { icon: Icons.IconLeafColor2, name: 'IconLeafColor2' },
  { icon: Icons.IconLeafColor3, name: 'IconLeafColor3' },
  { icon: Icons.IconLeafColor4, name: 'IconLeafColor4' },
  { icon: Icons.IconLeafColor5, name: 'IconLeafColor5' },
  { icon: Icons.IconLeafColor6, name: 'IconLeafColor6' },
  { icon: Icons.IconLeafColor7, name: 'IconLeafColor7' },
  { icon: Icons.IconLeafColor8, name: 'IconLeafColor8' },
  { icon: Icons.IconLeafColor9, name: 'IconLeafColor9' },
];