/**
 * Generated by scripts/generate-icons.js.
 * DO NOT EDIT!
 */

import * as Icons from '../../leaf-grey';

export const ICON_LIST = [
  { icon: Icons.IconLeafGrey1, name: 'IconLeafGrey1' },
  { icon: Icons.IconLeafGrey10, name: 'IconLeafGrey10' },
  { icon: Icons.IconLeafGrey11, name: 'IconLeafGrey11' },
  { icon: Icons.IconLeafGrey12, name: 'IconLeafGrey12' },
  { icon: Icons.IconLeafGrey13, name: 'IconLeafGrey13' },
  { icon: Icons.IconLeafGrey14, name: 'IconLeafGrey14' },
  { icon: Icons.IconLeafGrey15, name: 'IconLeafGrey15' },
  { icon: Icons.IconLeafGrey16, name: 'IconLeafGrey16' },
  { icon: Icons.IconLeafGrey2, name: 'IconLeafGrey2' },
  { icon: Icons.IconLeafGrey3, name: 'IconLeafGrey3' },
  { icon: Icons.IconLeafGrey4, name: 'IconLeafGrey4' },
  { icon: Icons.IconLeafGrey5, name: 'IconLeafGrey5' },
  { icon: Icons.IconLeafGrey6, name: 'IconLeafGrey6' },
  { icon: Icons.IconLeafGrey7, name: 'IconLeafGrey7' },
  { icon: Icons.IconLeafGrey8, name: 'IconLeafGrey8' },
  { icon: Icons.IconLeafGrey9, name: 'IconLeafGrey9' },
];