/**
 * Generated by scripts/generate-icons.js.
 * DO NOT EDIT!
 */

import * as Icons from '../../logistics-color';

export const ICON_LIST = [
  { icon: Icons.IconLogisticsColor1, name: 'IconLogisticsColor1' },
  { icon: Icons.IconLogisticsColor10, name: 'IconLogisticsColor10' },
  { icon: Icons.IconLogisticsColor11, name: 'IconLogisticsColor11' },
  { icon: Icons.IconLogisticsColor12, name: 'IconLogisticsColor12' },
  { icon: Icons.IconLogisticsColor13, name: 'IconLogisticsColor13' },
  { icon: Icons.IconLogisticsColor14, name: 'IconLogisticsColor14' },
  { icon: Icons.IconLogisticsColor15, name: 'IconLogisticsColor15' },
  { icon: Icons.IconLogisticsColor16, name: 'IconLogisticsColor16' },
  { icon: Icons.IconLogisticsColor17, name: 'IconLogisticsColor17' },
  { icon: Icons.IconLogisticsColor18, name: 'IconLogisticsColor18' },
  { icon: Icons.IconLogisticsColor19, name: 'IconLogisticsColor19' },
  { icon: Icons.IconLogisticsColor2, name: 'IconLogisticsColor2' },
  { icon: Icons.IconLogisticsColor20, name: 'IconLogisticsColor20' },
  { icon: Icons.IconLogisticsColor21, name: 'IconLogisticsColor21' },
  { icon: Icons.IconLogisticsColor22, name: 'IconLogisticsColor22' },
  { icon: Icons.IconLogisticsColor23, name: 'IconLogisticsColor23' },
  { icon: Icons.IconLogisticsColor24, name: 'IconLogisticsColor24' },
  { icon: Icons.IconLogisticsColor25, name: 'IconLogisticsColor25' },
  { icon: Icons.IconLogisticsColor26, name: 'IconLogisticsColor26' },
  { icon: Icons.IconLogisticsColor27, name: 'IconLogisticsColor27' },
  { icon: Icons.IconLogisticsColor28, name: 'IconLogisticsColor28' },
  { icon: Icons.IconLogisticsColor29, name: 'IconLogisticsColor29' },
  { icon: Icons.IconLogisticsColor3, name: 'IconLogisticsColor3' },
  { icon: Icons.IconLogisticsColor30, name: 'IconLogisticsColor30' },
  { icon: Icons.IconLogisticsColor31, name: 'IconLogisticsColor31' },
  { icon: Icons.IconLogisticsColor32, name: 'IconLogisticsColor32' },
  { icon: Icons.IconLogisticsColor33, name: 'IconLogisticsColor33' },
  { icon: Icons.IconLogisticsColor34, name: 'IconLogisticsColor34' },
  { icon: Icons.IconLogisticsColor35, name: 'IconLogisticsColor35' },
  { icon: Icons.IconLogisticsColor36, name: 'IconLogisticsColor36' },
  { icon: Icons.IconLogisticsColor37, name: 'IconLogisticsColor37' },
  { icon: Icons.IconLogisticsColor38, name: 'IconLogisticsColor38' },
  { icon: Icons.IconLogisticsColor39, name: 'IconLogisticsColor39' },
  { icon: Icons.IconLogisticsColor4, name: 'IconLogisticsColor4' },
  { icon: Icons.IconLogisticsColor40, name: 'IconLogisticsColor40' },
  { icon: Icons.IconLogisticsColor5, name: 'IconLogisticsColor5' },
  { icon: Icons.IconLogisticsColor6, name: 'IconLogisticsColor6' },
  { icon: Icons.IconLogisticsColor7, name: 'IconLogisticsColor7' },
  { icon: Icons.IconLogisticsColor8, name: 'IconLogisticsColor8' },
  { icon: Icons.IconLogisticsColor9, name: 'IconLogisticsColor9' },
];