/**
 * Generated by scripts/generate-icons.js.
 * DO NOT EDIT!
 */

import * as Icons from '../../logistics-grey';

export const ICON_LIST = [
  { icon: Icons.IconLogisticsGrey1, name: 'IconLogisticsGrey1' },
  { icon: Icons.IconLogisticsGrey10, name: 'IconLogisticsGrey10' },
  { icon: Icons.IconLogisticsGrey11, name: 'IconLogisticsGrey11' },
  { icon: Icons.IconLogisticsGrey12, name: 'IconLogisticsGrey12' },
  { icon: Icons.IconLogisticsGrey13, name: 'IconLogisticsGrey13' },
  { icon: Icons.IconLogisticsGrey14, name: 'IconLogisticsGrey14' },
  { icon: Icons.IconLogisticsGrey15, name: 'IconLogisticsGrey15' },
  { icon: Icons.IconLogisticsGrey16, name: 'IconLogisticsGrey16' },
  { icon: Icons.IconLogisticsGrey17, name: 'IconLogisticsGrey17' },
  { icon: Icons.IconLogisticsGrey18, name: 'IconLogisticsGrey18' },
  { icon: Icons.IconLogisticsGrey19, name: 'IconLogisticsGrey19' },
  { icon: Icons.IconLogisticsGrey2, name: 'IconLogisticsGrey2' },
  { icon: Icons.IconLogisticsGrey20, name: 'IconLogisticsGrey20' },
  { icon: Icons.IconLogisticsGrey3, name: 'IconLogisticsGrey3' },
  { icon: Icons.IconLogisticsGrey4, name: 'IconLogisticsGrey4' },
  { icon: Icons.IconLogisticsGrey5, name: 'IconLogisticsGrey5' },
  { icon: Icons.IconLogisticsGrey6, name: 'IconLogisticsGrey6' },
  { icon: Icons.IconLogisticsGrey7, name: 'IconLogisticsGrey7' },
  { icon: Icons.IconLogisticsGrey8, name: 'IconLogisticsGrey8' },
  { icon: Icons.IconLogisticsGrey9, name: 'IconLogisticsGrey9' },
];