/**
 * Generated by scripts/generate-icons.js.
 * DO NOT EDIT!
 */

import * as Icons from '../../lumberjack-color';

export const ICON_LIST = [
  { icon: Icons.IconLumberjackColor1, name: 'IconLumberjackColor1' },
  { icon: Icons.IconLumberjackColor10, name: 'IconLumberjackColor10' },
  { icon: Icons.IconLumberjackColor11, name: 'IconLumberjackColor11' },
  { icon: Icons.IconLumberjackColor12, name: 'IconLumberjackColor12' },
  { icon: Icons.IconLumberjackColor13, name: 'IconLumberjackColor13' },
  { icon: Icons.IconLumberjackColor14, name: 'IconLumberjackColor14' },
  { icon: Icons.IconLumberjackColor15, name: 'IconLumberjackColor15' },
  { icon: Icons.IconLumberjackColor16, name: 'IconLumberjackColor16' },
  { icon: Icons.IconLumberjackColor2, name: 'IconLumberjackColor2' },
  { icon: Icons.IconLumberjackColor3, name: 'IconLumberjackColor3' },
  { icon: Icons.IconLumberjackColor4, name: 'IconLumberjackColor4' },
  { icon: Icons.IconLumberjackColor5, name: 'IconLumberjackColor5' },
  { icon: Icons.IconLumberjackColor6, name: 'IconLumberjackColor6' },
  { icon: Icons.IconLumberjackColor7, name: 'IconLumberjackColor7' },
  { icon: Icons.IconLumberjackColor8, name: 'IconLumberjackColor8' },
  { icon: Icons.IconLumberjackColor9, name: 'IconLumberjackColor9' },
];