/**
 * Generated by scripts/generate-icons.js.
 * DO NOT EDIT!
 */

import * as Icons from '../../lumberjack-grey';

export const ICON_LIST = [
  { icon: Icons.IconLumberjackGrey1, name: 'IconLumberjackGrey1' },
  { icon: Icons.IconLumberjackGrey10, name: 'IconLumberjackGrey10' },
  { icon: Icons.IconLumberjackGrey11, name: 'IconLumberjackGrey11' },
  { icon: Icons.IconLumberjackGrey12, name: 'IconLumberjackGrey12' },
  { icon: Icons.IconLumberjackGrey13, name: 'IconLumberjackGrey13' },
  { icon: Icons.IconLumberjackGrey14, name: 'IconLumberjackGrey14' },
  { icon: Icons.IconLumberjackGrey15, name: 'IconLumberjackGrey15' },
  { icon: Icons.IconLumberjackGrey16, name: 'IconLumberjackGrey16' },
  { icon: Icons.IconLumberjackGrey2, name: 'IconLumberjackGrey2' },
  { icon: Icons.IconLumberjackGrey3, name: 'IconLumberjackGrey3' },
  { icon: Icons.IconLumberjackGrey4, name: 'IconLumberjackGrey4' },
  { icon: Icons.IconLumberjackGrey5, name: 'IconLumberjackGrey5' },
  { icon: Icons.IconLumberjackGrey6, name: 'IconLumberjackGrey6' },
  { icon: Icons.IconLumberjackGrey7, name: 'IconLumberjackGrey7' },
  { icon: Icons.IconLumberjackGrey8, name: 'IconLumberjackGrey8' },
  { icon: Icons.IconLumberjackGrey9, name: 'IconLumberjackGrey9' },
];