/**
 * Generated by scripts/generate-icons.js.
 * DO NOT EDIT!
 */

import * as Icons from '../../medical-grey';

export const ICON_LIST = [
  { icon: Icons.IconMedicalGrey1, name: 'IconMedicalGrey1' },
  { icon: Icons.IconMedicalGrey10, name: 'IconMedicalGrey10' },
  { icon: Icons.IconMedicalGrey11, name: 'IconMedicalGrey11' },
  { icon: Icons.IconMedicalGrey12, name: 'IconMedicalGrey12' },
  { icon: Icons.IconMedicalGrey13, name: 'IconMedicalGrey13' },
  { icon: Icons.IconMedicalGrey14, name: 'IconMedicalGrey14' },
  { icon: Icons.IconMedicalGrey15, name: 'IconMedicalGrey15' },
  { icon: Icons.IconMedicalGrey16, name: 'IconMedicalGrey16' },
  { icon: Icons.IconMedicalGrey17, name: 'IconMedicalGrey17' },
  { icon: Icons.IconMedicalGrey18, name: 'IconMedicalGrey18' },
  { icon: Icons.IconMedicalGrey19, name: 'IconMedicalGrey19' },
  { icon: Icons.IconMedicalGrey2, name: 'IconMedicalGrey2' },
  { icon: Icons.IconMedicalGrey20, name: 'IconMedicalGrey20' },
  { icon: Icons.IconMedicalGrey21, name: 'IconMedicalGrey21' },
  { icon: Icons.IconMedicalGrey22, name: 'IconMedicalGrey22' },
  { icon: Icons.IconMedicalGrey23, name: 'IconMedicalGrey23' },
  { icon: Icons.IconMedicalGrey24, name: 'IconMedicalGrey24' },
  { icon: Icons.IconMedicalGrey25, name: 'IconMedicalGrey25' },
  { icon: Icons.IconMedicalGrey26, name: 'IconMedicalGrey26' },
  { icon: Icons.IconMedicalGrey27, name: 'IconMedicalGrey27' },
  { icon: Icons.IconMedicalGrey28, name: 'IconMedicalGrey28' },
  { icon: Icons.IconMedicalGrey29, name: 'IconMedicalGrey29' },
  { icon: Icons.IconMedicalGrey3, name: 'IconMedicalGrey3' },
  { icon: Icons.IconMedicalGrey30, name: 'IconMedicalGrey30' },
  { icon: Icons.IconMedicalGrey31, name: 'IconMedicalGrey31' },
  { icon: Icons.IconMedicalGrey32, name: 'IconMedicalGrey32' },
  { icon: Icons.IconMedicalGrey33, name: 'IconMedicalGrey33' },
  { icon: Icons.IconMedicalGrey34, name: 'IconMedicalGrey34' },
  { icon: Icons.IconMedicalGrey35, name: 'IconMedicalGrey35' },
  { icon: Icons.IconMedicalGrey4, name: 'IconMedicalGrey4' },
  { icon: Icons.IconMedicalGrey5, name: 'IconMedicalGrey5' },
  { icon: Icons.IconMedicalGrey6, name: 'IconMedicalGrey6' },
  { icon: Icons.IconMedicalGrey7, name: 'IconMedicalGrey7' },
  { icon: Icons.IconMedicalGrey8, name: 'IconMedicalGrey8' },
  { icon: Icons.IconMedicalGrey9, name: 'IconMedicalGrey9' },
];