/**
 * Generated by scripts/generate-icons.js.
 * DO NOT EDIT!
 */

import * as Icons from '../../mobile-ui-grey';

export const ICON_LIST = [
  { icon: Icons.IconMobileUiGrey1, name: 'IconMobileUiGrey1' },
  { icon: Icons.IconMobileUiGrey10, name: 'IconMobileUiGrey10' },
  { icon: Icons.IconMobileUiGrey11, name: 'IconMobileUiGrey11' },
  { icon: Icons.IconMobileUiGrey12, name: 'IconMobileUiGrey12' },
  { icon: Icons.IconMobileUiGrey13, name: 'IconMobileUiGrey13' },
  { icon: Icons.IconMobileUiGrey14, name: 'IconMobileUiGrey14' },
  { icon: Icons.IconMobileUiGrey15, name: 'IconMobileUiGrey15' },
  { icon: Icons.IconMobileUiGrey16, name: 'IconMobileUiGrey16' },
  { icon: Icons.IconMobileUiGrey17, name: 'IconMobileUiGrey17' },
  { icon: Icons.IconMobileUiGrey18, name: 'IconMobileUiGrey18' },
  { icon: Icons.IconMobileUiGrey19, name: 'IconMobileUiGrey19' },
  { icon: Icons.IconMobileUiGrey2, name: 'IconMobileUiGrey2' },
  { icon: Icons.IconMobileUiGrey20, name: 'IconMobileUiGrey20' },
  { icon: Icons.IconMobileUiGrey21, name: 'IconMobileUiGrey21' },
  { icon: Icons.IconMobileUiGrey22, name: 'IconMobileUiGrey22' },
  { icon: Icons.IconMobileUiGrey23, name: 'IconMobileUiGrey23' },
  { icon: Icons.IconMobileUiGrey24, name: 'IconMobileUiGrey24' },
  { icon: Icons.IconMobileUiGrey25, name: 'IconMobileUiGrey25' },
  { icon: Icons.IconMobileUiGrey26, name: 'IconMobileUiGrey26' },
  { icon: Icons.IconMobileUiGrey27, name: 'IconMobileUiGrey27' },
  { icon: Icons.IconMobileUiGrey28, name: 'IconMobileUiGrey28' },
  { icon: Icons.IconMobileUiGrey29, name: 'IconMobileUiGrey29' },
  { icon: Icons.IconMobileUiGrey3, name: 'IconMobileUiGrey3' },
  { icon: Icons.IconMobileUiGrey30, name: 'IconMobileUiGrey30' },
  { icon: Icons.IconMobileUiGrey31, name: 'IconMobileUiGrey31' },
  { icon: Icons.IconMobileUiGrey32, name: 'IconMobileUiGrey32' },
  { icon: Icons.IconMobileUiGrey4, name: 'IconMobileUiGrey4' },
  { icon: Icons.IconMobileUiGrey5, name: 'IconMobileUiGrey5' },
  { icon: Icons.IconMobileUiGrey6, name: 'IconMobileUiGrey6' },
  { icon: Icons.IconMobileUiGrey7, name: 'IconMobileUiGrey7' },
  { icon: Icons.IconMobileUiGrey8, name: 'IconMobileUiGrey8' },
  { icon: Icons.IconMobileUiGrey9, name: 'IconMobileUiGrey9' },
];