/**
 * Generated by scripts/generate-icons.js.
 * DO NOT EDIT!
 */

import * as Icons from '../../music-color';

export const ICON_LIST = [
  { icon: Icons.IconMusicColor1, name: 'IconMusicColor1' },
  { icon: Icons.IconMusicColor10, name: 'IconMusicColor10' },
  { icon: Icons.IconMusicColor11, name: 'IconMusicColor11' },
  { icon: Icons.IconMusicColor12, name: 'IconMusicColor12' },
  { icon: Icons.IconMusicColor13, name: 'IconMusicColor13' },
  { icon: Icons.IconMusicColor14, name: 'IconMusicColor14' },
  { icon: Icons.IconMusicColor15, name: 'IconMusicColor15' },
  { icon: Icons.IconMusicColor16, name: 'IconMusicColor16' },
  { icon: Icons.IconMusicColor2, name: 'IconMusicColor2' },
  { icon: Icons.IconMusicColor3, name: 'IconMusicColor3' },
  { icon: Icons.IconMusicColor4, name: 'IconMusicColor4' },
  { icon: Icons.IconMusicColor5, name: 'IconMusicColor5' },
  { icon: Icons.IconMusicColor6, name: 'IconMusicColor6' },
  { icon: Icons.IconMusicColor7, name: 'IconMusicColor7' },
  { icon: Icons.IconMusicColor8, name: 'IconMusicColor8' },
  { icon: Icons.IconMusicColor9, name: 'IconMusicColor9' },
];