/**
 * Generated by scripts/generate-icons.js.
 * DO NOT EDIT!
 */

import * as Icons from '../../music-grey';

export const ICON_LIST = [
  { icon: Icons.IconMusicGrey1, name: 'IconMusicGrey1' },
  { icon: Icons.IconMusicGrey10, name: 'IconMusicGrey10' },
  { icon: Icons.IconMusicGrey11, name: 'IconMusicGrey11' },
  { icon: Icons.IconMusicGrey12, name: 'IconMusicGrey12' },
  { icon: Icons.IconMusicGrey13, name: 'IconMusicGrey13' },
  { icon: Icons.IconMusicGrey14, name: 'IconMusicGrey14' },
  { icon: Icons.IconMusicGrey15, name: 'IconMusicGrey15' },
  { icon: Icons.IconMusicGrey16, name: 'IconMusicGrey16' },
  { icon: Icons.IconMusicGrey2, name: 'IconMusicGrey2' },
  { icon: Icons.IconMusicGrey3, name: 'IconMusicGrey3' },
  { icon: Icons.IconMusicGrey4, name: 'IconMusicGrey4' },
  { icon: Icons.IconMusicGrey5, name: 'IconMusicGrey5' },
  { icon: Icons.IconMusicGrey6, name: 'IconMusicGrey6' },
  { icon: Icons.IconMusicGrey7, name: 'IconMusicGrey7' },
  { icon: Icons.IconMusicGrey8, name: 'IconMusicGrey8' },
  { icon: Icons.IconMusicGrey9, name: 'IconMusicGrey9' },
];