/**
 * Generated by scripts/generate-icons.js.
 * DO NOT EDIT!
 */

import * as Icons from '../../office-grey';

export const ICON_LIST = [
  { icon: Icons.IconOfficeGrey1, name: 'IconOfficeGrey1' },
  { icon: Icons.IconOfficeGrey10, name: 'IconOfficeGrey10' },
  { icon: Icons.IconOfficeGrey11, name: 'IconOfficeGrey11' },
  { icon: Icons.IconOfficeGrey12, name: 'IconOfficeGrey12' },
  { icon: Icons.IconOfficeGrey13, name: 'IconOfficeGrey13' },
  { icon: Icons.IconOfficeGrey14, name: 'IconOfficeGrey14' },
  { icon: Icons.IconOfficeGrey15, name: 'IconOfficeGrey15' },
  { icon: Icons.IconOfficeGrey16, name: 'IconOfficeGrey16' },
  { icon: Icons.IconOfficeGrey17, name: 'IconOfficeGrey17' },
  { icon: Icons.IconOfficeGrey18, name: 'IconOfficeGrey18' },
  { icon: Icons.IconOfficeGrey19, name: 'IconOfficeGrey19' },
  { icon: Icons.IconOfficeGrey2, name: 'IconOfficeGrey2' },
  { icon: Icons.IconOfficeGrey20, name: 'IconOfficeGrey20' },
  { icon: Icons.IconOfficeGrey3, name: 'IconOfficeGrey3' },
  { icon: Icons.IconOfficeGrey4, name: 'IconOfficeGrey4' },
  { icon: Icons.IconOfficeGrey5, name: 'IconOfficeGrey5' },
  { icon: Icons.IconOfficeGrey6, name: 'IconOfficeGrey6' },
  { icon: Icons.IconOfficeGrey7, name: 'IconOfficeGrey7' },
  { icon: Icons.IconOfficeGrey8, name: 'IconOfficeGrey8' },
  { icon: Icons.IconOfficeGrey9, name: 'IconOfficeGrey9' },
];