/**
 * Generated by scripts/generate-icons.js.
 * DO NOT EDIT!
 */

import * as Icons from '../../office-color';

export const ICON_LIST = [
  { icon: Icons.IconOfficeColor1, name: 'IconOfficeColor1' },
  { icon: Icons.IconOfficeColor10, name: 'IconOfficeColor10' },
  { icon: Icons.IconOfficeColor11, name: 'IconOfficeColor11' },
  { icon: Icons.IconOfficeColor12, name: 'IconOfficeColor12' },
  { icon: Icons.IconOfficeColor13, name: 'IconOfficeColor13' },
  { icon: Icons.IconOfficeColor14, name: 'IconOfficeColor14' },
  { icon: Icons.IconOfficeColor15, name: 'IconOfficeColor15' },
  { icon: Icons.IconOfficeColor16, name: 'IconOfficeColor16' },
  { icon: Icons.IconOfficeColor17, name: 'IconOfficeColor17' },
  { icon: Icons.IconOfficeColor18, name: 'IconOfficeColor18' },
  { icon: Icons.IconOfficeColor19, name: 'IconOfficeColor19' },
  { icon: Icons.IconOfficeColor2, name: 'IconOfficeColor2' },
  { icon: Icons.IconOfficeColor20, name: 'IconOfficeColor20' },
  { icon: Icons.IconOfficeColor21, name: 'IconOfficeColor21' },
  { icon: Icons.IconOfficeColor22, name: 'IconOfficeColor22' },
  { icon: Icons.IconOfficeColor23, name: 'IconOfficeColor23' },
  { icon: Icons.IconOfficeColor24, name: 'IconOfficeColor24' },
  { icon: Icons.IconOfficeColor25, name: 'IconOfficeColor25' },
  { icon: Icons.IconOfficeColor26, name: 'IconOfficeColor26' },
  { icon: Icons.IconOfficeColor27, name: 'IconOfficeColor27' },
  { icon: Icons.IconOfficeColor28, name: 'IconOfficeColor28' },
  { icon: Icons.IconOfficeColor29, name: 'IconOfficeColor29' },
  { icon: Icons.IconOfficeColor3, name: 'IconOfficeColor3' },
  { icon: Icons.IconOfficeColor30, name: 'IconOfficeColor30' },
  { icon: Icons.IconOfficeColor31, name: 'IconOfficeColor31' },
  { icon: Icons.IconOfficeColor32, name: 'IconOfficeColor32' },
  { icon: Icons.IconOfficeColor33, name: 'IconOfficeColor33' },
  { icon: Icons.IconOfficeColor34, name: 'IconOfficeColor34' },
  { icon: Icons.IconOfficeColor35, name: 'IconOfficeColor35' },
  { icon: Icons.IconOfficeColor36, name: 'IconOfficeColor36' },
  { icon: Icons.IconOfficeColor37, name: 'IconOfficeColor37' },
  { icon: Icons.IconOfficeColor38, name: 'IconOfficeColor38' },
  { icon: Icons.IconOfficeColor39, name: 'IconOfficeColor39' },
  { icon: Icons.IconOfficeColor4, name: 'IconOfficeColor4' },
  { icon: Icons.IconOfficeColor40, name: 'IconOfficeColor40' },
  { icon: Icons.IconOfficeColor5, name: 'IconOfficeColor5' },
  { icon: Icons.IconOfficeColor6, name: 'IconOfficeColor6' },
  { icon: Icons.IconOfficeColor7, name: 'IconOfficeColor7' },
  { icon: Icons.IconOfficeColor8, name: 'IconOfficeColor8' },
  { icon: Icons.IconOfficeColor9, name: 'IconOfficeColor9' },
];