/**
 * Generated by scripts/generate-icons.js.
 * DO NOT EDIT!
 */

import * as Icons from '../../security-color';

export const ICON_LIST = [
  { icon: Icons.IconSecurityColor1, name: 'IconSecurityColor1' },
  { icon: Icons.IconSecurityColor10, name: 'IconSecurityColor10' },
  { icon: Icons.IconSecurityColor11, name: 'IconSecurityColor11' },
  { icon: Icons.IconSecurityColor12, name: 'IconSecurityColor12' },
  { icon: Icons.IconSecurityColor13, name: 'IconSecurityColor13' },
  { icon: Icons.IconSecurityColor14, name: 'IconSecurityColor14' },
  { icon: Icons.IconSecurityColor15, name: 'IconSecurityColor15' },
  { icon: Icons.IconSecurityColor16, name: 'IconSecurityColor16' },
  { icon: Icons.IconSecurityColor2, name: 'IconSecurityColor2' },
  { icon: Icons.IconSecurityColor3, name: 'IconSecurityColor3' },
  { icon: Icons.IconSecurityColor4, name: 'IconSecurityColor4' },
  { icon: Icons.IconSecurityColor5, name: 'IconSecurityColor5' },
  { icon: Icons.IconSecurityColor6, name: 'IconSecurityColor6' },
  { icon: Icons.IconSecurityColor7, name: 'IconSecurityColor7' },
  { icon: Icons.IconSecurityColor8, name: 'IconSecurityColor8' },
  { icon: Icons.IconSecurityColor9, name: 'IconSecurityColor9' },
];