/**
 * Generated by scripts/generate-icons.js.
 * DO NOT EDIT!
 */

import * as Icons from '../../security-grey';

export const ICON_LIST = [
  { icon: Icons.IconSecurityGrey1, name: 'IconSecurityGrey1' },
  { icon: Icons.IconSecurityGrey10, name: 'IconSecurityGrey10' },
  { icon: Icons.IconSecurityGrey11, name: 'IconSecurityGrey11' },
  { icon: Icons.IconSecurityGrey12, name: 'IconSecurityGrey12' },
  { icon: Icons.IconSecurityGrey13, name: 'IconSecurityGrey13' },
  { icon: Icons.IconSecurityGrey14, name: 'IconSecurityGrey14' },
  { icon: Icons.IconSecurityGrey15, name: 'IconSecurityGrey15' },
  { icon: Icons.IconSecurityGrey16, name: 'IconSecurityGrey16' },
  { icon: Icons.IconSecurityGrey2, name: 'IconSecurityGrey2' },
  { icon: Icons.IconSecurityGrey3, name: 'IconSecurityGrey3' },
  { icon: Icons.IconSecurityGrey4, name: 'IconSecurityGrey4' },
  { icon: Icons.IconSecurityGrey5, name: 'IconSecurityGrey5' },
  { icon: Icons.IconSecurityGrey6, name: 'IconSecurityGrey6' },
  { icon: Icons.IconSecurityGrey7, name: 'IconSecurityGrey7' },
  { icon: Icons.IconSecurityGrey8, name: 'IconSecurityGrey8' },
  { icon: Icons.IconSecurityGrey9, name: 'IconSecurityGrey9' },
];