/**
 * Generated by scripts/generate-icons.js.
 * DO NOT EDIT!
 */

import * as Icons from '../../shopping-color';

export const ICON_LIST = [
  { icon: Icons.IconShoppingColor1, name: 'IconShoppingColor1' },
  { icon: Icons.IconShoppingColor10, name: 'IconShoppingColor10' },
  { icon: Icons.IconShoppingColor11, name: 'IconShoppingColor11' },
  { icon: Icons.IconShoppingColor12, name: 'IconShoppingColor12' },
  { icon: Icons.IconShoppingColor13, name: 'IconShoppingColor13' },
  { icon: Icons.IconShoppingColor14, name: 'IconShoppingColor14' },
  { icon: Icons.IconShoppingColor15, name: 'IconShoppingColor15' },
  { icon: Icons.IconShoppingColor16, name: 'IconShoppingColor16' },
  { icon: Icons.IconShoppingColor2, name: 'IconShoppingColor2' },
  { icon: Icons.IconShoppingColor3, name: 'IconShoppingColor3' },
  { icon: Icons.IconShoppingColor4, name: 'IconShoppingColor4' },
  { icon: Icons.IconShoppingColor5, name: 'IconShoppingColor5' },
  { icon: Icons.IconShoppingColor6, name: 'IconShoppingColor6' },
  { icon: Icons.IconShoppingColor7, name: 'IconShoppingColor7' },
  { icon: Icons.IconShoppingColor8, name: 'IconShoppingColor8' },
  { icon: Icons.IconShoppingColor9, name: 'IconShoppingColor9' },
];