/**
 * Generated by scripts/generate-icons.js.
 * DO NOT EDIT!
 */

import * as Icons from '../../shopping-grey';

export const ICON_LIST = [
  { icon: Icons.IconShoppingGrey1, name: 'IconShoppingGrey1' },
  { icon: Icons.IconShoppingGrey10, name: 'IconShoppingGrey10' },
  { icon: Icons.IconShoppingGrey11, name: 'IconShoppingGrey11' },
  { icon: Icons.IconShoppingGrey12, name: 'IconShoppingGrey12' },
  { icon: Icons.IconShoppingGrey13, name: 'IconShoppingGrey13' },
  { icon: Icons.IconShoppingGrey14, name: 'IconShoppingGrey14' },
  { icon: Icons.IconShoppingGrey15, name: 'IconShoppingGrey15' },
  { icon: Icons.IconShoppingGrey16, name: 'IconShoppingGrey16' },
  { icon: Icons.IconShoppingGrey2, name: 'IconShoppingGrey2' },
  { icon: Icons.IconShoppingGrey3, name: 'IconShoppingGrey3' },
  { icon: Icons.IconShoppingGrey4, name: 'IconShoppingGrey4' },
  { icon: Icons.IconShoppingGrey5, name: 'IconShoppingGrey5' },
  { icon: Icons.IconShoppingGrey6, name: 'IconShoppingGrey6' },
  { icon: Icons.IconShoppingGrey7, name: 'IconShoppingGrey7' },
  { icon: Icons.IconShoppingGrey8, name: 'IconShoppingGrey8' },
  { icon: Icons.IconShoppingGrey9, name: 'IconShoppingGrey9' },
];