/**
 * Generated by scripts/generate-icons.js.
 * DO NOT EDIT!
 */

import * as Icons from '../../skull-color';

export const ICON_LIST = [
  { icon: Icons.IconSkullColor1, name: 'IconSkullColor1' },
  { icon: Icons.IconSkullColor10, name: 'IconSkullColor10' },
  { icon: Icons.IconSkullColor11, name: 'IconSkullColor11' },
  { icon: Icons.IconSkullColor12, name: 'IconSkullColor12' },
  { icon: Icons.IconSkullColor13, name: 'IconSkullColor13' },
  { icon: Icons.IconSkullColor14, name: 'IconSkullColor14' },
  { icon: Icons.IconSkullColor15, name: 'IconSkullColor15' },
  { icon: Icons.IconSkullColor16, name: 'IconSkullColor16' },
  { icon: Icons.IconSkullColor2, name: 'IconSkullColor2' },
  { icon: Icons.IconSkullColor3, name: 'IconSkullColor3' },
  { icon: Icons.IconSkullColor4, name: 'IconSkullColor4' },
  { icon: Icons.IconSkullColor5, name: 'IconSkullColor5' },
  { icon: Icons.IconSkullColor6, name: 'IconSkullColor6' },
  { icon: Icons.IconSkullColor7, name: 'IconSkullColor7' },
  { icon: Icons.IconSkullColor8, name: 'IconSkullColor8' },
  { icon: Icons.IconSkullColor9, name: 'IconSkullColor9' },
];