/**
 * Generated by scripts/generate-icons.js.
 * DO NOT EDIT!
 */

import * as Icons from '../../skull-grey';

export const ICON_LIST = [
  { icon: Icons.IconSkullGrey1, name: 'IconSkullGrey1' },
  { icon: Icons.IconSkullGrey10, name: 'IconSkullGrey10' },
  { icon: Icons.IconSkullGrey11, name: 'IconSkullGrey11' },
  { icon: Icons.IconSkullGrey12, name: 'IconSkullGrey12' },
  { icon: Icons.IconSkullGrey13, name: 'IconSkullGrey13' },
  { icon: Icons.IconSkullGrey14, name: 'IconSkullGrey14' },
  { icon: Icons.IconSkullGrey15, name: 'IconSkullGrey15' },
  { icon: Icons.IconSkullGrey16, name: 'IconSkullGrey16' },
  { icon: Icons.IconSkullGrey2, name: 'IconSkullGrey2' },
  { icon: Icons.IconSkullGrey3, name: 'IconSkullGrey3' },
  { icon: Icons.IconSkullGrey4, name: 'IconSkullGrey4' },
  { icon: Icons.IconSkullGrey5, name: 'IconSkullGrey5' },
  { icon: Icons.IconSkullGrey6, name: 'IconSkullGrey6' },
  { icon: Icons.IconSkullGrey7, name: 'IconSkullGrey7' },
  { icon: Icons.IconSkullGrey8, name: 'IconSkullGrey8' },
  { icon: Icons.IconSkullGrey9, name: 'IconSkullGrey9' },
];