/**
 * Generated by scripts/generate-icons.js.
 * DO NOT EDIT!
 */

import * as Icons from '../../space-color';

export const ICON_LIST = [
  { icon: Icons.IconSpaceColor1, name: 'IconSpaceColor1' },
  { icon: Icons.IconSpaceColor10, name: 'IconSpaceColor10' },
  { icon: Icons.IconSpaceColor11, name: 'IconSpaceColor11' },
  { icon: Icons.IconSpaceColor12, name: 'IconSpaceColor12' },
  { icon: Icons.IconSpaceColor13, name: 'IconSpaceColor13' },
  { icon: Icons.IconSpaceColor14, name: 'IconSpaceColor14' },
  { icon: Icons.IconSpaceColor15, name: 'IconSpaceColor15' },
  { icon: Icons.IconSpaceColor16, name: 'IconSpaceColor16' },
  { icon: Icons.IconSpaceColor2, name: 'IconSpaceColor2' },
  { icon: Icons.IconSpaceColor3, name: 'IconSpaceColor3' },
  { icon: Icons.IconSpaceColor4, name: 'IconSpaceColor4' },
  { icon: Icons.IconSpaceColor5, name: 'IconSpaceColor5' },
  { icon: Icons.IconSpaceColor6, name: 'IconSpaceColor6' },
  { icon: Icons.IconSpaceColor7, name: 'IconSpaceColor7' },
  { icon: Icons.IconSpaceColor8, name: 'IconSpaceColor8' },
  { icon: Icons.IconSpaceColor9, name: 'IconSpaceColor9' },
];