/**
 * Generated by scripts/generate-icons.js.
 * DO NOT EDIT!
 */

import * as Icons from '../../space-grey';

export const ICON_LIST = [
  { icon: Icons.IconSpaceGrey1, name: 'IconSpaceGrey1' },
  { icon: Icons.IconSpaceGrey10, name: 'IconSpaceGrey10' },
  { icon: Icons.IconSpaceGrey11, name: 'IconSpaceGrey11' },
  { icon: Icons.IconSpaceGrey12, name: 'IconSpaceGrey12' },
  { icon: Icons.IconSpaceGrey13, name: 'IconSpaceGrey13' },
  { icon: Icons.IconSpaceGrey14, name: 'IconSpaceGrey14' },
  { icon: Icons.IconSpaceGrey15, name: 'IconSpaceGrey15' },
  { icon: Icons.IconSpaceGrey16, name: 'IconSpaceGrey16' },
  { icon: Icons.IconSpaceGrey2, name: 'IconSpaceGrey2' },
  { icon: Icons.IconSpaceGrey3, name: 'IconSpaceGrey3' },
  { icon: Icons.IconSpaceGrey4, name: 'IconSpaceGrey4' },
  { icon: Icons.IconSpaceGrey5, name: 'IconSpaceGrey5' },
  { icon: Icons.IconSpaceGrey6, name: 'IconSpaceGrey6' },
  { icon: Icons.IconSpaceGrey7, name: 'IconSpaceGrey7' },
  { icon: Icons.IconSpaceGrey8, name: 'IconSpaceGrey8' },
  { icon: Icons.IconSpaceGrey9, name: 'IconSpaceGrey9' },
];