/**
 * Generated by scripts/generate-icons.js.
 * DO NOT EDIT!
 */

import * as Icons from '../../spring-grey';

export const ICON_LIST = [
  { icon: Icons.IconSpringGrey1, name: 'IconSpringGrey1' },
  { icon: Icons.IconSpringGrey10, name: 'IconSpringGrey10' },
  { icon: Icons.IconSpringGrey11, name: 'IconSpringGrey11' },
  { icon: Icons.IconSpringGrey12, name: 'IconSpringGrey12' },
  { icon: Icons.IconSpringGrey13, name: 'IconSpringGrey13' },
  { icon: Icons.IconSpringGrey14, name: 'IconSpringGrey14' },
  { icon: Icons.IconSpringGrey15, name: 'IconSpringGrey15' },
  { icon: Icons.IconSpringGrey16, name: 'IconSpringGrey16' },
  { icon: Icons.IconSpringGrey2, name: 'IconSpringGrey2' },
  { icon: Icons.IconSpringGrey3, name: 'IconSpringGrey3' },
  { icon: Icons.IconSpringGrey4, name: 'IconSpringGrey4' },
  { icon: Icons.IconSpringGrey5, name: 'IconSpringGrey5' },
  { icon: Icons.IconSpringGrey6, name: 'IconSpringGrey6' },
  { icon: Icons.IconSpringGrey7, name: 'IconSpringGrey7' },
  { icon: Icons.IconSpringGrey8, name: 'IconSpringGrey8' },
  { icon: Icons.IconSpringGrey9, name: 'IconSpringGrey9' },
];