/**
 * Generated by scripts/generate-icons.js.
 * DO NOT EDIT!
 */

import * as Icons from '../../spring-color';

export const ICON_LIST = [
  { icon: Icons.IconSpringColor1, name: 'IconSpringColor1' },
  { icon: Icons.IconSpringColor10, name: 'IconSpringColor10' },
  { icon: Icons.IconSpringColor11, name: 'IconSpringColor11' },
  { icon: Icons.IconSpringColor12, name: 'IconSpringColor12' },
  { icon: Icons.IconSpringColor13, name: 'IconSpringColor13' },
  { icon: Icons.IconSpringColor14, name: 'IconSpringColor14' },
  { icon: Icons.IconSpringColor15, name: 'IconSpringColor15' },
  { icon: Icons.IconSpringColor16, name: 'IconSpringColor16' },
  { icon: Icons.IconSpringColor2, name: 'IconSpringColor2' },
  { icon: Icons.IconSpringColor3, name: 'IconSpringColor3' },
  { icon: Icons.IconSpringColor4, name: 'IconSpringColor4' },
  { icon: Icons.IconSpringColor5, name: 'IconSpringColor5' },
  { icon: Icons.IconSpringColor6, name: 'IconSpringColor6' },
  { icon: Icons.IconSpringColor7, name: 'IconSpringColor7' },
  { icon: Icons.IconSpringColor8, name: 'IconSpringColor8' },
  { icon: Icons.IconSpringColor9, name: 'IconSpringColor9' },
];