/**
 * Generated by scripts/generate-icons.js.
 * DO NOT EDIT!
 */

import * as Icons from '../../sweet-17-grey';

export const ICON_LIST = [
  { icon: Icons.IconSweet17Grey1, name: 'IconSweet17Grey1' },
  { icon: Icons.IconSweet17Grey10, name: 'IconSweet17Grey10' },
  { icon: Icons.IconSweet17Grey11, name: 'IconSweet17Grey11' },
  { icon: Icons.IconSweet17Grey12, name: 'IconSweet17Grey12' },
  { icon: Icons.IconSweet17Grey13, name: 'IconSweet17Grey13' },
  { icon: Icons.IconSweet17Grey14, name: 'IconSweet17Grey14' },
  { icon: Icons.IconSweet17Grey15, name: 'IconSweet17Grey15' },
  { icon: Icons.IconSweet17Grey16, name: 'IconSweet17Grey16' },
  { icon: Icons.IconSweet17Grey17, name: 'IconSweet17Grey17' },
  { icon: Icons.IconSweet17Grey18, name: 'IconSweet17Grey18' },
  { icon: Icons.IconSweet17Grey19, name: 'IconSweet17Grey19' },
  { icon: Icons.IconSweet17Grey2, name: 'IconSweet17Grey2' },
  { icon: Icons.IconSweet17Grey20, name: 'IconSweet17Grey20' },
  { icon: Icons.IconSweet17Grey21, name: 'IconSweet17Grey21' },
  { icon: Icons.IconSweet17Grey22, name: 'IconSweet17Grey22' },
  { icon: Icons.IconSweet17Grey23, name: 'IconSweet17Grey23' },
  { icon: Icons.IconSweet17Grey24, name: 'IconSweet17Grey24' },
  { icon: Icons.IconSweet17Grey25, name: 'IconSweet17Grey25' },
  { icon: Icons.IconSweet17Grey3, name: 'IconSweet17Grey3' },
  { icon: Icons.IconSweet17Grey4, name: 'IconSweet17Grey4' },
  { icon: Icons.IconSweet17Grey5, name: 'IconSweet17Grey5' },
  { icon: Icons.IconSweet17Grey6, name: 'IconSweet17Grey6' },
  { icon: Icons.IconSweet17Grey7, name: 'IconSweet17Grey7' },
  { icon: Icons.IconSweet17Grey8, name: 'IconSweet17Grey8' },
  { icon: Icons.IconSweet17Grey9, name: 'IconSweet17Grey9' },
];