/**
 * Generated by scripts/generate-icons.js.
 * DO NOT EDIT!
 */

import * as Icons from '../../sweet-17-color';

export const ICON_LIST = [
  { icon: Icons.IconSweet17Color1, name: 'IconSweet17Color1' },
  { icon: Icons.IconSweet17Color10, name: 'IconSweet17Color10' },
  { icon: Icons.IconSweet17Color11, name: 'IconSweet17Color11' },
  { icon: Icons.IconSweet17Color12, name: 'IconSweet17Color12' },
  { icon: Icons.IconSweet17Color13, name: 'IconSweet17Color13' },
  { icon: Icons.IconSweet17Color14, name: 'IconSweet17Color14' },
  { icon: Icons.IconSweet17Color15, name: 'IconSweet17Color15' },
  { icon: Icons.IconSweet17Color16, name: 'IconSweet17Color16' },
  { icon: Icons.IconSweet17Color17, name: 'IconSweet17Color17' },
  { icon: Icons.IconSweet17Color18, name: 'IconSweet17Color18' },
  { icon: Icons.IconSweet17Color19, name: 'IconSweet17Color19' },
  { icon: Icons.IconSweet17Color2, name: 'IconSweet17Color2' },
  { icon: Icons.IconSweet17Color20, name: 'IconSweet17Color20' },
  { icon: Icons.IconSweet17Color21, name: 'IconSweet17Color21' },
  { icon: Icons.IconSweet17Color22, name: 'IconSweet17Color22' },
  { icon: Icons.IconSweet17Color23, name: 'IconSweet17Color23' },
  { icon: Icons.IconSweet17Color24, name: 'IconSweet17Color24' },
  { icon: Icons.IconSweet17Color25, name: 'IconSweet17Color25' },
  { icon: Icons.IconSweet17Color3, name: 'IconSweet17Color3' },
  { icon: Icons.IconSweet17Color4, name: 'IconSweet17Color4' },
  { icon: Icons.IconSweet17Color5, name: 'IconSweet17Color5' },
  { icon: Icons.IconSweet17Color6, name: 'IconSweet17Color6' },
  { icon: Icons.IconSweet17Color7, name: 'IconSweet17Color7' },
  { icon: Icons.IconSweet17Color8, name: 'IconSweet17Color8' },
  { icon: Icons.IconSweet17Color9, name: 'IconSweet17Color9' },
];