/**
 * Generated by scripts/generate-icons.js.
 * DO NOT EDIT!
 */

import * as Icons from '../../time-color';

export const ICON_LIST = [
  { icon: Icons.IconTimeColor1, name: 'IconTimeColor1' },
  { icon: Icons.IconTimeColor10, name: 'IconTimeColor10' },
  { icon: Icons.IconTimeColor11, name: 'IconTimeColor11' },
  { icon: Icons.IconTimeColor12, name: 'IconTimeColor12' },
  { icon: Icons.IconTimeColor13, name: 'IconTimeColor13' },
  { icon: Icons.IconTimeColor14, name: 'IconTimeColor14' },
  { icon: Icons.IconTimeColor15, name: 'IconTimeColor15' },
  { icon: Icons.IconTimeColor16, name: 'IconTimeColor16' },
  { icon: Icons.IconTimeColor2, name: 'IconTimeColor2' },
  { icon: Icons.IconTimeColor3, name: 'IconTimeColor3' },
  { icon: Icons.IconTimeColor4, name: 'IconTimeColor4' },
  { icon: Icons.IconTimeColor5, name: 'IconTimeColor5' },
  { icon: Icons.IconTimeColor6, name: 'IconTimeColor6' },
  { icon: Icons.IconTimeColor7, name: 'IconTimeColor7' },
  { icon: Icons.IconTimeColor8, name: 'IconTimeColor8' },
  { icon: Icons.IconTimeColor9, name: 'IconTimeColor9' },
];