/**
 * Generated by scripts/generate-icons.js.
 * DO NOT EDIT!
 */

import * as Icons from '../../time-grey';

export const ICON_LIST = [
  { icon: Icons.IconTimeGrey1, name: 'IconTimeGrey1' },
  { icon: Icons.IconTimeGrey10, name: 'IconTimeGrey10' },
  { icon: Icons.IconTimeGrey11, name: 'IconTimeGrey11' },
  { icon: Icons.IconTimeGrey12, name: 'IconTimeGrey12' },
  { icon: Icons.IconTimeGrey13, name: 'IconTimeGrey13' },
  { icon: Icons.IconTimeGrey14, name: 'IconTimeGrey14' },
  { icon: Icons.IconTimeGrey15, name: 'IconTimeGrey15' },
  { icon: Icons.IconTimeGrey16, name: 'IconTimeGrey16' },
  { icon: Icons.IconTimeGrey2, name: 'IconTimeGrey2' },
  { icon: Icons.IconTimeGrey3, name: 'IconTimeGrey3' },
  { icon: Icons.IconTimeGrey4, name: 'IconTimeGrey4' },
  { icon: Icons.IconTimeGrey5, name: 'IconTimeGrey5' },
  { icon: Icons.IconTimeGrey6, name: 'IconTimeGrey6' },
  { icon: Icons.IconTimeGrey7, name: 'IconTimeGrey7' },
  { icon: Icons.IconTimeGrey8, name: 'IconTimeGrey8' },
  { icon: Icons.IconTimeGrey9, name: 'IconTimeGrey9' },
];