/**
 * Generated by scripts/generate-icons.js.
 * DO NOT EDIT!
 */

import * as Icons from '../../travel-grey';

export const ICON_LIST = [
  { icon: Icons.IconTravelGrey1, name: 'IconTravelGrey1' },
  { icon: Icons.IconTravelGrey10, name: 'IconTravelGrey10' },
  { icon: Icons.IconTravelGrey11, name: 'IconTravelGrey11' },
  { icon: Icons.IconTravelGrey12, name: 'IconTravelGrey12' },
  { icon: Icons.IconTravelGrey13, name: 'IconTravelGrey13' },
  { icon: Icons.IconTravelGrey14, name: 'IconTravelGrey14' },
  { icon: Icons.IconTravelGrey15, name: 'IconTravelGrey15' },
  { icon: Icons.IconTravelGrey16, name: 'IconTravelGrey16' },
  { icon: Icons.IconTravelGrey2, name: 'IconTravelGrey2' },
  { icon: Icons.IconTravelGrey3, name: 'IconTravelGrey3' },
  { icon: Icons.IconTravelGrey4, name: 'IconTravelGrey4' },
  { icon: Icons.IconTravelGrey5, name: 'IconTravelGrey5' },
  { icon: Icons.IconTravelGrey6, name: 'IconTravelGrey6' },
  { icon: Icons.IconTravelGrey7, name: 'IconTravelGrey7' },
  { icon: Icons.IconTravelGrey8, name: 'IconTravelGrey8' },
  { icon: Icons.IconTravelGrey9, name: 'IconTravelGrey9' },
];