/**
 * Generated by scripts/generate-icons.js.
 * DO NOT EDIT!
 */

import * as Icons from '../../travel-color';

export const ICON_LIST = [
  { icon: Icons.IconTravelColor1, name: 'IconTravelColor1' },
  { icon: Icons.IconTravelColor10, name: 'IconTravelColor10' },
  { icon: Icons.IconTravelColor11, name: 'IconTravelColor11' },
  { icon: Icons.IconTravelColor12, name: 'IconTravelColor12' },
  { icon: Icons.IconTravelColor13, name: 'IconTravelColor13' },
  { icon: Icons.IconTravelColor14, name: 'IconTravelColor14' },
  { icon: Icons.IconTravelColor15, name: 'IconTravelColor15' },
  { icon: Icons.IconTravelColor16, name: 'IconTravelColor16' },
  { icon: Icons.IconTravelColor2, name: 'IconTravelColor2' },
  { icon: Icons.IconTravelColor3, name: 'IconTravelColor3' },
  { icon: Icons.IconTravelColor4, name: 'IconTravelColor4' },
  { icon: Icons.IconTravelColor5, name: 'IconTravelColor5' },
  { icon: Icons.IconTravelColor6, name: 'IconTravelColor6' },
  { icon: Icons.IconTravelColor7, name: 'IconTravelColor7' },
  { icon: Icons.IconTravelColor8, name: 'IconTravelColor8' },
  { icon: Icons.IconTravelColor9, name: 'IconTravelColor9' },
];