/**
 * Generated by scripts/generate-icons.js.
 * DO NOT EDIT!
 */

import * as Icons from '../../valentine-color';

export const ICON_LIST = [
  { icon: Icons.IconValentineColor1, name: 'IconValentineColor1' },
  { icon: Icons.IconValentineColor10, name: 'IconValentineColor10' },
  { icon: Icons.IconValentineColor11, name: 'IconValentineColor11' },
  { icon: Icons.IconValentineColor12, name: 'IconValentineColor12' },
  { icon: Icons.IconValentineColor13, name: 'IconValentineColor13' },
  { icon: Icons.IconValentineColor14, name: 'IconValentineColor14' },
  { icon: Icons.IconValentineColor15, name: 'IconValentineColor15' },
  { icon: Icons.IconValentineColor16, name: 'IconValentineColor16' },
  { icon: Icons.IconValentineColor17, name: 'IconValentineColor17' },
  { icon: Icons.IconValentineColor18, name: 'IconValentineColor18' },
  { icon: Icons.IconValentineColor19, name: 'IconValentineColor19' },
  { icon: Icons.IconValentineColor2, name: 'IconValentineColor2' },
  { icon: Icons.IconValentineColor20, name: 'IconValentineColor20' },
  { icon: Icons.IconValentineColor21, name: 'IconValentineColor21' },
  { icon: Icons.IconValentineColor22, name: 'IconValentineColor22' },
  { icon: Icons.IconValentineColor23, name: 'IconValentineColor23' },
  { icon: Icons.IconValentineColor24, name: 'IconValentineColor24' },
  { icon: Icons.IconValentineColor25, name: 'IconValentineColor25' },
  { icon: Icons.IconValentineColor3, name: 'IconValentineColor3' },
  { icon: Icons.IconValentineColor4, name: 'IconValentineColor4' },
  { icon: Icons.IconValentineColor5, name: 'IconValentineColor5' },
  { icon: Icons.IconValentineColor6, name: 'IconValentineColor6' },
  { icon: Icons.IconValentineColor7, name: 'IconValentineColor7' },
  { icon: Icons.IconValentineColor8, name: 'IconValentineColor8' },
  { icon: Icons.IconValentineColor9, name: 'IconValentineColor9' },
];