/**
 * Generated by scripts/generate-icons.js.
 * DO NOT EDIT!
 */

import * as Icons from '../../valentine-grey';

export const ICON_LIST = [
  { icon: Icons.IconValentineGrey1, name: 'IconValentineGrey1' },
  { icon: Icons.IconValentineGrey10, name: 'IconValentineGrey10' },
  { icon: Icons.IconValentineGrey11, name: 'IconValentineGrey11' },
  { icon: Icons.IconValentineGrey12, name: 'IconValentineGrey12' },
  { icon: Icons.IconValentineGrey13, name: 'IconValentineGrey13' },
  { icon: Icons.IconValentineGrey14, name: 'IconValentineGrey14' },
  { icon: Icons.IconValentineGrey15, name: 'IconValentineGrey15' },
  { icon: Icons.IconValentineGrey16, name: 'IconValentineGrey16' },
  { icon: Icons.IconValentineGrey17, name: 'IconValentineGrey17' },
  { icon: Icons.IconValentineGrey18, name: 'IconValentineGrey18' },
  { icon: Icons.IconValentineGrey19, name: 'IconValentineGrey19' },
  { icon: Icons.IconValentineGrey2, name: 'IconValentineGrey2' },
  { icon: Icons.IconValentineGrey20, name: 'IconValentineGrey20' },
  { icon: Icons.IconValentineGrey21, name: 'IconValentineGrey21' },
  { icon: Icons.IconValentineGrey22, name: 'IconValentineGrey22' },
  { icon: Icons.IconValentineGrey23, name: 'IconValentineGrey23' },
  { icon: Icons.IconValentineGrey24, name: 'IconValentineGrey24' },
  { icon: Icons.IconValentineGrey25, name: 'IconValentineGrey25' },
  { icon: Icons.IconValentineGrey3, name: 'IconValentineGrey3' },
  { icon: Icons.IconValentineGrey4, name: 'IconValentineGrey4' },
  { icon: Icons.IconValentineGrey5, name: 'IconValentineGrey5' },
  { icon: Icons.IconValentineGrey6, name: 'IconValentineGrey6' },
  { icon: Icons.IconValentineGrey7, name: 'IconValentineGrey7' },
  { icon: Icons.IconValentineGrey8, name: 'IconValentineGrey8' },
  { icon: Icons.IconValentineGrey9, name: 'IconValentineGrey9' },
];