/**
 * Generated by scripts/generate-icons.js.
 * DO NOT EDIT!
 */

import * as Icons from '../../virtual-reality-grey';

export const ICON_LIST = [
  { icon: Icons.IconVirtualRealityGrey1, name: 'IconVirtualRealityGrey1' },
  { icon: Icons.IconVirtualRealityGrey10, name: 'IconVirtualRealityGrey10' },
  { icon: Icons.IconVirtualRealityGrey11, name: 'IconVirtualRealityGrey11' },
  { icon: Icons.IconVirtualRealityGrey12, name: 'IconVirtualRealityGrey12' },
  { icon: Icons.IconVirtualRealityGrey13, name: 'IconVirtualRealityGrey13' },
  { icon: Icons.IconVirtualRealityGrey14, name: 'IconVirtualRealityGrey14' },
  { icon: Icons.IconVirtualRealityGrey15, name: 'IconVirtualRealityGrey15' },
  { icon: Icons.IconVirtualRealityGrey16, name: 'IconVirtualRealityGrey16' },
  { icon: Icons.IconVirtualRealityGrey2, name: 'IconVirtualRealityGrey2' },
  { icon: Icons.IconVirtualRealityGrey3, name: 'IconVirtualRealityGrey3' },
  { icon: Icons.IconVirtualRealityGrey4, name: 'IconVirtualRealityGrey4' },
  { icon: Icons.IconVirtualRealityGrey5, name: 'IconVirtualRealityGrey5' },
  { icon: Icons.IconVirtualRealityGrey6, name: 'IconVirtualRealityGrey6' },
  { icon: Icons.IconVirtualRealityGrey7, name: 'IconVirtualRealityGrey7' },
  { icon: Icons.IconVirtualRealityGrey8, name: 'IconVirtualRealityGrey8' },
  { icon: Icons.IconVirtualRealityGrey9, name: 'IconVirtualRealityGrey9' },
];