/**
 * Generated by scripts/generate-icons.js.
 * DO NOT EDIT!
 */

import * as Icons from '../../virtual-reality-color';

export const ICON_LIST = [
  { icon: Icons.IconVirtualRealityColor1, name: 'IconVirtualRealityColor1' },
  { icon: Icons.IconVirtualRealityColor10, name: 'IconVirtualRealityColor10' },
  { icon: Icons.IconVirtualRealityColor11, name: 'IconVirtualRealityColor11' },
  { icon: Icons.IconVirtualRealityColor12, name: 'IconVirtualRealityColor12' },
  { icon: Icons.IconVirtualRealityColor13, name: 'IconVirtualRealityColor13' },
  { icon: Icons.IconVirtualRealityColor14, name: 'IconVirtualRealityColor14' },
  { icon: Icons.IconVirtualRealityColor15, name: 'IconVirtualRealityColor15' },
  { icon: Icons.IconVirtualRealityColor16, name: 'IconVirtualRealityColor16' },
  { icon: Icons.IconVirtualRealityColor2, name: 'IconVirtualRealityColor2' },
  { icon: Icons.IconVirtualRealityColor3, name: 'IconVirtualRealityColor3' },
  { icon: Icons.IconVirtualRealityColor4, name: 'IconVirtualRealityColor4' },
  { icon: Icons.IconVirtualRealityColor5, name: 'IconVirtualRealityColor5' },
  { icon: Icons.IconVirtualRealityColor6, name: 'IconVirtualRealityColor6' },
  { icon: Icons.IconVirtualRealityColor7, name: 'IconVirtualRealityColor7' },
  { icon: Icons.IconVirtualRealityColor8, name: 'IconVirtualRealityColor8' },
  { icon: Icons.IconVirtualRealityColor9, name: 'IconVirtualRealityColor9' },
];