/**
 * Generated by scripts/generate-icons.js.
 * DO NOT EDIT!
 */

import * as Icons from '../../zoo-color';

export const ICON_LIST = [
  { icon: Icons.IconZooColor1, name: 'IconZooColor1' },
  { icon: Icons.IconZooColor10, name: 'IconZooColor10' },
  { icon: Icons.IconZooColor11, name: 'IconZooColor11' },
  { icon: Icons.IconZooColor12, name: 'IconZooColor12' },
  { icon: Icons.IconZooColor13, name: 'IconZooColor13' },
  { icon: Icons.IconZooColor14, name: 'IconZooColor14' },
  { icon: Icons.IconZooColor15, name: 'IconZooColor15' },
  { icon: Icons.IconZooColor16, name: 'IconZooColor16' },
  { icon: Icons.IconZooColor17, name: 'IconZooColor17' },
  { icon: Icons.IconZooColor18, name: 'IconZooColor18' },
  { icon: Icons.IconZooColor19, name: 'IconZooColor19' },
  { icon: Icons.IconZooColor2, name: 'IconZooColor2' },
  { icon: Icons.IconZooColor20, name: 'IconZooColor20' },
  { icon: Icons.IconZooColor21, name: 'IconZooColor21' },
  { icon: Icons.IconZooColor22, name: 'IconZooColor22' },
  { icon: Icons.IconZooColor23, name: 'IconZooColor23' },
  { icon: Icons.IconZooColor24, name: 'IconZooColor24' },
  { icon: Icons.IconZooColor25, name: 'IconZooColor25' },
  { icon: Icons.IconZooColor3, name: 'IconZooColor3' },
  { icon: Icons.IconZooColor4, name: 'IconZooColor4' },
  { icon: Icons.IconZooColor5, name: 'IconZooColor5' },
  { icon: Icons.IconZooColor6, name: 'IconZooColor6' },
  { icon: Icons.IconZooColor7, name: 'IconZooColor7' },
  { icon: Icons.IconZooColor8, name: 'IconZooColor8' },
  { icon: Icons.IconZooColor9, name: 'IconZooColor9' },
];