/**
 * Generated by scripts/generate-icons.js.
 * DO NOT EDIT!
 */

import * as Icons from '../../zoo-grey';

export const ICON_LIST = [
  { icon: Icons.IconZooGrey1, name: 'IconZooGrey1' },
  { icon: Icons.IconZooGrey10, name: 'IconZooGrey10' },
  { icon: Icons.IconZooGrey11, name: 'IconZooGrey11' },
  { icon: Icons.IconZooGrey12, name: 'IconZooGrey12' },
  { icon: Icons.IconZooGrey13, name: 'IconZooGrey13' },
  { icon: Icons.IconZooGrey14, name: 'IconZooGrey14' },
  { icon: Icons.IconZooGrey15, name: 'IconZooGrey15' },
  { icon: Icons.IconZooGrey16, name: 'IconZooGrey16' },
  { icon: Icons.IconZooGrey17, name: 'IconZooGrey17' },
  { icon: Icons.IconZooGrey18, name: 'IconZooGrey18' },
  { icon: Icons.IconZooGrey19, name: 'IconZooGrey19' },
  { icon: Icons.IconZooGrey2, name: 'IconZooGrey2' },
  { icon: Icons.IconZooGrey20, name: 'IconZooGrey20' },
  { icon: Icons.IconZooGrey21, name: 'IconZooGrey21' },
  { icon: Icons.IconZooGrey22, name: 'IconZooGrey22' },
  { icon: Icons.IconZooGrey23, name: 'IconZooGrey23' },
  { icon: Icons.IconZooGrey24, name: 'IconZooGrey24' },
  { icon: Icons.IconZooGrey25, name: 'IconZooGrey25' },
  { icon: Icons.IconZooGrey3, name: 'IconZooGrey3' },
  { icon: Icons.IconZooGrey4, name: 'IconZooGrey4' },
  { icon: Icons.IconZooGrey5, name: 'IconZooGrey5' },
  { icon: Icons.IconZooGrey6, name: 'IconZooGrey6' },
  { icon: Icons.IconZooGrey7, name: 'IconZooGrey7' },
  { icon: Icons.IconZooGrey8, name: 'IconZooGrey8' },
  { icon: Icons.IconZooGrey9, name: 'IconZooGrey9' },
];