const fs = require('fs');

const generateScript = () => {
  const svgDir = './assets/';
  const saveDir = './scripts/';
  let scriptOutput = `# Generated by scripts/generate-script.js
# DO NO EDIT

`;
  
  // Read root Svg emoji directory
  fs.readdirSync(svgDir).forEach(folderName => {
    if (folderName === '.DS_Store') return;
    const flowArray = folderName.split('-');
    const flow = flowArray[flowArray.length - 1];
    scriptOutput += `svgr --template scripts/svgr-template.js --config-file scripts/.svgrrc-${flow}.js -d src/${folderName} --ext tsx assets/${folderName}
`;
  });
  fs.writeFileSync(`${saveDir}all-scripts.sh`, scriptOutput);
};

generateScript();
