const fs = require("fs");
const path = require("path");

const generate = (key, iconListForStory) => {
  const iconDir = `./src/icons/${key}`;
  const iconIndexFile = `${iconDir}.tsx`;
  const relativeIconDir = `../../${key}`;

  let iconIndexOutput = `/**
 * Generated by scripts/generate-icons.js.
 * DO NOT EDIT!
 */

`;

  let iconListOutput = `/**
 * Generated by scripts/generate-icons.js.
 * DO NOT EDIT!
 */

import * as Icons from '${relativeIconDir}';

export const ICON_LIST = [
`;

  fs.readdirSync(iconDir).forEach(fileName => {
    const baseName = path.basename(fileName, ".tsx");
    const iconName = `Icon${baseName}`;
    iconIndexOutput += `export { default as ${iconName} }
      from './${key}/${baseName}';
`;
    iconListOutput += `  { icon: Icons.${iconName}, name: '${iconName}' },
`;
  });

  iconListOutput += "];";

  fs.writeFileSync(iconIndexFile, iconIndexOutput);
  fs.writeFileSync(iconListForStory, iconListOutput);
};

generate("zoo-grey", "./src/icons/__stories__/components/zoo-grey-list.ts");
generate("zoo-color", "./src/icons/__stories__/components/zoo-color-list.ts");
