/**
 * Generated by scripts/generate-icons.js
 * DO NOT EDIT!
 */

import * as Icons from '../business-color';

export const ICON_LIST = [
  { icon: Icons.BusinessColor1, name: 'BusinessColor1' },
  { icon: Icons.BusinessColor10, name: 'BusinessColor10' },
  { icon: Icons.BusinessColor11, name: 'BusinessColor11' },
  { icon: Icons.BusinessColor12, name: 'BusinessColor12' },
  { icon: Icons.BusinessColor13, name: 'BusinessColor13' },
  { icon: Icons.BusinessColor14, name: 'BusinessColor14' },
  { icon: Icons.BusinessColor15, name: 'BusinessColor15' },
  { icon: Icons.BusinessColor16, name: 'BusinessColor16' },
  { icon: Icons.BusinessColor17, name: 'BusinessColor17' },
  { icon: Icons.BusinessColor18, name: 'BusinessColor18' },
  { icon: Icons.BusinessColor19, name: 'BusinessColor19' },
  { icon: Icons.BusinessColor2, name: 'BusinessColor2' },
  { icon: Icons.BusinessColor20, name: 'BusinessColor20' },
  { icon: Icons.BusinessColor21, name: 'BusinessColor21' },
  { icon: Icons.BusinessColor22, name: 'BusinessColor22' },
  { icon: Icons.BusinessColor23, name: 'BusinessColor23' },
  { icon: Icons.BusinessColor24, name: 'BusinessColor24' },
  { icon: Icons.BusinessColor25, name: 'BusinessColor25' },
  { icon: Icons.BusinessColor26, name: 'BusinessColor26' },
  { icon: Icons.BusinessColor27, name: 'BusinessColor27' },
  { icon: Icons.BusinessColor28, name: 'BusinessColor28' },
  { icon: Icons.BusinessColor29, name: 'BusinessColor29' },
  { icon: Icons.BusinessColor3, name: 'BusinessColor3' },
  { icon: Icons.BusinessColor30, name: 'BusinessColor30' },
  { icon: Icons.BusinessColor31, name: 'BusinessColor31' },
  { icon: Icons.BusinessColor32, name: 'BusinessColor32' },
  { icon: Icons.BusinessColor33, name: 'BusinessColor33' },
  { icon: Icons.BusinessColor34, name: 'BusinessColor34' },
  { icon: Icons.BusinessColor35, name: 'BusinessColor35' },
  { icon: Icons.BusinessColor36, name: 'BusinessColor36' },
  { icon: Icons.BusinessColor37, name: 'BusinessColor37' },
  { icon: Icons.BusinessColor38, name: 'BusinessColor38' },
  { icon: Icons.BusinessColor39, name: 'BusinessColor39' },
  { icon: Icons.BusinessColor4, name: 'BusinessColor4' },
  { icon: Icons.BusinessColor40, name: 'BusinessColor40' },
  { icon: Icons.BusinessColor5, name: 'BusinessColor5' },
  { icon: Icons.BusinessColor6, name: 'BusinessColor6' },
  { icon: Icons.BusinessColor7, name: 'BusinessColor7' },
  { icon: Icons.BusinessColor8, name: 'BusinessColor8' },
  { icon: Icons.BusinessColor9, name: 'BusinessColor9' },
];
