/**
 * Generated by scripts/generate-icons.js
 * DO NOT EDIT!
 */
        
import * as Icons from '../business-grey';

export const ICON_LIST = [
  { icon: Icons.BusinessGrey1, name: 'BusinessGrey1' },
  { icon: Icons.BusinessGrey10, name: 'BusinessGrey10' },
  { icon: Icons.BusinessGrey11, name: 'BusinessGrey11' },
  { icon: Icons.BusinessGrey12, name: 'BusinessGrey12' },
  { icon: Icons.BusinessGrey13, name: 'BusinessGrey13' },
  { icon: Icons.BusinessGrey14, name: 'BusinessGrey14' },
  { icon: Icons.BusinessGrey15, name: 'BusinessGrey15' },
  { icon: Icons.BusinessGrey16, name: 'BusinessGrey16' },
  { icon: Icons.BusinessGrey17, name: 'BusinessGrey17' },
  { icon: Icons.BusinessGrey18, name: 'BusinessGrey18' },
  { icon: Icons.BusinessGrey19, name: 'BusinessGrey19' },
  { icon: Icons.BusinessGrey2, name: 'BusinessGrey2' },
  { icon: Icons.BusinessGrey20, name: 'BusinessGrey20' },
  { icon: Icons.BusinessGrey3, name: 'BusinessGrey3' },
  { icon: Icons.BusinessGrey4, name: 'BusinessGrey4' },
  { icon: Icons.BusinessGrey5, name: 'BusinessGrey5' },
  { icon: Icons.BusinessGrey6, name: 'BusinessGrey6' },
  { icon: Icons.BusinessGrey7, name: 'BusinessGrey7' },
  { icon: Icons.BusinessGrey8, name: 'BusinessGrey8' },
  { icon: Icons.BusinessGrey9, name: 'BusinessGrey9' },
];
