/**
 * Generated by scripts/generate-icons.js
 * DO NOT EDIT!
 */

import * as Icons from '../financial-grey';

export const ICON_LIST = [
  { icon: Icons.FinancialGrey1, name: 'FinancialGrey1' },
  { icon: Icons.FinancialGrey10, name: 'FinancialGrey10' },
  { icon: Icons.FinancialGrey11, name: 'FinancialGrey11' },
  { icon: Icons.FinancialGrey12, name: 'FinancialGrey12' },
  { icon: Icons.FinancialGrey13, name: 'FinancialGrey13' },
  { icon: Icons.FinancialGrey14, name: 'FinancialGrey14' },
  { icon: Icons.FinancialGrey15, name: 'FinancialGrey15' },
  { icon: Icons.FinancialGrey16, name: 'FinancialGrey16' },
  { icon: Icons.FinancialGrey17, name: 'FinancialGrey17' },
  { icon: Icons.FinancialGrey18, name: 'FinancialGrey18' },
  { icon: Icons.FinancialGrey19, name: 'FinancialGrey19' },
  { icon: Icons.FinancialGrey2, name: 'FinancialGrey2' },
  { icon: Icons.FinancialGrey20, name: 'FinancialGrey20' },
  { icon: Icons.FinancialGrey21, name: 'FinancialGrey21' },
  { icon: Icons.FinancialGrey22, name: 'FinancialGrey22' },
  { icon: Icons.FinancialGrey23, name: 'FinancialGrey23' },
  { icon: Icons.FinancialGrey24, name: 'FinancialGrey24' },
  { icon: Icons.FinancialGrey25, name: 'FinancialGrey25' },
  { icon: Icons.FinancialGrey26, name: 'FinancialGrey26' },
  { icon: Icons.FinancialGrey3, name: 'FinancialGrey3' },
  { icon: Icons.FinancialGrey4, name: 'FinancialGrey4' },
  { icon: Icons.FinancialGrey5, name: 'FinancialGrey5' },
  { icon: Icons.FinancialGrey6, name: 'FinancialGrey6' },
  { icon: Icons.FinancialGrey7, name: 'FinancialGrey7' },
  { icon: Icons.FinancialGrey8, name: 'FinancialGrey8' },
  { icon: Icons.FinancialGrey9, name: 'FinancialGrey9' },
];
