/**
 * Generated by scripts/generate-icons.js
 * DO NOT EDIT!
 */

import * as Icons from '../food-dishes-color';

export const ICON_LIST = [
  { icon: Icons.FoodDishesColor1, name: 'FoodDishesColor1' },
  { icon: Icons.FoodDishesColor10, name: 'FoodDishesColor10' },
  { icon: Icons.FoodDishesColor11, name: 'FoodDishesColor11' },
  { icon: Icons.FoodDishesColor12, name: 'FoodDishesColor12' },
  { icon: Icons.FoodDishesColor13, name: 'FoodDishesColor13' },
  { icon: Icons.FoodDishesColor14, name: 'FoodDishesColor14' },
  { icon: Icons.FoodDishesColor15, name: 'FoodDishesColor15' },
  { icon: Icons.FoodDishesColor2, name: 'FoodDishesColor2' },
  { icon: Icons.FoodDishesColor3, name: 'FoodDishesColor3' },
  { icon: Icons.FoodDishesColor4, name: 'FoodDishesColor4' },
  { icon: Icons.FoodDishesColor5, name: 'FoodDishesColor5' },
  { icon: Icons.FoodDishesColor6, name: 'FoodDishesColor6' },
  { icon: Icons.FoodDishesColor7, name: 'FoodDishesColor7' },
  { icon: Icons.FoodDishesColor8, name: 'FoodDishesColor8' },
  { icon: Icons.FoodDishesColor9, name: 'FoodDishesColor9' },
];
