/**
 * Generated by scripts/generate-icons.js
 * DO NOT EDIT!
 */
        
import * as Icons from '../fourthofjuly-grey';

export const ICON_LIST = [
  { icon: Icons.FourthofjulyGrey1, name: 'FourthofjulyGrey1' },
  { icon: Icons.FourthofjulyGrey10, name: 'FourthofjulyGrey10' },
  { icon: Icons.FourthofjulyGrey11, name: 'FourthofjulyGrey11' },
  { icon: Icons.FourthofjulyGrey12, name: 'FourthofjulyGrey12' },
  { icon: Icons.FourthofjulyGrey13, name: 'FourthofjulyGrey13' },
  { icon: Icons.FourthofjulyGrey14, name: 'FourthofjulyGrey14' },
  { icon: Icons.FourthofjulyGrey15, name: 'FourthofjulyGrey15' },
  { icon: Icons.FourthofjulyGrey16, name: 'FourthofjulyGrey16' },
  { icon: Icons.FourthofjulyGrey17, name: 'FourthofjulyGrey17' },
  { icon: Icons.FourthofjulyGrey18, name: 'FourthofjulyGrey18' },
  { icon: Icons.FourthofjulyGrey19, name: 'FourthofjulyGrey19' },
  { icon: Icons.FourthofjulyGrey2, name: 'FourthofjulyGrey2' },
  { icon: Icons.FourthofjulyGrey20, name: 'FourthofjulyGrey20' },
  { icon: Icons.FourthofjulyGrey21, name: 'FourthofjulyGrey21' },
  { icon: Icons.FourthofjulyGrey22, name: 'FourthofjulyGrey22' },
  { icon: Icons.FourthofjulyGrey23, name: 'FourthofjulyGrey23' },
  { icon: Icons.FourthofjulyGrey24, name: 'FourthofjulyGrey24' },
  { icon: Icons.FourthofjulyGrey25, name: 'FourthofjulyGrey25' },
  { icon: Icons.FourthofjulyGrey26, name: 'FourthofjulyGrey26' },
  { icon: Icons.FourthofjulyGrey27, name: 'FourthofjulyGrey27' },
  { icon: Icons.FourthofjulyGrey28, name: 'FourthofjulyGrey28' },
  { icon: Icons.FourthofjulyGrey29, name: 'FourthofjulyGrey29' },
  { icon: Icons.FourthofjulyGrey3, name: 'FourthofjulyGrey3' },
  { icon: Icons.FourthofjulyGrey30, name: 'FourthofjulyGrey30' },
  { icon: Icons.FourthofjulyGrey31, name: 'FourthofjulyGrey31' },
  { icon: Icons.FourthofjulyGrey32, name: 'FourthofjulyGrey32' },
  { icon: Icons.FourthofjulyGrey33, name: 'FourthofjulyGrey33' },
  { icon: Icons.FourthofjulyGrey34, name: 'FourthofjulyGrey34' },
  { icon: Icons.FourthofjulyGrey35, name: 'FourthofjulyGrey35' },
  { icon: Icons.FourthofjulyGrey36, name: 'FourthofjulyGrey36' },
  { icon: Icons.FourthofjulyGrey37, name: 'FourthofjulyGrey37' },
  { icon: Icons.FourthofjulyGrey38, name: 'FourthofjulyGrey38' },
  { icon: Icons.FourthofjulyGrey39, name: 'FourthofjulyGrey39' },
  { icon: Icons.FourthofjulyGrey4, name: 'FourthofjulyGrey4' },
  { icon: Icons.FourthofjulyGrey40, name: 'FourthofjulyGrey40' },
  { icon: Icons.FourthofjulyGrey5, name: 'FourthofjulyGrey5' },
  { icon: Icons.FourthofjulyGrey6, name: 'FourthofjulyGrey6' },
  { icon: Icons.FourthofjulyGrey7, name: 'FourthofjulyGrey7' },
  { icon: Icons.FourthofjulyGrey8, name: 'FourthofjulyGrey8' },
  { icon: Icons.FourthofjulyGrey9, name: 'FourthofjulyGrey9' },
];
