/**
 * Generated by scripts/generate-icons.js
 * DO NOT EDIT!
 */

import * as Icons from '../green-energy-color';

export const ICON_LIST = [
  { icon: Icons.GreenEnergyColor1, name: 'GreenEnergyColor1' },
  { icon: Icons.GreenEnergyColor10, name: 'GreenEnergyColor10' },
  { icon: Icons.GreenEnergyColor11, name: 'GreenEnergyColor11' },
  { icon: Icons.GreenEnergyColor12, name: 'GreenEnergyColor12' },
  { icon: Icons.GreenEnergyColor13, name: 'GreenEnergyColor13' },
  { icon: Icons.GreenEnergyColor14, name: 'GreenEnergyColor14' },
  { icon: Icons.GreenEnergyColor15, name: 'GreenEnergyColor15' },
  { icon: Icons.GreenEnergyColor16, name: 'GreenEnergyColor16' },
  { icon: Icons.GreenEnergyColor17, name: 'GreenEnergyColor17' },
  { icon: Icons.GreenEnergyColor18, name: 'GreenEnergyColor18' },
  { icon: Icons.GreenEnergyColor19, name: 'GreenEnergyColor19' },
  { icon: Icons.GreenEnergyColor2, name: 'GreenEnergyColor2' },
  { icon: Icons.GreenEnergyColor20, name: 'GreenEnergyColor20' },
  { icon: Icons.GreenEnergyColor21, name: 'GreenEnergyColor21' },
  { icon: Icons.GreenEnergyColor22, name: 'GreenEnergyColor22' },
  { icon: Icons.GreenEnergyColor23, name: 'GreenEnergyColor23' },
  { icon: Icons.GreenEnergyColor24, name: 'GreenEnergyColor24' },
  { icon: Icons.GreenEnergyColor25, name: 'GreenEnergyColor25' },
  { icon: Icons.GreenEnergyColor26, name: 'GreenEnergyColor26' },
  { icon: Icons.GreenEnergyColor27, name: 'GreenEnergyColor27' },
  { icon: Icons.GreenEnergyColor28, name: 'GreenEnergyColor28' },
  { icon: Icons.GreenEnergyColor29, name: 'GreenEnergyColor29' },
  { icon: Icons.GreenEnergyColor3, name: 'GreenEnergyColor3' },
  { icon: Icons.GreenEnergyColor30, name: 'GreenEnergyColor30' },
  { icon: Icons.GreenEnergyColor31, name: 'GreenEnergyColor31' },
  { icon: Icons.GreenEnergyColor32, name: 'GreenEnergyColor32' },
  { icon: Icons.GreenEnergyColor4, name: 'GreenEnergyColor4' },
  { icon: Icons.GreenEnergyColor5, name: 'GreenEnergyColor5' },
  { icon: Icons.GreenEnergyColor6, name: 'GreenEnergyColor6' },
  { icon: Icons.GreenEnergyColor7, name: 'GreenEnergyColor7' },
  { icon: Icons.GreenEnergyColor8, name: 'GreenEnergyColor8' },
  { icon: Icons.GreenEnergyColor9, name: 'GreenEnergyColor9' },
];
