/**
 * Generated by scripts/generate-icons.js
 * DO NOT EDIT!
 */

import * as Icons from '../helmet-grey';

export const ICON_LIST = [
  { icon: Icons.HelmetGrey1, name: 'HelmetGrey1' },
  { icon: Icons.HelmetGrey10, name: 'HelmetGrey10' },
  { icon: Icons.HelmetGrey11, name: 'HelmetGrey11' },
  { icon: Icons.HelmetGrey12, name: 'HelmetGrey12' },
  { icon: Icons.HelmetGrey13, name: 'HelmetGrey13' },
  { icon: Icons.HelmetGrey14, name: 'HelmetGrey14' },
  { icon: Icons.HelmetGrey15, name: 'HelmetGrey15' },
  { icon: Icons.HelmetGrey16, name: 'HelmetGrey16' },
  { icon: Icons.HelmetGrey17, name: 'HelmetGrey17' },
  { icon: Icons.HelmetGrey18, name: 'HelmetGrey18' },
  { icon: Icons.HelmetGrey19, name: 'HelmetGrey19' },
  { icon: Icons.HelmetGrey2, name: 'HelmetGrey2' },
  { icon: Icons.HelmetGrey20, name: 'HelmetGrey20' },
  { icon: Icons.HelmetGrey21, name: 'HelmetGrey21' },
  { icon: Icons.HelmetGrey22, name: 'HelmetGrey22' },
  { icon: Icons.HelmetGrey23, name: 'HelmetGrey23' },
  { icon: Icons.HelmetGrey24, name: 'HelmetGrey24' },
  { icon: Icons.HelmetGrey25, name: 'HelmetGrey25' },
  { icon: Icons.HelmetGrey26, name: 'HelmetGrey26' },
  { icon: Icons.HelmetGrey27, name: 'HelmetGrey27' },
  { icon: Icons.HelmetGrey28, name: 'HelmetGrey28' },
  { icon: Icons.HelmetGrey29, name: 'HelmetGrey29' },
  { icon: Icons.HelmetGrey3, name: 'HelmetGrey3' },
  { icon: Icons.HelmetGrey30, name: 'HelmetGrey30' },
  { icon: Icons.HelmetGrey31, name: 'HelmetGrey31' },
  { icon: Icons.HelmetGrey32, name: 'HelmetGrey32' },
  { icon: Icons.HelmetGrey4, name: 'HelmetGrey4' },
  { icon: Icons.HelmetGrey5, name: 'HelmetGrey5' },
  { icon: Icons.HelmetGrey6, name: 'HelmetGrey6' },
  { icon: Icons.HelmetGrey7, name: 'HelmetGrey7' },
  { icon: Icons.HelmetGrey8, name: 'HelmetGrey8' },
  { icon: Icons.HelmetGrey9, name: 'HelmetGrey9' },
];
