/**
 * Generated by scripts/generate-icons.js
 * DO NOT EDIT!
 */
        
import * as Icons from '../home-color';

export const ICON_LIST = [
  { icon: Icons.HomeColor1, name: 'HomeColor1' },
  { icon: Icons.HomeColor10, name: 'HomeColor10' },
  { icon: Icons.HomeColor11, name: 'HomeColor11' },
  { icon: Icons.HomeColor12, name: 'HomeColor12' },
  { icon: Icons.HomeColor13, name: 'HomeColor13' },
  { icon: Icons.HomeColor14, name: 'HomeColor14' },
  { icon: Icons.HomeColor15, name: 'HomeColor15' },
  { icon: Icons.HomeColor16, name: 'HomeColor16' },
  { icon: Icons.HomeColor2, name: 'HomeColor2' },
  { icon: Icons.HomeColor3, name: 'HomeColor3' },
  { icon: Icons.HomeColor4, name: 'HomeColor4' },
  { icon: Icons.HomeColor5, name: 'HomeColor5' },
  { icon: Icons.HomeColor6, name: 'HomeColor6' },
  { icon: Icons.HomeColor7, name: 'HomeColor7' },
  { icon: Icons.HomeColor8, name: 'HomeColor8' },
  { icon: Icons.HomeColor9, name: 'HomeColor9' },
];
