/**
 * Generated by scripts/generate-icons.js
 * DO NOT EDIT!
 */

import * as Icons from '../home-grey';

export const ICON_LIST = [
  { icon: Icons.HomeGrey1, name: 'HomeGrey1' },
  { icon: Icons.HomeGrey10, name: 'HomeGrey10' },
  { icon: Icons.HomeGrey11, name: 'HomeGrey11' },
  { icon: Icons.HomeGrey12, name: 'HomeGrey12' },
  { icon: Icons.HomeGrey13, name: 'HomeGrey13' },
  { icon: Icons.HomeGrey14, name: 'HomeGrey14' },
  { icon: Icons.HomeGrey15, name: 'HomeGrey15' },
  { icon: Icons.HomeGrey16, name: 'HomeGrey16' },
  { icon: Icons.HomeGrey2, name: 'HomeGrey2' },
  { icon: Icons.HomeGrey3, name: 'HomeGrey3' },
  { icon: Icons.HomeGrey4, name: 'HomeGrey4' },
  { icon: Icons.HomeGrey5, name: 'HomeGrey5' },
  { icon: Icons.HomeGrey6, name: 'HomeGrey6' },
  { icon: Icons.HomeGrey7, name: 'HomeGrey7' },
  { icon: Icons.HomeGrey8, name: 'HomeGrey8' },
  { icon: Icons.HomeGrey9, name: 'HomeGrey9' },
];
