/**
 * Generated by scripts/generate-icons.js
 * DO NOT EDIT!
 */

import * as Icons from '../kitchen-color';

export const ICON_LIST = [
  { icon: Icons.KitchenColor1, name: 'KitchenColor1' },
  { icon: Icons.KitchenColor10, name: 'KitchenColor10' },
  { icon: Icons.KitchenColor11, name: 'KitchenColor11' },
  { icon: Icons.KitchenColor12, name: 'KitchenColor12' },
  { icon: Icons.KitchenColor13, name: 'KitchenColor13' },
  { icon: Icons.KitchenColor14, name: 'KitchenColor14' },
  { icon: Icons.KitchenColor15, name: 'KitchenColor15' },
  { icon: Icons.KitchenColor16, name: 'KitchenColor16' },
  { icon: Icons.KitchenColor2, name: 'KitchenColor2' },
  { icon: Icons.KitchenColor3, name: 'KitchenColor3' },
  { icon: Icons.KitchenColor4, name: 'KitchenColor4' },
  { icon: Icons.KitchenColor5, name: 'KitchenColor5' },
  { icon: Icons.KitchenColor6, name: 'KitchenColor6' },
  { icon: Icons.KitchenColor7, name: 'KitchenColor7' },
  { icon: Icons.KitchenColor8, name: 'KitchenColor8' },
  { icon: Icons.KitchenColor9, name: 'KitchenColor9' },
];
