/**
 * Generated by scripts/generate-icons.js
 * DO NOT EDIT!
 */
        
import * as Icons from '../kitchen-grey';

export const ICON_LIST = [
  { icon: Icons.KitchenGrey1, name: 'KitchenGrey1' },
  { icon: Icons.KitchenGrey10, name: 'KitchenGrey10' },
  { icon: Icons.KitchenGrey11, name: 'KitchenGrey11' },
  { icon: Icons.KitchenGrey12, name: 'KitchenGrey12' },
  { icon: Icons.KitchenGrey13, name: 'KitchenGrey13' },
  { icon: Icons.KitchenGrey14, name: 'KitchenGrey14' },
  { icon: Icons.KitchenGrey15, name: 'KitchenGrey15' },
  { icon: Icons.KitchenGrey16, name: 'KitchenGrey16' },
  { icon: Icons.KitchenGrey2, name: 'KitchenGrey2' },
  { icon: Icons.KitchenGrey3, name: 'KitchenGrey3' },
  { icon: Icons.KitchenGrey4, name: 'KitchenGrey4' },
  { icon: Icons.KitchenGrey5, name: 'KitchenGrey5' },
  { icon: Icons.KitchenGrey6, name: 'KitchenGrey6' },
  { icon: Icons.KitchenGrey7, name: 'KitchenGrey7' },
  { icon: Icons.KitchenGrey8, name: 'KitchenGrey8' },
  { icon: Icons.KitchenGrey9, name: 'KitchenGrey9' },
];
