/**
 * Generated by scripts/generate-icons.js
 * DO NOT EDIT!
 */
        
import * as Icons from '../knife-color';

export const ICON_LIST = [
  { icon: Icons.KnifeColor1, name: 'KnifeColor1' },
  { icon: Icons.KnifeColor10, name: 'KnifeColor10' },
  { icon: Icons.KnifeColor11, name: 'KnifeColor11' },
  { icon: Icons.KnifeColor12, name: 'KnifeColor12' },
  { icon: Icons.KnifeColor13, name: 'KnifeColor13' },
  { icon: Icons.KnifeColor14, name: 'KnifeColor14' },
  { icon: Icons.KnifeColor15, name: 'KnifeColor15' },
  { icon: Icons.KnifeColor16, name: 'KnifeColor16' },
  { icon: Icons.KnifeColor2, name: 'KnifeColor2' },
  { icon: Icons.KnifeColor3, name: 'KnifeColor3' },
  { icon: Icons.KnifeColor4, name: 'KnifeColor4' },
  { icon: Icons.KnifeColor5, name: 'KnifeColor5' },
  { icon: Icons.KnifeColor6, name: 'KnifeColor6' },
  { icon: Icons.KnifeColor7, name: 'KnifeColor7' },
  { icon: Icons.KnifeColor8, name: 'KnifeColor8' },
  { icon: Icons.KnifeColor9, name: 'KnifeColor9' },
];
