/**
 * Generated by scripts/generate-icons.js
 * DO NOT EDIT!
 */

import * as Icons from '../knife-grey';

export const ICON_LIST = [
  { icon: Icons.KnifeGrey1, name: 'KnifeGrey1' },
  { icon: Icons.KnifeGrey10, name: 'KnifeGrey10' },
  { icon: Icons.KnifeGrey11, name: 'KnifeGrey11' },
  { icon: Icons.KnifeGrey12, name: 'KnifeGrey12' },
  { icon: Icons.KnifeGrey13, name: 'KnifeGrey13' },
  { icon: Icons.KnifeGrey14, name: 'KnifeGrey14' },
  { icon: Icons.KnifeGrey15, name: 'KnifeGrey15' },
  { icon: Icons.KnifeGrey16, name: 'KnifeGrey16' },
  { icon: Icons.KnifeGrey2, name: 'KnifeGrey2' },
  { icon: Icons.KnifeGrey3, name: 'KnifeGrey3' },
  { icon: Icons.KnifeGrey4, name: 'KnifeGrey4' },
  { icon: Icons.KnifeGrey5, name: 'KnifeGrey5' },
  { icon: Icons.KnifeGrey6, name: 'KnifeGrey6' },
  { icon: Icons.KnifeGrey7, name: 'KnifeGrey7' },
  { icon: Icons.KnifeGrey8, name: 'KnifeGrey8' },
  { icon: Icons.KnifeGrey9, name: 'KnifeGrey9' },
];
