/**
 * Generated by scripts/generate-icons.js
 * DO NOT EDIT!
 */
        
import * as Icons from '../law-color';

export const ICON_LIST = [
  { icon: Icons.LawColor1, name: 'LawColor1' },
  { icon: Icons.LawColor10, name: 'LawColor10' },
  { icon: Icons.LawColor11, name: 'LawColor11' },
  { icon: Icons.LawColor12, name: 'LawColor12' },
  { icon: Icons.LawColor13, name: 'LawColor13' },
  { icon: Icons.LawColor14, name: 'LawColor14' },
  { icon: Icons.LawColor15, name: 'LawColor15' },
  { icon: Icons.LawColor16, name: 'LawColor16' },
  { icon: Icons.LawColor2, name: 'LawColor2' },
  { icon: Icons.LawColor3, name: 'LawColor3' },
  { icon: Icons.LawColor4, name: 'LawColor4' },
  { icon: Icons.LawColor5, name: 'LawColor5' },
  { icon: Icons.LawColor6, name: 'LawColor6' },
  { icon: Icons.LawColor7, name: 'LawColor7' },
  { icon: Icons.LawColor8, name: 'LawColor8' },
  { icon: Icons.LawColor9, name: 'LawColor9' },
];
