/**
 * Generated by scripts/generate-icons.js
 * DO NOT EDIT!
 */
        
import * as Icons from '../law-grey';

export const ICON_LIST = [
  { icon: Icons.LawGrey1, name: 'LawGrey1' },
  { icon: Icons.LawGrey10, name: 'LawGrey10' },
  { icon: Icons.LawGrey11, name: 'LawGrey11' },
  { icon: Icons.LawGrey12, name: 'LawGrey12' },
  { icon: Icons.LawGrey13, name: 'LawGrey13' },
  { icon: Icons.LawGrey14, name: 'LawGrey14' },
  { icon: Icons.LawGrey15, name: 'LawGrey15' },
  { icon: Icons.LawGrey16, name: 'LawGrey16' },
  { icon: Icons.LawGrey2, name: 'LawGrey2' },
  { icon: Icons.LawGrey3, name: 'LawGrey3' },
  { icon: Icons.LawGrey4, name: 'LawGrey4' },
  { icon: Icons.LawGrey5, name: 'LawGrey5' },
  { icon: Icons.LawGrey6, name: 'LawGrey6' },
  { icon: Icons.LawGrey7, name: 'LawGrey7' },
  { icon: Icons.LawGrey8, name: 'LawGrey8' },
  { icon: Icons.LawGrey9, name: 'LawGrey9' },
];
