/**
 * Generated by scripts/generate-icons.js
 * DO NOT EDIT!
 */
        
import * as Icons from '../leaf-color';

export const ICON_LIST = [
  { icon: Icons.LeafColor1, name: 'LeafColor1' },
  { icon: Icons.LeafColor10, name: 'LeafColor10' },
  { icon: Icons.LeafColor11, name: 'LeafColor11' },
  { icon: Icons.LeafColor12, name: 'LeafColor12' },
  { icon: Icons.LeafColor13, name: 'LeafColor13' },
  { icon: Icons.LeafColor14, name: 'LeafColor14' },
  { icon: Icons.LeafColor15, name: 'LeafColor15' },
  { icon: Icons.LeafColor16, name: 'LeafColor16' },
  { icon: Icons.LeafColor2, name: 'LeafColor2' },
  { icon: Icons.LeafColor3, name: 'LeafColor3' },
  { icon: Icons.LeafColor4, name: 'LeafColor4' },
  { icon: Icons.LeafColor5, name: 'LeafColor5' },
  { icon: Icons.LeafColor6, name: 'LeafColor6' },
  { icon: Icons.LeafColor7, name: 'LeafColor7' },
  { icon: Icons.LeafColor8, name: 'LeafColor8' },
  { icon: Icons.LeafColor9, name: 'LeafColor9' },
];
