/**
 * Generated by scripts/generate-icons.js
 * DO NOT EDIT!
 */

import * as Icons from '../leaf-grey';

export const ICON_LIST = [
  { icon: Icons.LeafGrey1, name: 'LeafGrey1' },
  { icon: Icons.LeafGrey10, name: 'LeafGrey10' },
  { icon: Icons.LeafGrey11, name: 'LeafGrey11' },
  { icon: Icons.LeafGrey12, name: 'LeafGrey12' },
  { icon: Icons.LeafGrey13, name: 'LeafGrey13' },
  { icon: Icons.LeafGrey14, name: 'LeafGrey14' },
  { icon: Icons.LeafGrey15, name: 'LeafGrey15' },
  { icon: Icons.LeafGrey16, name: 'LeafGrey16' },
  { icon: Icons.LeafGrey2, name: 'LeafGrey2' },
  { icon: Icons.LeafGrey3, name: 'LeafGrey3' },
  { icon: Icons.LeafGrey4, name: 'LeafGrey4' },
  { icon: Icons.LeafGrey5, name: 'LeafGrey5' },
  { icon: Icons.LeafGrey6, name: 'LeafGrey6' },
  { icon: Icons.LeafGrey7, name: 'LeafGrey7' },
  { icon: Icons.LeafGrey8, name: 'LeafGrey8' },
  { icon: Icons.LeafGrey9, name: 'LeafGrey9' },
];
