/**
 * Generated by scripts/generate-icons.js
 * DO NOT EDIT!
 */

import * as Icons from '../logistics-grey';

export const ICON_LIST = [
  { icon: Icons.LogisticsGrey1, name: 'LogisticsGrey1' },
  { icon: Icons.LogisticsGrey10, name: 'LogisticsGrey10' },
  { icon: Icons.LogisticsGrey11, name: 'LogisticsGrey11' },
  { icon: Icons.LogisticsGrey12, name: 'LogisticsGrey12' },
  { icon: Icons.LogisticsGrey13, name: 'LogisticsGrey13' },
  { icon: Icons.LogisticsGrey14, name: 'LogisticsGrey14' },
  { icon: Icons.LogisticsGrey15, name: 'LogisticsGrey15' },
  { icon: Icons.LogisticsGrey16, name: 'LogisticsGrey16' },
  { icon: Icons.LogisticsGrey17, name: 'LogisticsGrey17' },
  { icon: Icons.LogisticsGrey18, name: 'LogisticsGrey18' },
  { icon: Icons.LogisticsGrey19, name: 'LogisticsGrey19' },
  { icon: Icons.LogisticsGrey2, name: 'LogisticsGrey2' },
  { icon: Icons.LogisticsGrey20, name: 'LogisticsGrey20' },
  { icon: Icons.LogisticsGrey3, name: 'LogisticsGrey3' },
  { icon: Icons.LogisticsGrey4, name: 'LogisticsGrey4' },
  { icon: Icons.LogisticsGrey5, name: 'LogisticsGrey5' },
  { icon: Icons.LogisticsGrey6, name: 'LogisticsGrey6' },
  { icon: Icons.LogisticsGrey7, name: 'LogisticsGrey7' },
  { icon: Icons.LogisticsGrey8, name: 'LogisticsGrey8' },
  { icon: Icons.LogisticsGrey9, name: 'LogisticsGrey9' },
];
