/**
 * Generated by scripts/generate-icons.js
 * DO NOT EDIT!
 */
        
import * as Icons from '../logistics-color';

export const ICON_LIST = [
  { icon: Icons.LogisticsColor1, name: 'LogisticsColor1' },
  { icon: Icons.LogisticsColor10, name: 'LogisticsColor10' },
  { icon: Icons.LogisticsColor11, name: 'LogisticsColor11' },
  { icon: Icons.LogisticsColor12, name: 'LogisticsColor12' },
  { icon: Icons.LogisticsColor13, name: 'LogisticsColor13' },
  { icon: Icons.LogisticsColor14, name: 'LogisticsColor14' },
  { icon: Icons.LogisticsColor15, name: 'LogisticsColor15' },
  { icon: Icons.LogisticsColor16, name: 'LogisticsColor16' },
  { icon: Icons.LogisticsColor17, name: 'LogisticsColor17' },
  { icon: Icons.LogisticsColor18, name: 'LogisticsColor18' },
  { icon: Icons.LogisticsColor19, name: 'LogisticsColor19' },
  { icon: Icons.LogisticsColor2, name: 'LogisticsColor2' },
  { icon: Icons.LogisticsColor20, name: 'LogisticsColor20' },
  { icon: Icons.LogisticsColor21, name: 'LogisticsColor21' },
  { icon: Icons.LogisticsColor22, name: 'LogisticsColor22' },
  { icon: Icons.LogisticsColor23, name: 'LogisticsColor23' },
  { icon: Icons.LogisticsColor24, name: 'LogisticsColor24' },
  { icon: Icons.LogisticsColor25, name: 'LogisticsColor25' },
  { icon: Icons.LogisticsColor26, name: 'LogisticsColor26' },
  { icon: Icons.LogisticsColor27, name: 'LogisticsColor27' },
  { icon: Icons.LogisticsColor28, name: 'LogisticsColor28' },
  { icon: Icons.LogisticsColor29, name: 'LogisticsColor29' },
  { icon: Icons.LogisticsColor3, name: 'LogisticsColor3' },
  { icon: Icons.LogisticsColor30, name: 'LogisticsColor30' },
  { icon: Icons.LogisticsColor31, name: 'LogisticsColor31' },
  { icon: Icons.LogisticsColor32, name: 'LogisticsColor32' },
  { icon: Icons.LogisticsColor33, name: 'LogisticsColor33' },
  { icon: Icons.LogisticsColor34, name: 'LogisticsColor34' },
  { icon: Icons.LogisticsColor35, name: 'LogisticsColor35' },
  { icon: Icons.LogisticsColor36, name: 'LogisticsColor36' },
  { icon: Icons.LogisticsColor37, name: 'LogisticsColor37' },
  { icon: Icons.LogisticsColor38, name: 'LogisticsColor38' },
  { icon: Icons.LogisticsColor39, name: 'LogisticsColor39' },
  { icon: Icons.LogisticsColor4, name: 'LogisticsColor4' },
  { icon: Icons.LogisticsColor40, name: 'LogisticsColor40' },
  { icon: Icons.LogisticsColor5, name: 'LogisticsColor5' },
  { icon: Icons.LogisticsColor6, name: 'LogisticsColor6' },
  { icon: Icons.LogisticsColor7, name: 'LogisticsColor7' },
  { icon: Icons.LogisticsColor8, name: 'LogisticsColor8' },
  { icon: Icons.LogisticsColor9, name: 'LogisticsColor9' },
];
