/**
 * Generated by scripts/generate-icons.js
 * DO NOT EDIT!
 */
        
import * as Icons from '../lumberjack-color';

export const ICON_LIST = [
  { icon: Icons.LumerjackColor1, name: 'LumerjackColor1' },
  { icon: Icons.LumerjackColor10, name: 'LumerjackColor10' },
  { icon: Icons.LumerjackColor11, name: 'LumerjackColor11' },
  { icon: Icons.LumerjackColor12, name: 'LumerjackColor12' },
  { icon: Icons.LumerjackColor13, name: 'LumerjackColor13' },
  { icon: Icons.LumerjackColor14, name: 'LumerjackColor14' },
  { icon: Icons.LumerjackColor15, name: 'LumerjackColor15' },
  { icon: Icons.LumerjackColor16, name: 'LumerjackColor16' },
  { icon: Icons.LumerjackColor2, name: 'LumerjackColor2' },
  { icon: Icons.LumerjackColor3, name: 'LumerjackColor3' },
  { icon: Icons.LumerjackColor4, name: 'LumerjackColor4' },
  { icon: Icons.LumerjackColor5, name: 'LumerjackColor5' },
  { icon: Icons.LumerjackColor6, name: 'LumerjackColor6' },
  { icon: Icons.LumerjackColor7, name: 'LumerjackColor7' },
  { icon: Icons.LumerjackColor8, name: 'LumerjackColor8' },
  { icon: Icons.LumerjackColor9, name: 'LumerjackColor9' },
];
