/**
 * Generated by scripts/generate-icons.js
 * DO NOT EDIT!
 */

import * as Icons from '../lumberjack-grey';

export const ICON_LIST = [
  { icon: Icons.LumberjackGrey1, name: 'LumberjackGrey1' },
  { icon: Icons.LumberjackGrey10, name: 'LumberjackGrey10' },
  { icon: Icons.LumberjackGrey11, name: 'LumberjackGrey11' },
  { icon: Icons.LumberjackGrey12, name: 'LumberjackGrey12' },
  { icon: Icons.LumberjackGrey13, name: 'LumberjackGrey13' },
  { icon: Icons.LumberjackGrey14, name: 'LumberjackGrey14' },
  { icon: Icons.LumberjackGrey15, name: 'LumberjackGrey15' },
  { icon: Icons.LumberjackGrey16, name: 'LumberjackGrey16' },
  { icon: Icons.LumberjackGrey2, name: 'LumberjackGrey2' },
  { icon: Icons.LumberjackGrey3, name: 'LumberjackGrey3' },
  { icon: Icons.LumberjackGrey4, name: 'LumberjackGrey4' },
  { icon: Icons.LumberjackGrey5, name: 'LumberjackGrey5' },
  { icon: Icons.LumberjackGrey6, name: 'LumberjackGrey6' },
  { icon: Icons.LumberjackGrey7, name: 'LumberjackGrey7' },
  { icon: Icons.LumberjackGrey8, name: 'LumberjackGrey8' },
  { icon: Icons.LumberjackGrey9, name: 'LumberjackGrey9' },
];
