/**
 * Generated by scripts/generate-icons.js
 * DO NOT EDIT!
 */

import * as Icons from '../lumberjack-grey';

export const ICON_LIST = [
  { icon: Icons.LumerjackGrey1, name: 'LumerjackGrey1' },
  { icon: Icons.LumerjackGrey10, name: 'LumerjackGrey10' },
  { icon: Icons.LumerjackGrey11, name: 'LumerjackGrey11' },
  { icon: Icons.LumerjackGrey12, name: 'LumerjackGrey12' },
  { icon: Icons.LumerjackGrey13, name: 'LumerjackGrey13' },
  { icon: Icons.LumerjackGrey14, name: 'LumerjackGrey14' },
  { icon: Icons.LumerjackGrey15, name: 'LumerjackGrey15' },
  { icon: Icons.LumerjackGrey16, name: 'LumerjackGrey16' },
  { icon: Icons.LumerjackGrey2, name: 'LumerjackGrey2' },
  { icon: Icons.LumerjackGrey3, name: 'LumerjackGrey3' },
  { icon: Icons.LumerjackGrey4, name: 'LumerjackGrey4' },
  { icon: Icons.LumerjackGrey5, name: 'LumerjackGrey5' },
  { icon: Icons.LumerjackGrey6, name: 'LumerjackGrey6' },
  { icon: Icons.LumerjackGrey7, name: 'LumerjackGrey7' },
  { icon: Icons.LumerjackGrey8, name: 'LumerjackGrey8' },
  { icon: Icons.LumerjackGrey9, name: 'LumerjackGrey9' },
];
