/**
 * Generated by scripts/generate-icons.js
 * DO NOT EDIT!
 */

import * as Icons from '../lumberjack-grey';

export const ICON_LIST = [
  { icon: Icons.LumberjackGrey1, name: 'LumberjackGrey1' },
  { icon: Icons.LumberjackGrey10, name: 'LumberjackGrey10' },
  { icon: Icons.LumberjackGrey11, name: 'LumberjackGrey11' },
  { icon: Icons.LumberjackGrey12, name: 'LumberjackGrey12' },
  { icon: Icons.LumberjackGrey13, name: 'LumberjackGrey13' },
  { icon: Icons.LumberjackGrey14, name: 'LumberjackGrey14' },
  { icon: Icons.LumberjackGrey15, name: 'LumberjackGrey15' },
  { icon: Icons.LumberjackGrey16, name: 'LumberjackGrey16' },
  { icon: Icons.LumberjackGrey2, name: 'LumberjackGrey2' },
  { icon: Icons.LumberjackGrey3, name: 'LumberjackGrey3' },
  { icon: Icons.LumberjackGrey4, name: 'LumberjackGrey4' },
  { icon: Icons.LumberjackGrey5, name: 'LumberjackGrey5' },
  { icon: Icons.LumberjackGrey6, name: 'LumberjackGrey6' },
  { icon: Icons.LumberjackGrey7, name: 'LumberjackGrey7' },
  { icon: Icons.LumberjackGrey8, name: 'LumberjackGrey8' },
  { icon: Icons.LumberjackGrey9, name: 'LumberjackGrey9' },
  { icon: Icons.LumerjackGrey1, name: 'LumerjackGrey1' },
  { icon: Icons.LumerjackGrey10, name: 'LumerjackGrey10' },
  { icon: Icons.LumerjackGrey11, name: 'LumerjackGrey11' },
  { icon: Icons.LumerjackGrey12, name: 'LumerjackGrey12' },
  { icon: Icons.LumerjackGrey13, name: 'LumerjackGrey13' },
  { icon: Icons.LumerjackGrey14, name: 'LumerjackGrey14' },
  { icon: Icons.LumerjackGrey15, name: 'LumerjackGrey15' },
  { icon: Icons.LumerjackGrey16, name: 'LumerjackGrey16' },
  { icon: Icons.LumerjackGrey2, name: 'LumerjackGrey2' },
  { icon: Icons.LumerjackGrey3, name: 'LumerjackGrey3' },
  { icon: Icons.LumerjackGrey4, name: 'LumerjackGrey4' },
  { icon: Icons.LumerjackGrey5, name: 'LumerjackGrey5' },
  { icon: Icons.LumerjackGrey6, name: 'LumerjackGrey6' },
  { icon: Icons.LumerjackGrey7, name: 'LumerjackGrey7' },
  { icon: Icons.LumerjackGrey8, name: 'LumerjackGrey8' },
  { icon: Icons.LumerjackGrey9, name: 'LumerjackGrey9' },
];
