/**
 * Generated by scripts/generate-icons.js
 * DO NOT EDIT!
 */

import * as Icons from '../medical-grey';

export const ICON_LIST = [
  { icon: Icons.MedicalGrey1, name: 'MedicalGrey1' },
  { icon: Icons.MedicalGrey10, name: 'MedicalGrey10' },
  { icon: Icons.MedicalGrey11, name: 'MedicalGrey11' },
  { icon: Icons.MedicalGrey12, name: 'MedicalGrey12' },
  { icon: Icons.MedicalGrey13, name: 'MedicalGrey13' },
  { icon: Icons.MedicalGrey14, name: 'MedicalGrey14' },
  { icon: Icons.MedicalGrey15, name: 'MedicalGrey15' },
  { icon: Icons.MedicalGrey16, name: 'MedicalGrey16' },
  { icon: Icons.MedicalGrey17, name: 'MedicalGrey17' },
  { icon: Icons.MedicalGrey18, name: 'MedicalGrey18' },
  { icon: Icons.MedicalGrey19, name: 'MedicalGrey19' },
  { icon: Icons.MedicalGrey2, name: 'MedicalGrey2' },
  { icon: Icons.MedicalGrey20, name: 'MedicalGrey20' },
  { icon: Icons.MedicalGrey21, name: 'MedicalGrey21' },
  { icon: Icons.MedicalGrey22, name: 'MedicalGrey22' },
  { icon: Icons.MedicalGrey23, name: 'MedicalGrey23' },
  { icon: Icons.MedicalGrey24, name: 'MedicalGrey24' },
  { icon: Icons.MedicalGrey25, name: 'MedicalGrey25' },
  { icon: Icons.MedicalGrey26, name: 'MedicalGrey26' },
  { icon: Icons.MedicalGrey27, name: 'MedicalGrey27' },
  { icon: Icons.MedicalGrey28, name: 'MedicalGrey28' },
  { icon: Icons.MedicalGrey29, name: 'MedicalGrey29' },
  { icon: Icons.MedicalGrey3, name: 'MedicalGrey3' },
  { icon: Icons.MedicalGrey30, name: 'MedicalGrey30' },
  { icon: Icons.MedicalGrey31, name: 'MedicalGrey31' },
  { icon: Icons.MedicalGrey32, name: 'MedicalGrey32' },
  { icon: Icons.MedicalGrey33, name: 'MedicalGrey33' },
  { icon: Icons.MedicalGrey34, name: 'MedicalGrey34' },
  { icon: Icons.MedicalGrey35, name: 'MedicalGrey35' },
  { icon: Icons.MedicalGrey4, name: 'MedicalGrey4' },
  { icon: Icons.MedicalGrey5, name: 'MedicalGrey5' },
  { icon: Icons.MedicalGrey6, name: 'MedicalGrey6' },
  { icon: Icons.MedicalGrey7, name: 'MedicalGrey7' },
  { icon: Icons.MedicalGrey8, name: 'MedicalGrey8' },
  { icon: Icons.MedicalGrey9, name: 'MedicalGrey9' },
];
