/**
 * Generated by scripts/generate-icons.js
 * DO NOT EDIT!
 */

import * as Icons from '../mobile-ui-grey';

export const ICON_LIST = [
  { icon: Icons.MobileUiGrey1, name: 'MobileUiGrey1' },
  { icon: Icons.MobileUiGrey10, name: 'MobileUiGrey10' },
  { icon: Icons.MobileUiGrey11, name: 'MobileUiGrey11' },
  { icon: Icons.MobileUiGrey12, name: 'MobileUiGrey12' },
  { icon: Icons.MobileUiGrey13, name: 'MobileUiGrey13' },
  { icon: Icons.MobileUiGrey14, name: 'MobileUiGrey14' },
  { icon: Icons.MobileUiGrey15, name: 'MobileUiGrey15' },
  { icon: Icons.MobileUiGrey16, name: 'MobileUiGrey16' },
  { icon: Icons.MobileUiGrey17, name: 'MobileUiGrey17' },
  { icon: Icons.MobileUiGrey18, name: 'MobileUiGrey18' },
  { icon: Icons.MobileUiGrey19, name: 'MobileUiGrey19' },
  { icon: Icons.MobileUiGrey2, name: 'MobileUiGrey2' },
  { icon: Icons.MobileUiGrey20, name: 'MobileUiGrey20' },
  { icon: Icons.MobileUiGrey21, name: 'MobileUiGrey21' },
  { icon: Icons.MobileUiGrey22, name: 'MobileUiGrey22' },
  { icon: Icons.MobileUiGrey23, name: 'MobileUiGrey23' },
  { icon: Icons.MobileUiGrey24, name: 'MobileUiGrey24' },
  { icon: Icons.MobileUiGrey25, name: 'MobileUiGrey25' },
  { icon: Icons.MobileUiGrey26, name: 'MobileUiGrey26' },
  { icon: Icons.MobileUiGrey27, name: 'MobileUiGrey27' },
  { icon: Icons.MobileUiGrey28, name: 'MobileUiGrey28' },
  { icon: Icons.MobileUiGrey29, name: 'MobileUiGrey29' },
  { icon: Icons.MobileUiGrey3, name: 'MobileUiGrey3' },
  { icon: Icons.MobileUiGrey30, name: 'MobileUiGrey30' },
  { icon: Icons.MobileUiGrey31, name: 'MobileUiGrey31' },
  { icon: Icons.MobileUiGrey32, name: 'MobileUiGrey32' },
  { icon: Icons.MobileUiGrey4, name: 'MobileUiGrey4' },
  { icon: Icons.MobileUiGrey5, name: 'MobileUiGrey5' },
  { icon: Icons.MobileUiGrey6, name: 'MobileUiGrey6' },
  { icon: Icons.MobileUiGrey7, name: 'MobileUiGrey7' },
  { icon: Icons.MobileUiGrey8, name: 'MobileUiGrey8' },
  { icon: Icons.MobileUiGrey9, name: 'MobileUiGrey9' },
];
