/**
 * Generated by scripts/generate-icons.js
 * DO NOT EDIT!
 */

import * as Icons from '../music-grey';

export const ICON_LIST = [
  { icon: Icons.MusicGrey1, name: 'MusicGrey1' },
  { icon: Icons.MusicGrey10, name: 'MusicGrey10' },
  { icon: Icons.MusicGrey11, name: 'MusicGrey11' },
  { icon: Icons.MusicGrey12, name: 'MusicGrey12' },
  { icon: Icons.MusicGrey13, name: 'MusicGrey13' },
  { icon: Icons.MusicGrey14, name: 'MusicGrey14' },
  { icon: Icons.MusicGrey15, name: 'MusicGrey15' },
  { icon: Icons.MusicGrey16, name: 'MusicGrey16' },
  { icon: Icons.MusicGrey2, name: 'MusicGrey2' },
  { icon: Icons.MusicGrey3, name: 'MusicGrey3' },
  { icon: Icons.MusicGrey4, name: 'MusicGrey4' },
  { icon: Icons.MusicGrey5, name: 'MusicGrey5' },
  { icon: Icons.MusicGrey6, name: 'MusicGrey6' },
  { icon: Icons.MusicGrey7, name: 'MusicGrey7' },
  { icon: Icons.MusicGrey8, name: 'MusicGrey8' },
  { icon: Icons.MusicGrey9, name: 'MusicGrey9' },
];
