/**
 * Generated by scripts/generate-icons.js
 * DO NOT EDIT!
 */

import * as Icons from '../music-color';

export const ICON_LIST = [
  { icon: Icons.MusicColor1, name: 'MusicColor1' },
  { icon: Icons.MusicColor10, name: 'MusicColor10' },
  { icon: Icons.MusicColor11, name: 'MusicColor11' },
  { icon: Icons.MusicColor12, name: 'MusicColor12' },
  { icon: Icons.MusicColor13, name: 'MusicColor13' },
  { icon: Icons.MusicColor14, name: 'MusicColor14' },
  { icon: Icons.MusicColor15, name: 'MusicColor15' },
  { icon: Icons.MusicColor16, name: 'MusicColor16' },
  { icon: Icons.MusicColor2, name: 'MusicColor2' },
  { icon: Icons.MusicColor3, name: 'MusicColor3' },
  { icon: Icons.MusicColor4, name: 'MusicColor4' },
  { icon: Icons.MusicColor5, name: 'MusicColor5' },
  { icon: Icons.MusicColor6, name: 'MusicColor6' },
  { icon: Icons.MusicColor7, name: 'MusicColor7' },
  { icon: Icons.MusicColor8, name: 'MusicColor8' },
  { icon: Icons.MusicColor9, name: 'MusicColor9' },
];
