/**
 * Generated by scripts/generate-icons.js
 * DO NOT EDIT!
 */
        
import * as Icons from '../office-color';

export const ICON_LIST = [
  { icon: Icons.OfficeColor1, name: 'OfficeColor1' },
  { icon: Icons.OfficeColor10, name: 'OfficeColor10' },
  { icon: Icons.OfficeColor11, name: 'OfficeColor11' },
  { icon: Icons.OfficeColor12, name: 'OfficeColor12' },
  { icon: Icons.OfficeColor13, name: 'OfficeColor13' },
  { icon: Icons.OfficeColor14, name: 'OfficeColor14' },
  { icon: Icons.OfficeColor15, name: 'OfficeColor15' },
  { icon: Icons.OfficeColor16, name: 'OfficeColor16' },
  { icon: Icons.OfficeColor17, name: 'OfficeColor17' },
  { icon: Icons.OfficeColor18, name: 'OfficeColor18' },
  { icon: Icons.OfficeColor19, name: 'OfficeColor19' },
  { icon: Icons.OfficeColor2, name: 'OfficeColor2' },
  { icon: Icons.OfficeColor20, name: 'OfficeColor20' },
  { icon: Icons.OfficeColor21, name: 'OfficeColor21' },
  { icon: Icons.OfficeColor22, name: 'OfficeColor22' },
  { icon: Icons.OfficeColor23, name: 'OfficeColor23' },
  { icon: Icons.OfficeColor24, name: 'OfficeColor24' },
  { icon: Icons.OfficeColor25, name: 'OfficeColor25' },
  { icon: Icons.OfficeColor26, name: 'OfficeColor26' },
  { icon: Icons.OfficeColor27, name: 'OfficeColor27' },
  { icon: Icons.OfficeColor28, name: 'OfficeColor28' },
  { icon: Icons.OfficeColor29, name: 'OfficeColor29' },
  { icon: Icons.OfficeColor3, name: 'OfficeColor3' },
  { icon: Icons.OfficeColor30, name: 'OfficeColor30' },
  { icon: Icons.OfficeColor31, name: 'OfficeColor31' },
  { icon: Icons.OfficeColor32, name: 'OfficeColor32' },
  { icon: Icons.OfficeColor33, name: 'OfficeColor33' },
  { icon: Icons.OfficeColor34, name: 'OfficeColor34' },
  { icon: Icons.OfficeColor35, name: 'OfficeColor35' },
  { icon: Icons.OfficeColor36, name: 'OfficeColor36' },
  { icon: Icons.OfficeColor37, name: 'OfficeColor37' },
  { icon: Icons.OfficeColor38, name: 'OfficeColor38' },
  { icon: Icons.OfficeColor39, name: 'OfficeColor39' },
  { icon: Icons.OfficeColor4, name: 'OfficeColor4' },
  { icon: Icons.OfficeColor40, name: 'OfficeColor40' },
  { icon: Icons.OfficeColor5, name: 'OfficeColor5' },
  { icon: Icons.OfficeColor6, name: 'OfficeColor6' },
  { icon: Icons.OfficeColor7, name: 'OfficeColor7' },
  { icon: Icons.OfficeColor8, name: 'OfficeColor8' },
  { icon: Icons.OfficeColor9, name: 'OfficeColor9' },
];
