/**
 * Generated by scripts/generate-icons.js
 * DO NOT EDIT!
 */
        
import * as Icons from '../office-grey';

export const ICON_LIST = [
  { icon: Icons.OfficeGrey1, name: 'OfficeGrey1' },
  { icon: Icons.OfficeGrey10, name: 'OfficeGrey10' },
  { icon: Icons.OfficeGrey11, name: 'OfficeGrey11' },
  { icon: Icons.OfficeGrey12, name: 'OfficeGrey12' },
  { icon: Icons.OfficeGrey13, name: 'OfficeGrey13' },
  { icon: Icons.OfficeGrey14, name: 'OfficeGrey14' },
  { icon: Icons.OfficeGrey15, name: 'OfficeGrey15' },
  { icon: Icons.OfficeGrey16, name: 'OfficeGrey16' },
  { icon: Icons.OfficeGrey17, name: 'OfficeGrey17' },
  { icon: Icons.OfficeGrey18, name: 'OfficeGrey18' },
  { icon: Icons.OfficeGrey19, name: 'OfficeGrey19' },
  { icon: Icons.OfficeGrey2, name: 'OfficeGrey2' },
  { icon: Icons.OfficeGrey20, name: 'OfficeGrey20' },
  { icon: Icons.OfficeGrey3, name: 'OfficeGrey3' },
  { icon: Icons.OfficeGrey4, name: 'OfficeGrey4' },
  { icon: Icons.OfficeGrey5, name: 'OfficeGrey5' },
  { icon: Icons.OfficeGrey6, name: 'OfficeGrey6' },
  { icon: Icons.OfficeGrey7, name: 'OfficeGrey7' },
  { icon: Icons.OfficeGrey8, name: 'OfficeGrey8' },
  { icon: Icons.OfficeGrey9, name: 'OfficeGrey9' },
];
