/**
 * Generated by scripts/generate-icons.js
 * DO NOT EDIT!
 */
        
import * as Icons from '../security-color';

export const ICON_LIST = [
  { icon: Icons.SecurityColor1, name: 'SecurityColor1' },
  { icon: Icons.SecurityColor10, name: 'SecurityColor10' },
  { icon: Icons.SecurityColor11, name: 'SecurityColor11' },
  { icon: Icons.SecurityColor12, name: 'SecurityColor12' },
  { icon: Icons.SecurityColor13, name: 'SecurityColor13' },
  { icon: Icons.SecurityColor14, name: 'SecurityColor14' },
  { icon: Icons.SecurityColor15, name: 'SecurityColor15' },
  { icon: Icons.SecurityColor16, name: 'SecurityColor16' },
  { icon: Icons.SecurityColor2, name: 'SecurityColor2' },
  { icon: Icons.SecurityColor3, name: 'SecurityColor3' },
  { icon: Icons.SecurityColor4, name: 'SecurityColor4' },
  { icon: Icons.SecurityColor5, name: 'SecurityColor5' },
  { icon: Icons.SecurityColor6, name: 'SecurityColor6' },
  { icon: Icons.SecurityColor7, name: 'SecurityColor7' },
  { icon: Icons.SecurityColor8, name: 'SecurityColor8' },
  { icon: Icons.SecurityColor9, name: 'SecurityColor9' },
];
