/**
 * Generated by scripts/generate-icons.js
 * DO NOT EDIT!
 */
        
import * as Icons from '../security-grey';

export const ICON_LIST = [
  { icon: Icons.SecurityGrey1, name: 'SecurityGrey1' },
  { icon: Icons.SecurityGrey10, name: 'SecurityGrey10' },
  { icon: Icons.SecurityGrey11, name: 'SecurityGrey11' },
  { icon: Icons.SecurityGrey12, name: 'SecurityGrey12' },
  { icon: Icons.SecurityGrey13, name: 'SecurityGrey13' },
  { icon: Icons.SecurityGrey14, name: 'SecurityGrey14' },
  { icon: Icons.SecurityGrey15, name: 'SecurityGrey15' },
  { icon: Icons.SecurityGrey16, name: 'SecurityGrey16' },
  { icon: Icons.SecurityGrey2, name: 'SecurityGrey2' },
  { icon: Icons.SecurityGrey3, name: 'SecurityGrey3' },
  { icon: Icons.SecurityGrey4, name: 'SecurityGrey4' },
  { icon: Icons.SecurityGrey5, name: 'SecurityGrey5' },
  { icon: Icons.SecurityGrey6, name: 'SecurityGrey6' },
  { icon: Icons.SecurityGrey7, name: 'SecurityGrey7' },
  { icon: Icons.SecurityGrey8, name: 'SecurityGrey8' },
  { icon: Icons.SecurityGrey9, name: 'SecurityGrey9' },
];
