/**
 * Generated by scripts/generate-icons.js
 * DO NOT EDIT!
 */
        
import * as Icons from '../shopping-grey';

export const ICON_LIST = [
  { icon: Icons.ShoppingGrey1, name: 'ShoppingGrey1' },
  { icon: Icons.ShoppingGrey10, name: 'ShoppingGrey10' },
  { icon: Icons.ShoppingGrey11, name: 'ShoppingGrey11' },
  { icon: Icons.ShoppingGrey12, name: 'ShoppingGrey12' },
  { icon: Icons.ShoppingGrey13, name: 'ShoppingGrey13' },
  { icon: Icons.ShoppingGrey14, name: 'ShoppingGrey14' },
  { icon: Icons.ShoppingGrey15, name: 'ShoppingGrey15' },
  { icon: Icons.ShoppingGrey16, name: 'ShoppingGrey16' },
  { icon: Icons.ShoppingGrey2, name: 'ShoppingGrey2' },
  { icon: Icons.ShoppingGrey3, name: 'ShoppingGrey3' },
  { icon: Icons.ShoppingGrey4, name: 'ShoppingGrey4' },
  { icon: Icons.ShoppingGrey5, name: 'ShoppingGrey5' },
  { icon: Icons.ShoppingGrey6, name: 'ShoppingGrey6' },
  { icon: Icons.ShoppingGrey7, name: 'ShoppingGrey7' },
  { icon: Icons.ShoppingGrey8, name: 'ShoppingGrey8' },
  { icon: Icons.ShoppingGrey9, name: 'ShoppingGrey9' },
];
