/**
 * Generated by scripts/generate-icons.js
 * DO NOT EDIT!
 */
        
import * as Icons from '../shopping-color';

export const ICON_LIST = [
  { icon: Icons.ShoppingColor1, name: 'ShoppingColor1' },
  { icon: Icons.ShoppingColor10, name: 'ShoppingColor10' },
  { icon: Icons.ShoppingColor11, name: 'ShoppingColor11' },
  { icon: Icons.ShoppingColor12, name: 'ShoppingColor12' },
  { icon: Icons.ShoppingColor13, name: 'ShoppingColor13' },
  { icon: Icons.ShoppingColor14, name: 'ShoppingColor14' },
  { icon: Icons.ShoppingColor15, name: 'ShoppingColor15' },
  { icon: Icons.ShoppingColor16, name: 'ShoppingColor16' },
  { icon: Icons.ShoppingColor2, name: 'ShoppingColor2' },
  { icon: Icons.ShoppingColor3, name: 'ShoppingColor3' },
  { icon: Icons.ShoppingColor4, name: 'ShoppingColor4' },
  { icon: Icons.ShoppingColor5, name: 'ShoppingColor5' },
  { icon: Icons.ShoppingColor6, name: 'ShoppingColor6' },
  { icon: Icons.ShoppingColor7, name: 'ShoppingColor7' },
  { icon: Icons.ShoppingColor8, name: 'ShoppingColor8' },
  { icon: Icons.ShoppingColor9, name: 'ShoppingColor9' },
];
