/**
 * Generated by scripts/generate-icons.js
 * DO NOT EDIT!
 */

import * as Icons from '../skull-color';

export const ICON_LIST = [
  { icon: Icons.SkullColor1, name: 'SkullColor1' },
  { icon: Icons.SkullColor10, name: 'SkullColor10' },
  { icon: Icons.SkullColor11, name: 'SkullColor11' },
  { icon: Icons.SkullColor12, name: 'SkullColor12' },
  { icon: Icons.SkullColor13, name: 'SkullColor13' },
  { icon: Icons.SkullColor14, name: 'SkullColor14' },
  { icon: Icons.SkullColor15, name: 'SkullColor15' },
  { icon: Icons.SkullColor16, name: 'SkullColor16' },
  { icon: Icons.SkullColor2, name: 'SkullColor2' },
  { icon: Icons.SkullColor3, name: 'SkullColor3' },
  { icon: Icons.SkullColor4, name: 'SkullColor4' },
  { icon: Icons.SkullColor5, name: 'SkullColor5' },
  { icon: Icons.SkullColor6, name: 'SkullColor6' },
  { icon: Icons.SkullColor7, name: 'SkullColor7' },
  { icon: Icons.SkullColor8, name: 'SkullColor8' },
  { icon: Icons.SkullColor9, name: 'SkullColor9' },
];
