/**
 * Generated by scripts/generate-icons.js
 * DO NOT EDIT!
 */
        
import * as Icons from '../skull-grey';

export const ICON_LIST = [
  { icon: Icons.SkullGrey1, name: 'SkullGrey1' },
  { icon: Icons.SkullGrey10, name: 'SkullGrey10' },
  { icon: Icons.SkullGrey11, name: 'SkullGrey11' },
  { icon: Icons.SkullGrey12, name: 'SkullGrey12' },
  { icon: Icons.SkullGrey13, name: 'SkullGrey13' },
  { icon: Icons.SkullGrey14, name: 'SkullGrey14' },
  { icon: Icons.SkullGrey15, name: 'SkullGrey15' },
  { icon: Icons.SkullGrey16, name: 'SkullGrey16' },
  { icon: Icons.SkullGrey2, name: 'SkullGrey2' },
  { icon: Icons.SkullGrey3, name: 'SkullGrey3' },
  { icon: Icons.SkullGrey4, name: 'SkullGrey4' },
  { icon: Icons.SkullGrey5, name: 'SkullGrey5' },
  { icon: Icons.SkullGrey6, name: 'SkullGrey6' },
  { icon: Icons.SkullGrey7, name: 'SkullGrey7' },
  { icon: Icons.SkullGrey8, name: 'SkullGrey8' },
  { icon: Icons.SkullGrey9, name: 'SkullGrey9' },
];
