/**
 * Generated by scripts/generate-icons.js
 * DO NOT EDIT!
 */
        
import * as Icons from '../space-grey';

export const ICON_LIST = [
  { icon: Icons.SpaceGrey1, name: 'SpaceGrey1' },
  { icon: Icons.SpaceGrey10, name: 'SpaceGrey10' },
  { icon: Icons.SpaceGrey11, name: 'SpaceGrey11' },
  { icon: Icons.SpaceGrey12, name: 'SpaceGrey12' },
  { icon: Icons.SpaceGrey13, name: 'SpaceGrey13' },
  { icon: Icons.SpaceGrey14, name: 'SpaceGrey14' },
  { icon: Icons.SpaceGrey15, name: 'SpaceGrey15' },
  { icon: Icons.SpaceGrey16, name: 'SpaceGrey16' },
  { icon: Icons.SpaceGrey2, name: 'SpaceGrey2' },
  { icon: Icons.SpaceGrey3, name: 'SpaceGrey3' },
  { icon: Icons.SpaceGrey4, name: 'SpaceGrey4' },
  { icon: Icons.SpaceGrey5, name: 'SpaceGrey5' },
  { icon: Icons.SpaceGrey6, name: 'SpaceGrey6' },
  { icon: Icons.SpaceGrey7, name: 'SpaceGrey7' },
  { icon: Icons.SpaceGrey8, name: 'SpaceGrey8' },
  { icon: Icons.SpaceGrey9, name: 'SpaceGrey9' },
];
