/**
 * Generated by scripts/generate-icons.js
 * DO NOT EDIT!
 */
        
import * as Icons from '../space-color';

export const ICON_LIST = [
  { icon: Icons.SpaceColor1, name: 'SpaceColor1' },
  { icon: Icons.SpaceColor10, name: 'SpaceColor10' },
  { icon: Icons.SpaceColor11, name: 'SpaceColor11' },
  { icon: Icons.SpaceColor12, name: 'SpaceColor12' },
  { icon: Icons.SpaceColor13, name: 'SpaceColor13' },
  { icon: Icons.SpaceColor14, name: 'SpaceColor14' },
  { icon: Icons.SpaceColor15, name: 'SpaceColor15' },
  { icon: Icons.SpaceColor16, name: 'SpaceColor16' },
  { icon: Icons.SpaceColor2, name: 'SpaceColor2' },
  { icon: Icons.SpaceColor3, name: 'SpaceColor3' },
  { icon: Icons.SpaceColor4, name: 'SpaceColor4' },
  { icon: Icons.SpaceColor5, name: 'SpaceColor5' },
  { icon: Icons.SpaceColor6, name: 'SpaceColor6' },
  { icon: Icons.SpaceColor7, name: 'SpaceColor7' },
  { icon: Icons.SpaceColor8, name: 'SpaceColor8' },
  { icon: Icons.SpaceColor9, name: 'SpaceColor9' },
];
