/**
 * Generated by scripts/generate-icons.js
 * DO NOT EDIT!
 */

import * as Icons from '../spring-color';

export const ICON_LIST = [
  { icon: Icons.SpringColor1, name: 'SpringColor1' },
  { icon: Icons.SpringColor10, name: 'SpringColor10' },
  { icon: Icons.SpringColor11, name: 'SpringColor11' },
  { icon: Icons.SpringColor12, name: 'SpringColor12' },
  { icon: Icons.SpringColor13, name: 'SpringColor13' },
  { icon: Icons.SpringColor14, name: 'SpringColor14' },
  { icon: Icons.SpringColor15, name: 'SpringColor15' },
  { icon: Icons.SpringColor16, name: 'SpringColor16' },
  { icon: Icons.SpringColor2, name: 'SpringColor2' },
  { icon: Icons.SpringColor3, name: 'SpringColor3' },
  { icon: Icons.SpringColor4, name: 'SpringColor4' },
  { icon: Icons.SpringColor5, name: 'SpringColor5' },
  { icon: Icons.SpringColor6, name: 'SpringColor6' },
  { icon: Icons.SpringColor7, name: 'SpringColor7' },
  { icon: Icons.SpringColor8, name: 'SpringColor8' },
  { icon: Icons.SpringColor9, name: 'SpringColor9' },
];
