/**
 * Generated by scripts/generate-icons.js
 * DO NOT EDIT!
 */

import * as Icons from '../spring-grey';

export const ICON_LIST = [
  { icon: Icons.SpringGrey1, name: 'SpringGrey1' },
  { icon: Icons.SpringGrey10, name: 'SpringGrey10' },
  { icon: Icons.SpringGrey11, name: 'SpringGrey11' },
  { icon: Icons.SpringGrey12, name: 'SpringGrey12' },
  { icon: Icons.SpringGrey13, name: 'SpringGrey13' },
  { icon: Icons.SpringGrey14, name: 'SpringGrey14' },
  { icon: Icons.SpringGrey15, name: 'SpringGrey15' },
  { icon: Icons.SpringGrey16, name: 'SpringGrey16' },
  { icon: Icons.SpringGrey2, name: 'SpringGrey2' },
  { icon: Icons.SpringGrey3, name: 'SpringGrey3' },
  { icon: Icons.SpringGrey4, name: 'SpringGrey4' },
  { icon: Icons.SpringGrey5, name: 'SpringGrey5' },
  { icon: Icons.SpringGrey6, name: 'SpringGrey6' },
  { icon: Icons.SpringGrey7, name: 'SpringGrey7' },
  { icon: Icons.SpringGrey8, name: 'SpringGrey8' },
  { icon: Icons.SpringGrey9, name: 'SpringGrey9' },
];
