/**
 * Generated by scripts/generate-icons.js
 * DO NOT EDIT!
 */

import * as Icons from '../sweet-17-grey';

export const ICON_LIST = [
  { icon: Icons.Sweet17Grey1, name: 'Sweet17Grey1' },
  { icon: Icons.Sweet17Grey10, name: 'Sweet17Grey10' },
  { icon: Icons.Sweet17Grey11, name: 'Sweet17Grey11' },
  { icon: Icons.Sweet17Grey12, name: 'Sweet17Grey12' },
  { icon: Icons.Sweet17Grey13, name: 'Sweet17Grey13' },
  { icon: Icons.Sweet17Grey14, name: 'Sweet17Grey14' },
  { icon: Icons.Sweet17Grey15, name: 'Sweet17Grey15' },
  { icon: Icons.Sweet17Grey16, name: 'Sweet17Grey16' },
  { icon: Icons.Sweet17Grey17, name: 'Sweet17Grey17' },
  { icon: Icons.Sweet17Grey18, name: 'Sweet17Grey18' },
  { icon: Icons.Sweet17Grey19, name: 'Sweet17Grey19' },
  { icon: Icons.Sweet17Grey2, name: 'Sweet17Grey2' },
  { icon: Icons.Sweet17Grey20, name: 'Sweet17Grey20' },
  { icon: Icons.Sweet17Grey21, name: 'Sweet17Grey21' },
  { icon: Icons.Sweet17Grey22, name: 'Sweet17Grey22' },
  { icon: Icons.Sweet17Grey23, name: 'Sweet17Grey23' },
  { icon: Icons.Sweet17Grey24, name: 'Sweet17Grey24' },
  { icon: Icons.Sweet17Grey25, name: 'Sweet17Grey25' },
  { icon: Icons.Sweet17Grey3, name: 'Sweet17Grey3' },
  { icon: Icons.Sweet17Grey4, name: 'Sweet17Grey4' },
  { icon: Icons.Sweet17Grey5, name: 'Sweet17Grey5' },
  { icon: Icons.Sweet17Grey6, name: 'Sweet17Grey6' },
  { icon: Icons.Sweet17Grey7, name: 'Sweet17Grey7' },
  { icon: Icons.Sweet17Grey8, name: 'Sweet17Grey8' },
  { icon: Icons.Sweet17Grey9, name: 'Sweet17Grey9' },
];
