/**
 * Generated by scripts/generate-icons.js
 * DO NOT EDIT!
 */
        
import * as Icons from '../sweet-17-color';

export const ICON_LIST = [
  { icon: Icons.Sweet17Color1, name: 'Sweet17Color1' },
  { icon: Icons.Sweet17Color10, name: 'Sweet17Color10' },
  { icon: Icons.Sweet17Color11, name: 'Sweet17Color11' },
  { icon: Icons.Sweet17Color12, name: 'Sweet17Color12' },
  { icon: Icons.Sweet17Color13, name: 'Sweet17Color13' },
  { icon: Icons.Sweet17Color14, name: 'Sweet17Color14' },
  { icon: Icons.Sweet17Color15, name: 'Sweet17Color15' },
  { icon: Icons.Sweet17Color16, name: 'Sweet17Color16' },
  { icon: Icons.Sweet17Color17, name: 'Sweet17Color17' },
  { icon: Icons.Sweet17Color18, name: 'Sweet17Color18' },
  { icon: Icons.Sweet17Color19, name: 'Sweet17Color19' },
  { icon: Icons.Sweet17Color2, name: 'Sweet17Color2' },
  { icon: Icons.Sweet17Color20, name: 'Sweet17Color20' },
  { icon: Icons.Sweet17Color21, name: 'Sweet17Color21' },
  { icon: Icons.Sweet17Color22, name: 'Sweet17Color22' },
  { icon: Icons.Sweet17Color23, name: 'Sweet17Color23' },
  { icon: Icons.Sweet17Color24, name: 'Sweet17Color24' },
  { icon: Icons.Sweet17Color25, name: 'Sweet17Color25' },
  { icon: Icons.Sweet17Color3, name: 'Sweet17Color3' },
  { icon: Icons.Sweet17Color4, name: 'Sweet17Color4' },
  { icon: Icons.Sweet17Color5, name: 'Sweet17Color5' },
  { icon: Icons.Sweet17Color6, name: 'Sweet17Color6' },
  { icon: Icons.Sweet17Color7, name: 'Sweet17Color7' },
  { icon: Icons.Sweet17Color8, name: 'Sweet17Color8' },
  { icon: Icons.Sweet17Color9, name: 'Sweet17Color9' },
];
