/**
 * Generated by scripts/generate-icons.js
 * DO NOT EDIT!
 */

import * as Icons from '../time-color';

export const ICON_LIST = [
  { icon: Icons.TimeColor1, name: 'TimeColor1' },
  { icon: Icons.TimeColor10, name: 'TimeColor10' },
  { icon: Icons.TimeColor11, name: 'TimeColor11' },
  { icon: Icons.TimeColor12, name: 'TimeColor12' },
  { icon: Icons.TimeColor13, name: 'TimeColor13' },
  { icon: Icons.TimeColor14, name: 'TimeColor14' },
  { icon: Icons.TimeColor15, name: 'TimeColor15' },
  { icon: Icons.TimeColor16, name: 'TimeColor16' },
  { icon: Icons.TimeColor2, name: 'TimeColor2' },
  { icon: Icons.TimeColor3, name: 'TimeColor3' },
  { icon: Icons.TimeColor4, name: 'TimeColor4' },
  { icon: Icons.TimeColor5, name: 'TimeColor5' },
  { icon: Icons.TimeColor6, name: 'TimeColor6' },
  { icon: Icons.TimeColor7, name: 'TimeColor7' },
  { icon: Icons.TimeColor8, name: 'TimeColor8' },
  { icon: Icons.TimeColor9, name: 'TimeColor9' },
];
