/**
 * Generated by scripts/generate-icons.js
 * DO NOT EDIT!
 */

import * as Icons from '../time-grey';

export const ICON_LIST = [
  { icon: Icons.TimeGrey1, name: 'TimeGrey1' },
  { icon: Icons.TimeGrey10, name: 'TimeGrey10' },
  { icon: Icons.TimeGrey11, name: 'TimeGrey11' },
  { icon: Icons.TimeGrey12, name: 'TimeGrey12' },
  { icon: Icons.TimeGrey13, name: 'TimeGrey13' },
  { icon: Icons.TimeGrey14, name: 'TimeGrey14' },
  { icon: Icons.TimeGrey15, name: 'TimeGrey15' },
  { icon: Icons.TimeGrey16, name: 'TimeGrey16' },
  { icon: Icons.TimeGrey2, name: 'TimeGrey2' },
  { icon: Icons.TimeGrey3, name: 'TimeGrey3' },
  { icon: Icons.TimeGrey4, name: 'TimeGrey4' },
  { icon: Icons.TimeGrey5, name: 'TimeGrey5' },
  { icon: Icons.TimeGrey6, name: 'TimeGrey6' },
  { icon: Icons.TimeGrey7, name: 'TimeGrey7' },
  { icon: Icons.TimeGrey8, name: 'TimeGrey8' },
  { icon: Icons.TimeGrey9, name: 'TimeGrey9' },
];
