/**
 * Generated by scripts/generate-icons.js
 * DO NOT EDIT!
 */

import * as Icons from '../travel-color';

export const ICON_LIST = [
  { icon: Icons.TravelColor1, name: 'TravelColor1' },
  { icon: Icons.TravelColor10, name: 'TravelColor10' },
  { icon: Icons.TravelColor11, name: 'TravelColor11' },
  { icon: Icons.TravelColor12, name: 'TravelColor12' },
  { icon: Icons.TravelColor13, name: 'TravelColor13' },
  { icon: Icons.TravelColor14, name: 'TravelColor14' },
  { icon: Icons.TravelColor15, name: 'TravelColor15' },
  { icon: Icons.TravelColor16, name: 'TravelColor16' },
  { icon: Icons.TravelColor2, name: 'TravelColor2' },
  { icon: Icons.TravelColor3, name: 'TravelColor3' },
  { icon: Icons.TravelColor4, name: 'TravelColor4' },
  { icon: Icons.TravelColor5, name: 'TravelColor5' },
  { icon: Icons.TravelColor6, name: 'TravelColor6' },
  { icon: Icons.TravelColor7, name: 'TravelColor7' },
  { icon: Icons.TravelColor8, name: 'TravelColor8' },
  { icon: Icons.TravelColor9, name: 'TravelColor9' },
];
