/**
 * Generated by scripts/generate-icons.js
 * DO NOT EDIT!
 */
        
import * as Icons from '../travel-grey';

export const ICON_LIST = [
  { icon: Icons.TravelGrey1, name: 'TravelGrey1' },
  { icon: Icons.TravelGrey10, name: 'TravelGrey10' },
  { icon: Icons.TravelGrey11, name: 'TravelGrey11' },
  { icon: Icons.TravelGrey12, name: 'TravelGrey12' },
  { icon: Icons.TravelGrey13, name: 'TravelGrey13' },
  { icon: Icons.TravelGrey14, name: 'TravelGrey14' },
  { icon: Icons.TravelGrey15, name: 'TravelGrey15' },
  { icon: Icons.TravelGrey16, name: 'TravelGrey16' },
  { icon: Icons.TravelGrey2, name: 'TravelGrey2' },
  { icon: Icons.TravelGrey3, name: 'TravelGrey3' },
  { icon: Icons.TravelGrey4, name: 'TravelGrey4' },
  { icon: Icons.TravelGrey5, name: 'TravelGrey5' },
  { icon: Icons.TravelGrey6, name: 'TravelGrey6' },
  { icon: Icons.TravelGrey7, name: 'TravelGrey7' },
  { icon: Icons.TravelGrey8, name: 'TravelGrey8' },
  { icon: Icons.TravelGrey9, name: 'TravelGrey9' },
];
