/**
 * Generated by scripts/generate-icons.js
 * DO NOT EDIT!
 */
        
import * as Icons from '../valentine-color';

export const ICON_LIST = [
  { icon: Icons.ValentineColor1, name: 'ValentineColor1' },
  { icon: Icons.ValentineColor10, name: 'ValentineColor10' },
  { icon: Icons.ValentineColor11, name: 'ValentineColor11' },
  { icon: Icons.ValentineColor12, name: 'ValentineColor12' },
  { icon: Icons.ValentineColor13, name: 'ValentineColor13' },
  { icon: Icons.ValentineColor14, name: 'ValentineColor14' },
  { icon: Icons.ValentineColor15, name: 'ValentineColor15' },
  { icon: Icons.ValentineColor16, name: 'ValentineColor16' },
  { icon: Icons.ValentineColor17, name: 'ValentineColor17' },
  { icon: Icons.ValentineColor18, name: 'ValentineColor18' },
  { icon: Icons.ValentineColor19, name: 'ValentineColor19' },
  { icon: Icons.ValentineColor2, name: 'ValentineColor2' },
  { icon: Icons.ValentineColor20, name: 'ValentineColor20' },
  { icon: Icons.ValentineColor21, name: 'ValentineColor21' },
  { icon: Icons.ValentineColor22, name: 'ValentineColor22' },
  { icon: Icons.ValentineColor23, name: 'ValentineColor23' },
  { icon: Icons.ValentineColor24, name: 'ValentineColor24' },
  { icon: Icons.ValentineColor25, name: 'ValentineColor25' },
  { icon: Icons.ValentineColor3, name: 'ValentineColor3' },
  { icon: Icons.ValentineColor4, name: 'ValentineColor4' },
  { icon: Icons.ValentineColor5, name: 'ValentineColor5' },
  { icon: Icons.ValentineColor6, name: 'ValentineColor6' },
  { icon: Icons.ValentineColor7, name: 'ValentineColor7' },
  { icon: Icons.ValentineColor8, name: 'ValentineColor8' },
  { icon: Icons.ValentineColor9, name: 'ValentineColor9' },
];
