/**
 * Generated by scripts/generate-icons.js
 * DO NOT EDIT!
 */
        
import * as Icons from '../valentine-grey';

export const ICON_LIST = [
  { icon: Icons.ValentineGrey1, name: 'ValentineGrey1' },
  { icon: Icons.ValentineGrey10, name: 'ValentineGrey10' },
  { icon: Icons.ValentineGrey11, name: 'ValentineGrey11' },
  { icon: Icons.ValentineGrey12, name: 'ValentineGrey12' },
  { icon: Icons.ValentineGrey13, name: 'ValentineGrey13' },
  { icon: Icons.ValentineGrey14, name: 'ValentineGrey14' },
  { icon: Icons.ValentineGrey15, name: 'ValentineGrey15' },
  { icon: Icons.ValentineGrey16, name: 'ValentineGrey16' },
  { icon: Icons.ValentineGrey17, name: 'ValentineGrey17' },
  { icon: Icons.ValentineGrey18, name: 'ValentineGrey18' },
  { icon: Icons.ValentineGrey19, name: 'ValentineGrey19' },
  { icon: Icons.ValentineGrey2, name: 'ValentineGrey2' },
  { icon: Icons.ValentineGrey20, name: 'ValentineGrey20' },
  { icon: Icons.ValentineGrey21, name: 'ValentineGrey21' },
  { icon: Icons.ValentineGrey22, name: 'ValentineGrey22' },
  { icon: Icons.ValentineGrey23, name: 'ValentineGrey23' },
  { icon: Icons.ValentineGrey24, name: 'ValentineGrey24' },
  { icon: Icons.ValentineGrey25, name: 'ValentineGrey25' },
  { icon: Icons.ValentineGrey3, name: 'ValentineGrey3' },
  { icon: Icons.ValentineGrey4, name: 'ValentineGrey4' },
  { icon: Icons.ValentineGrey5, name: 'ValentineGrey5' },
  { icon: Icons.ValentineGrey6, name: 'ValentineGrey6' },
  { icon: Icons.ValentineGrey7, name: 'ValentineGrey7' },
  { icon: Icons.ValentineGrey8, name: 'ValentineGrey8' },
  { icon: Icons.ValentineGrey9, name: 'ValentineGrey9' },
];
