/**
 * Generated by scripts/generate-icons.js
 * DO NOT EDIT!
 */
        
import * as Icons from '../virtual-reality-grey';

export const ICON_LIST = [
  { icon: Icons.VirtualRealityGrey1, name: 'VirtualRealityGrey1' },
  { icon: Icons.VirtualRealityGrey10, name: 'VirtualRealityGrey10' },
  { icon: Icons.VirtualRealityGrey11, name: 'VirtualRealityGrey11' },
  { icon: Icons.VirtualRealityGrey12, name: 'VirtualRealityGrey12' },
  { icon: Icons.VirtualRealityGrey13, name: 'VirtualRealityGrey13' },
  { icon: Icons.VirtualRealityGrey14, name: 'VirtualRealityGrey14' },
  { icon: Icons.VirtualRealityGrey15, name: 'VirtualRealityGrey15' },
  { icon: Icons.VirtualRealityGrey16, name: 'VirtualRealityGrey16' },
  { icon: Icons.VirtualRealityGrey2, name: 'VirtualRealityGrey2' },
  { icon: Icons.VirtualRealityGrey3, name: 'VirtualRealityGrey3' },
  { icon: Icons.VirtualRealityGrey4, name: 'VirtualRealityGrey4' },
  { icon: Icons.VirtualRealityGrey5, name: 'VirtualRealityGrey5' },
  { icon: Icons.VirtualRealityGrey6, name: 'VirtualRealityGrey6' },
  { icon: Icons.VirtualRealityGrey7, name: 'VirtualRealityGrey7' },
  { icon: Icons.VirtualRealityGrey8, name: 'VirtualRealityGrey8' },
  { icon: Icons.VirtualRealityGrey9, name: 'VirtualRealityGrey9' },
];
