/**
 * Generated by scripts/generate-icons.js
 * DO NOT EDIT!
 */

import * as Icons from '../virtual-reality-color';

export const ICON_LIST = [
  { icon: Icons.VirtualRealityColor1, name: 'VirtualRealityColor1' },
  { icon: Icons.VirtualRealityColor10, name: 'VirtualRealityColor10' },
  { icon: Icons.VirtualRealityColor11, name: 'VirtualRealityColor11' },
  { icon: Icons.VirtualRealityColor12, name: 'VirtualRealityColor12' },
  { icon: Icons.VirtualRealityColor13, name: 'VirtualRealityColor13' },
  { icon: Icons.VirtualRealityColor14, name: 'VirtualRealityColor14' },
  { icon: Icons.VirtualRealityColor15, name: 'VirtualRealityColor15' },
  { icon: Icons.VirtualRealityColor16, name: 'VirtualRealityColor16' },
  { icon: Icons.VirtualRealityColor2, name: 'VirtualRealityColor2' },
  { icon: Icons.VirtualRealityColor3, name: 'VirtualRealityColor3' },
  { icon: Icons.VirtualRealityColor4, name: 'VirtualRealityColor4' },
  { icon: Icons.VirtualRealityColor5, name: 'VirtualRealityColor5' },
  { icon: Icons.VirtualRealityColor6, name: 'VirtualRealityColor6' },
  { icon: Icons.VirtualRealityColor7, name: 'VirtualRealityColor7' },
  { icon: Icons.VirtualRealityColor8, name: 'VirtualRealityColor8' },
  { icon: Icons.VirtualRealityColor9, name: 'VirtualRealityColor9' },
];
