/**
 * Generated by scripts/generate-icons.js
 * DO NOT EDIT!
 */

import * as Icons from '../zoo-color';

export const ICON_LIST = [
  { icon: Icons.ZooColor1, name: 'ZooColor1' },
  { icon: Icons.ZooColor10, name: 'ZooColor10' },
  { icon: Icons.ZooColor11, name: 'ZooColor11' },
  { icon: Icons.ZooColor12, name: 'ZooColor12' },
  { icon: Icons.ZooColor13, name: 'ZooColor13' },
  { icon: Icons.ZooColor14, name: 'ZooColor14' },
  { icon: Icons.ZooColor15, name: 'ZooColor15' },
  { icon: Icons.ZooColor16, name: 'ZooColor16' },
  { icon: Icons.ZooColor17, name: 'ZooColor17' },
  { icon: Icons.ZooColor18, name: 'ZooColor18' },
  { icon: Icons.ZooColor19, name: 'ZooColor19' },
  { icon: Icons.ZooColor2, name: 'ZooColor2' },
  { icon: Icons.ZooColor20, name: 'ZooColor20' },
  { icon: Icons.ZooColor21, name: 'ZooColor21' },
  { icon: Icons.ZooColor22, name: 'ZooColor22' },
  { icon: Icons.ZooColor23, name: 'ZooColor23' },
  { icon: Icons.ZooColor24, name: 'ZooColor24' },
  { icon: Icons.ZooColor25, name: 'ZooColor25' },
  { icon: Icons.ZooColor3, name: 'ZooColor3' },
  { icon: Icons.ZooColor4, name: 'ZooColor4' },
  { icon: Icons.ZooColor5, name: 'ZooColor5' },
  { icon: Icons.ZooColor6, name: 'ZooColor6' },
  { icon: Icons.ZooColor7, name: 'ZooColor7' },
  { icon: Icons.ZooColor8, name: 'ZooColor8' },
  { icon: Icons.ZooColor9, name: 'ZooColor9' },
];
