/**
 * Generated by scripts/generate-icons.js
 * DO NOT EDIT!
 */

import * as Icons from '../zoo-grey';

export const ICON_LIST = [
  { icon: Icons.ZooGrey1, name: 'ZooGrey1' },
  { icon: Icons.ZooGrey10, name: 'ZooGrey10' },
  { icon: Icons.ZooGrey11, name: 'ZooGrey11' },
  { icon: Icons.ZooGrey12, name: 'ZooGrey12' },
  { icon: Icons.ZooGrey13, name: 'ZooGrey13' },
  { icon: Icons.ZooGrey14, name: 'ZooGrey14' },
  { icon: Icons.ZooGrey15, name: 'ZooGrey15' },
  { icon: Icons.ZooGrey16, name: 'ZooGrey16' },
  { icon: Icons.ZooGrey17, name: 'ZooGrey17' },
  { icon: Icons.ZooGrey18, name: 'ZooGrey18' },
  { icon: Icons.ZooGrey19, name: 'ZooGrey19' },
  { icon: Icons.ZooGrey2, name: 'ZooGrey2' },
  { icon: Icons.ZooGrey20, name: 'ZooGrey20' },
  { icon: Icons.ZooGrey21, name: 'ZooGrey21' },
  { icon: Icons.ZooGrey22, name: 'ZooGrey22' },
  { icon: Icons.ZooGrey23, name: 'ZooGrey23' },
  { icon: Icons.ZooGrey24, name: 'ZooGrey24' },
  { icon: Icons.ZooGrey25, name: 'ZooGrey25' },
  { icon: Icons.ZooGrey3, name: 'ZooGrey3' },
  { icon: Icons.ZooGrey4, name: 'ZooGrey4' },
  { icon: Icons.ZooGrey5, name: 'ZooGrey5' },
  { icon: Icons.ZooGrey6, name: 'ZooGrey6' },
  { icon: Icons.ZooGrey7, name: 'ZooGrey7' },
  { icon: Icons.ZooGrey8, name: 'ZooGrey8' },
  { icon: Icons.ZooGrey9, name: 'ZooGrey9' },
];
